### ISSUE TITLE
DBGp proxy

### ISSUE THREAD

**Issue by adrianofoschi** [xdebug/vscode-php-debug#107]
How to use/set DBGp proxy similar to PHPStorm?

https://confluence.jetbrains.com/display/PhpStorm/Multi-user+debugging+in+PhpStorm+with+Xdebug+and+DBGp+proxy

**Comment by felixfbecker** [comment]
Never tried it. Have you tried connecting to the proxy? Are you getting any errors?

**Comment by adrianofoschi** [comment]
Sorry I am a newbie about this topic. 
In PHPStorm I can set dbgp proxy in its settings. How Can I try to connect to the proxy in vscode?

**Comment by felixfbecker** [comment]
There are no proxy-related settings in VS Code. I don't know how the proxy works - if it doesn't work with the extension atm feel free to do a PR

**Comment by adrianofoschi** [comment]
It is well documented there https://derickrethans.nl/debugging-with-multiple-users.html

**Comment by felixfbecker** [comment]
It might be, but please understand that I just don't have the time to implement such a feature

**Comment by adrianofoschi** [comment]
Se should send a proxinit command to the server. Can you help me to understand  how to modify it?

Details there:
https://xdebug.org/docs-dbgp.php#just-in-time-debugging-and-debugger-proxies

**Comment by felixfbecker** [comment]
All requests are implemented in xdebugConnection.ts.  For example, here is the run request: https://github.com/felixfbecker/vscode-php-debug/blob/master/src/xdebugConnection.ts#L737

Not sure when that command is supposed to be send, but here is where the init packet is handled: https://github.com/felixfbecker/vscode-php-debug/blob/master/src/phpDebug.ts#L246

**Comment by adrianofoschi** [comment]
Probably the command should be sent on first connection. I don't know typescript so it is difficult for me to make a PR. Anyway I will try, thanks you for your support.

**Comment by adrianofoschi** [comment]
I'm going to work on this feature. Do you know a way to "send message" to xdebug server with curl or similar low level client? Thanks you

**Comment by felixfbecker** [comment]
Yes, there is a debugclient which you can build on xdebug.org, and you could also use telnet. But honestly I never used this, implementing this directly is much easier - you already have the all the message handling and socket stuff being taken care of

**Comment by adrianofoschi** [comment]
It works perfectly with nodejs net socket.

**Comment by felixfbecker** [comment]
This whole extension communicates with XDebug through a nodejs net socket, so yeah, I figured that 😄

**Comment by adrianofoschi** [comment]
Well, I'm trying to complete my work to integrate the proxy request in your plugin but It seems too hard for me.
The problem is this request should be performed in "sync mode" before the first init request. Then I think it could be inserted into phpDebug.ts constructor, but I have no idea how to make it syncronous.

This is the snippet in ts code

        const client = net.createConnection({port: 9001, host: '10.0.1.200'}, function() {
            client.write('proxyinit -p 9001 -k vscode -m 1', function() {
                console.log('test');
            });
        });

        client.on('data', (data:string) => {
            console.log(data.toString());
            client.end();
        });
        
        client.on('end', () => {
            console.log('disconnected from server');
        });

**Comment by pc-magas** [comment]
As seen on the latest merge there were an successfull attempt to implement dbGp proxy support, thus I want to know has it been integrated to the next release?
