### ISSUE TITLE
Always skip this exception/line - Feature requests

### ISSUE THREAD

**Issue by QwertyZW** [xdebug/vscode-php-debug#146]
PHP version:  7.1
XDebug version:  2.5
Adapter version:  1.10

I have a codebase(wordpress 4.7.2) that keeps spitting out the same exceptions at the same lines. I'd like to see other less common exceptions and not the ones wordpress keeps running into.

Is there a way to tell the debugger to always skip a specific exception while being told to break at exceptions?

**Comment by felixfbecker** [comment]
There is an open PR for this

**Comment by QwertyZW** [comment]
This https://github.com/felixfbecker/vscode-php-debug/pull/66 ?

**Comment by rrd108** [comment]
+1

**Comment by turowicz** [comment]
+1 !!! need ability to skip certain exceptions somehow

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by turowicz** [comment]
I think you can close this issue, the PR added required functionality.

#66

**Comment by zobo** [comment]
Will close this issue. I am considering adding negative glob batching to `ignore`.
