### ISSUE TITLE
XDebug with xampp loading forever

### ISSUE THREAD

**Issue by zyarnold** [xdebug/vscode-php-debug#163]
PHP version:  xampp latest
XDebug version:  latest
Adapter version:  i dunno im using xampp

Your launch.json:  all default
XDebug php.ini config:  all default

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

**Comment by benyaminl** [comment]
@felixfbecker I also experience some issue with php_xdebug-2.5.3-5.6-vc11.dll, I think their build is broken, especially while export database from phpmyadmin, it will crash and open so many port above 49k untill 58k (49000-58000 aka random port between it). I really pain in the ass. So I use DataGrip for accessing the mysql. And that would make Xampp and the PHP and Apache run forever without error log I think, my error log is clean. Xampp old build run php 5.6.
