### ISSUE TITLE
Cannot continue after exception occurred

### ISSUE THREAD

**Issue by Robouste** [xdebug/vscode-php-debug#165]
PHP version:  7.1.3
XDebug version:  2.5.4
Adapter version:  How to know ?

Your launch.json:  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```
XDebug php.ini config:  

xdebug.remote_enable = 1
xdebug.remote_autostart = 1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  ?
Adapter logfile (from setting `"log": true` in launch.json):  ?

I'm working with Symfony3 and wanted to try this extension. After configuring everything, I launch my app and it stopped immediatly after launch on a wierd exception I was not aware of. The problem is that I can't continue the excecution, no matter how I smash the green 'play' button. I also tried right-click on exception in the stack than 'continue' but it stay stuck

![image](https://cloud.githubusercontent.com/assets/5463032/26207262/52f9170e-3be7-11e7-9411-2f57467bacee.png)

**Comment by felixfbecker** [comment]
If your program crashes, you can't continue.
I can't help you without log files. See the Readme.

**Comment by Robouste** [comment]
Ok, I'll generate the log.

But the program doesn't crash, without debugging, it works fine. And if I launch debugging after the application, it works fine.

**Comment by Robouste** [comment]
[xdebug.log.txt](https://github.com/felixfbecker/vscode-php-debug/files/1011283/xdebug.log.txt)

here is the logs.

But don't waste too much time on this. Like I said, if I run debug after the app, it works fine (juste A LOT of exception but I can keep debugging).

I'm just wondering why I can't pass this first exception.

**Comment by felixfbecker** [comment]
You can also just disable breaking on Exceptions

**Comment by zobo** [comment]
I'll close this old one with works as designed. I hope to implement better exception support but there are VS Code limitations.
