### ISSUE TITLE
My win7 environment, always prompt: debug adapter process has been unexpectedly terminated

### ISSUE THREAD

**Issue by hulang** [xdebug/vscode-php-debug#184]
环境：windows7 + iis7 + fastcgi + php5

PHP version:  5.5
XDebug version:  2.5.5
Adapter version:  没有

Your launch.json:  
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9800
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9800
        }
    ]
}`
XDebug php.ini config:  
xdebug.remote_enable = 1
xdebug.remote_autostart = 1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php

```

**Comment by djgreg13** [comment]
Same issue here

**Comment by kingkrausel** [comment]
Same on Ubuntu

**Comment by felixfbecker** [comment]
@kingkrausel @djgreg13 please see #203

**Comment by chichihchen** [comment]
Same issue on Ubuntu 17.10, vscode 1.18.1.
