### ISSUE TITLE
All breakpoints gets unverified on VSCode running a Yii2 advanced project. WHY?

### ISSUE THREAD

**Issue by weinand** [xdebug/vscode-php-debug#201]
_From @MichalYosef on November 7, 2017 15:48_

Hello, I'm running an advanced Yii 2 app on XAMPP

- VSCode Version: 1.17.2
- OS Version: Windows 10

am trying to debug

I Disabled all extensions at the VS Code except from the PHP Debug 1.11.1
it didnt help.

every breakpoint I put gets immediatly unverified

Would appreciate a lot any hint...

_Copied from original issue: Microsoft/vscode#37779_

**Comment by weinand** [comment]
@MichalYosef do breakpoints get immediately unverified while running a debug session or while outside of a session?

**Comment by weinand** [comment]
_From @MichalYosef on November 7, 2017 21:34_

Immediatly

בתאריך 7 בנוב 2017 18:15,‏ "Andre Weinand" <notifications@github.com> כתב:

@MichalYosef <https://github.com/michalyosef> do breakpoints get
immediately unverified while running a debug session or while outside?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/37779#issuecomment-342534382>,
or mute the thread

**Comment by weinand** [comment]
_From @MichalYosef on November 7, 2017 21:35_

immediatley

**Comment by weinand** [comment]
sorry, but "immediately" is not a helpful answer. Let's try it again:
do breakpoints get unverified while running a debug session or while not running a debug session?

**Comment by weinand** [comment]
_From @MichalYosef on November 7, 2017 22:13_

sorry but i dont understand how they can break when not running
anyways it seems like a more serious problem, right now my pc won't
restart....

בתאריך 8 בנוב 2017 00:00,‏ "Andre Weinand" <notifications@github.com> כתב:

**Comment by weinand** [comment]
_From @mradcertica on November 7, 2017 22:33_

@weinand  Interesting.  I'm having the same issue.  All breakpoints become unverified.
Open php source.
Switch to debug.
Listen for XDebug
Set breakpoint in source file.
Access page that calls into function with breakpoint.
Breakpoint becomes unverified.

**Comment by weinand** [comment]
_From @MichalYosef on November 8, 2017 6:56_

yep
same here
the breakpoints gets unverified on runtime

2017-11-08 0:33 GMT+02:00 mradcertica <notifications@github.com>:

**Comment by feliw** [comment]
I encounter this also, after I change the xdebug .dll type to 64bit it can run properly again. Not sure if this can apply to you also or not.

**Comment by zobo** [comment]
Cleanup, old issue.
