### ISSUE TITLE
Breakpoint doesn't stop on Windows 10 / Docker project

### ISSUE THREAD

**Issue by piqoni** [xdebug/vscode-php-debug#218]
PHP version:  PHP 7.2.0 (my local)  PHP 5.6.32 (my docker with Xdebug enabled)
XDebug version: 2.5.5

I'm coming from Linux (where it worked flawlessly with the same configuration/docker project) so perhaps I might be doing something wrong or simply missing a "windows" step. 

My latest launch.json configuration in windows:
```
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "pathMappings": {
                "/var/www/html": "c:\\Users\\username\\project-name"
            },
            "port": 9000,
            "log": true
        },
```
Enabled port forwarding from guest to host of port 9000 in VirtualBox. 

My xdebug configuration (that IP is the host IP as seen by docker). 
![image](https://user-images.githubusercontent.com/3144671/34096044-2a6e39f0-e3d4-11e7-83e1-ebe9f9b1564a.png)

All the best, and thanks for the Extension.

**Comment by jefferyleung** [comment]
As a temporary workaround, I've setup another loopback IP on my host:
sudo ifconfig lo0 alias 17.254.254.254.

And in php.ini, I've set:
xdebug.remote_host=17.254.254.254.

**Comment by di3663** [comment]
Not work too, xdebug do work.

## version
```
D:\WORKSPACE>php_console -v

D:\WORKSPACE>D:\TOOL\php\php.exe -c D:\TOOL\php\php_console.ini -v
PHP 7.2.0 (cli) (built: Nov 29 2017 00:14:49) ( NTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans
```

## stated but not pause on breakpoint.
![default](https://user-images.githubusercontent.com/20258455/34910715-1c01f00a-f8f6-11e7-96b8-b405451f6abd.PNG)



## logs
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
-> disconnectRequest
{ command: 'disconnect',
  arguments: { restart: false },
  type: 'request',
  seq: 3 }
<- disconnectResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'disconnect',
  success: true }

```

## eclipse
![1](https://user-images.githubusercontent.com/20258455/34910733-8d3df426-f8f6-11e7-80af-7fb2023d094a.png)

**Comment by snpdev** [comment]
Having the same problem using ddev local development on Windows 10 with VS Code and xdebug.

I started an issue thread in the ddev project, but thought it would be valuable to cross-reference here:

https://github.com/drud/ddev/issues/735
https://github.com/drud/ddev/issues/736

**Comment by Spown** [comment]
Probably the same thing. I'm using XAMMP. There are breaks on errors, but neither breakpoints nor ``stopOnEntry`` do work.

**Comment by zobo** [comment]
Closing old issue. Please open new one with current info if this is still a problem.
