### ISSUE TITLE
Php-debug doesnot start debugging on browser reload when using PHP's built in web server (vscode)

### ISSUE THREAD

**Issue by steven7mwesigwa** [xdebug/vscode-php-debug#223]
PHP version:   PHP 7.0.22-3
XDebug version:  Xdebug v2.6.0alpha1
Adapter version:  Zend OPcache v7.0.22-3

Your launch.json:  
`{`
`	// Use IntelliSense to learn about possible attributes.`
`	// Hover to view descriptions of existing attributes.`
`	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387`
`	"version": "0.2.0",`
`	"configurations": [`
`		{`
`			"name": "Listen for XDebug",`
`			"type": "php",`
`			"request": "launch",`
`			"port": 9000`
`		},`
`		{`
`			"name": "Launch currently open script",`
`			"type": "php",`
`			"request": "launch",`
`			"program": "${file}",`
`			"cwd": "${fileDirname}",`
`			"port": 9000`
`		}`
`	]`
`}`
XDebug php.ini config:
`[XDebug]`
`xdebug.remote_autostart = 1`
`xdebug.remote_connect_back = 1`
`xdebug.remote_enable=On` 
`xdebug.remote_host="localhost"`
`xdebug.remote_port=9000`
`xdebug.remote_handler="dbgp"`

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php

   $cookie_name = "user";
   $cookie_value = "Alex Poster";
   $expiry_time = time() + 3600;
   setcookie($cookie_name, $cookie_value, $expiry_time);
   echo "<h1>One Moment</h1> ";
   if (count($_COOKIE)) {
       echo $_COOKIE["user"] . PHP_EOL;
    } else {
       echo("No Cookie");
   }
   function foo(array $g)
   {
      return count($g);
   }
   echo foo([34, 56, 56]);

```
## **ISSUE:**
_(Using local Apache set up web Server)_

Project Hierachy:
`1`
`|`
`|------ .vscode`
`|                 |---launch.json`
`|-----index.php`

When i move my _project folder_ to my set "**DocumentRoot**" of the _local apache web server_,

1. And open project in vscode,
2. Then "start Debugging" which initiates a Listen on Port: 9000,
3. Then i go to my browser and open "_`localhost/1/index.php`_",

Am _automatically_ switched to vscode and "actual debugging" works well as expected.

![screenshot from 2018-01-11 09-59-44](https://user-images.githubusercontent.com/24929438/34812071-153dfe3c-f6b5-11e7-8750-512a645d340f.png)

## **ACTUAL PROBLEM:** 
 _(Using PHP's Built in Web Server)_

Now when i move the _SAME_ _project folder_ **OUTSIDE** the "**DocumentRoot**" Directory,
1. And open project in vscode,
2. Then "start Debugging" which initiates a Listen on Port: 9000,
3. Then set up PHP's built in web Server,
4. `php -S localhost:4050`,
5. Then i go to my browser and open "_`localhost:4050/1`_",

The Page loads **BUT** am **_not_** automatically switched to vscode as before therefore "actual debugging" doesnot start.

![debug_fail](https://user-images.githubusercontent.com/24929438/34813168-edf73d66-f6b9-11e7-81cb-8602f811f6cc.png)

![screenshot from 2018-01-11 10-37-51](https://user-images.githubusercontent.com/24929438/34813257-4eef9906-f6ba-11e7-8389-a3addf8ec877.png)

**NOTE:** i don't get any feed back from the "DEBUG CONSOLE" of vscode.

## **QUESTION:** 
Isn't it possible to work **outside** the _"local Apache web server"_ and use _PHP's built-in server_  instead and be able to debug your projects normally in _vscode_?
(Or am i doing Something Wrong ?)

**Comment by zobo** [comment]
I need to test this, but I believe it has to do that VS Code will not focus the window on "new thread".

**Comment by zobo** [comment]
This is a very old issue. A configuration snippet exists how to setup the build in PHP web server that will do what was asked here.
