### ISSUE TITLE
Don't show array elements

### ISSUE THREAD

**Issue by phantom2024** [xdebug/vscode-php-debug#226]
Hi!
I have a issue and i don't know what happens. The debugger does not show the array elements on the $session_categorie, and the same environment on phpstorm works. these are the screenshots, the last is from phpstorm.
![captura de pantalla 2018-01-15 a la s 15 42 23](https://user-images.githubusercontent.com/875676/34957286-bdda8fca-fa0b-11e7-8088-e2a9980901d3.png)
![captura de pantalla 2018-01-15 a la s 15 42 59](https://user-images.githubusercontent.com/875676/34957297-c59c8b78-fa0b-11e7-92b9-d951979638ed.png)
![captura de pantalla 2018-01-15 a la s 15 46 11](https://user-images.githubusercontent.com/875676/34957304-c9dc132a-fa0b-11e7-94c9-4a862e58987f.png)

what is wrong?
Regards!

**Comment by anatoli26** [comment]
Same issue here. The structure elements are not expanded in on-hover preview, but are shown correctly in the Variables panel.

**Comment by zobo** [comment]
Cannot reproduce. If this is still revelvant, please reopen and provide debug adapter and xdebug logs.
