### ISSUE TITLE
Debug adapter process has terminated unexpectedly when doing remote debug 

### ISSUE THREAD

**Issue by reizamv** [xdebug/vscode-php-debug#232]
PHP version:   7.2.1
XDebug version:  2.6.0RC2
Adapter version:  

Your launch.json:  
XDebug php.ini config:  
 "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
XDebug logfile (from setting `xdebug.remote_log` in php.ini):  no value
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php
if (isset($_POST['username']))
{
	include ("/config/koneksi.php");
	$username=htmlentities((trim($_POST['username'])));
	$password=htmlentities($_POST['password']);
	
	$login=mysql_query("select * from tb_admin where nama_admin='$username' and password='$password'",$koneksi);
	
	$cek_login=mysql_num_rows($login);
		if (empty($cek_login))
		{
			?><script language="javascript">
			alert("Maaf, Password Anda salah!!");
			document.location="index.php";
			</script><?php  
		}
		else
		{
			//daftarkan ID jika user dan password BENAR
			while ($row=mysql_fetch_array($login))
			{
				$id=$row[0];
				$status=$row[3];
				$hak=$row[4];
				$id_user=$row[5];
				//session_register('id');
				//session_register('username');
				$_SESSION['username'] =$username;
				$_SESSION['hak']=$hak;
				$_SESSION['id_user']=$id_user;
			}
			if ($hak=="Panitia") {
				echo "<script> document.location.href='home.php'; </script>";	
			} else if ($hak=="User") {
				echo "<script> document.location.href='homeuser.php'; </script>";
			}
			
		}
}else{
	unset($_POST['username']);
	unset($_POST['hak']);
}
```

**Comment by zobo** [comment]
Not enough info to understand what is happening, and really old. Please make a new issue with all the logging if this is still the case.
