### ISSUE TITLE
pathMapping example on VSCode Marketplace still not correct

### ISSUE THREAD

**Issue by Didel** [xdebug/vscode-php-debug#233]
I just spent an hour or so trying to set up VSCode and Xdebug (in combination with DrupalVM). Being relatively new to VSCode, I don't have lots of experience yet in configuration files. But at work I am used to working with PHPStorm, so I do have experience in using XDebug and setting that up. I copied the example code (from the VSCode Marketplace) and couldn't get it to work, when suddenly I saw the `$` prefixed in another configuration example. That led me to this repo, and eventually I noticed the (probably) highly related issue #207 .

### **Tl;DR:** 
pathMapping example code on [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug#user-content-remote-host-debugging) (and thus also in the VSCode Extension Info page) lacks an `$` before `{workspaceRoot}`, which was already fixed on Github by #207.

User @ooystein noticed this as well: https://github.com/felixfbecker/vscode-php-debug/pull/207#issuecomment-358629097

### Screenshot of code on github:
<img width="923" alt="schermafbeelding 2018-01-27 om 00 05 43" src="https://user-images.githubusercontent.com/915243/35464411-0b1075be-02f6-11e8-9f5a-38707eed5257.png">

### Screenshot on marketplace:
<img width="778" alt="schermafbeelding 2018-01-27 om 00 05 30" src="https://user-images.githubusercontent.com/915243/35464410-0af9afb4-02f6-11e8-998d-fd8dd5d4c2a2.png">

**Comment by designgears** [comment]
I came here to mention the same thing...

**Comment by Neejoh** [comment]
Same here, this took me way to long to figure out (ashamed to say). But it needs to be fixed, such a small step for a man, giant leap for....the rest trying to figure this out.

**Comment by aimcom** [comment]
Maybe you could add an example for Windows directories to the documentation as well. It took me an hour to figure out that the drive letter has to be written in lowercase and that slashes have to be written as `/` and not as `\\`...

This works for me:
```
"/var/www/html": "c:/Users/Example/FooBar"
```

**Comment by dhavalgshah** [comment]
Update should now reflect that `${workspaceRoot}` is deprecated in favour of `${workspaceFolder}`.

Also should have an usage example when in multiroot environment with may be a link to [VSCode Variable Reference](https://code.visualstudio.com/docs/editor/variables-reference).

**Comment by techieshark** [comment]
I think this is now fixed yeah?

https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug#user-content-remote-host-debugging

![image](https://user-images.githubusercontent.com/1072292/132219624-c2f4795b-081d-4037-9a4e-85ad72683319.png)

(just ran across this open issue while searching for something else)

**Comment by zobo** [comment]
Indeed you are right. Closing.
