### ISSUE TITLE
Not correct code page show elements names in debugging.

### ISSUE THREAD

**Issue by xmihey** [xdebug/vscode-php-debug#251]
PHP version:  5.6.10
XDebug version:  2.4.1 
Adapter version:  2.2.29

Your launch.json:  {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "max_depth": 5,
            "stopOnEntry": false,
            "port": 9000
        }
XDebug php.ini config:  
[xdebug]
  xdebug.default_enable=1
   
  xdebug.remote_enable=1
  xdebug.remote_handler=dbgp
  xdebug.remote_host=localhost
  xdebug.remote_port=9000
  xdebug.remote_autostart=1
  xdebug.remote_log=0
  xdebug.max_nesting_level = 100

zend_extension="/Applications/MAMP/bin/php/php5.6.10/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so"

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php
<?php
$array = array(
    "foo" => "bar",
    "bar" => "foo",
);
$array2 = array(
    "Приветствие" => "КУ-КУ",
    "Прощание" => "Па-Ка",
);
var_dump($array);
var_dump($array2);
?>
```
var_dump show correct array elements name.
<img width="354" alt="default" src="https://user-images.githubusercontent.com/37571876/37640683-6771c4d2-2c1f-11e8-8827-6a34b0c0c956.png">
But, debugging does not correctly display the names of array elements.
The names in code page cp-1252, and the values in utf-8
<img width="637" alt="default" src="https://user-images.githubusercontent.com/37571876/37640847-0be4dd88-2c20-11e8-9f91-3649def46001.png">

**Comment by zobo** [comment]
This is a Xdebug XML encoding issue but can be solved with extended properties support. PR is already open.

**Comment by zobo** [comment]
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.16.0
