### ISSUE TITLE
Debugger locks up the php process and adds an "Everything" breakpoint

### ISSUE THREAD

**Issue by chris-schmitz** [xdebug/vscode-php-debug#255]
PHP version:  7.1.13
XDebug version:  2.6.0
Adapter version:  1.12.2

Your launch.json:  
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```

XDebug php.ini config:  
```
[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1

;customizations
zend_extension = /usr/local/Cellar/php71/7.1.8_20/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so
```

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  I'm not running php remotely
Adapter logfile (from setting `"log": true` in launch.json):  
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }
new connection 1
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 1 } }
<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (2:10:34 PM)' } ] } }
```

Code snippet to reproduce:  
```php
<?php

error_log('test'); // with a breakpoint on this line
```

Over the last couple of days I've been running into an issue where I can no longer stop on breakpoints and my php process gets locked up. 

![php debugger not working](https://user-images.githubusercontent.com/2437424/38211371-dc8dd520-367f-11e8-9e04-e6981aefc113.gif)

I've been using the debugger regularly for a while now and it's worked perfectly. It's only been the last couple of days (since 2018-03-28-ish) that this has been happing. 

As you can see in the gif above I tried to create a test project with the most simple setup possible to see if the issue was coming from my codebase, but I'm still getting the issue. 

As a side note, I've noticed that whenever I start the debugger an "Everything" breakpoint option gets automatically checked. I looked through VSCode's guides for debugging and can't find mention of this breakpoint so I'm not sure if it's a vscode thing or a php-debug thing. I also can't remember if it's always been there or if I just now noticed it. 

Please let me know if there's anything else I can do or give to help. Thanks!

**Comment by jasonwilliams** [comment]
This is still an issue (Everything being set by default)
