### ISSUE TITLE
Variables tree collapses after each step

### ISSUE THREAD

**Issue by asharpe** [xdebug/vscode-php-debug#256]
PHP version:  5.6
XDebug version:  2.5.5
Adapter version:  1.12.2

According to https://github.com/Microsoft/vscode/issues/32199#issuecomment-321597173 the editor tries to preserve the tree state while stepping and suggests that 

> If a scope collapses while stepping, this is a problem of the backend (debug adapter inside the debug extension)

While stepping through code and inspecting a structure with some depth it is somewhat annoying to have to expand the variables for every step

**Comment by felixfbecker** [comment]
@weinand could you comment on under what condition vscode would not be able to maintain the tree state?

**Comment by asharpe** [comment]
You can see that I've expanded `$config` in this screenshot...

![screen shot 2018-04-05 at 2 14 28 pm](https://user-images.githubusercontent.com/975844/38347002-d927fa10-38db-11e8-86eb-e2da520fce7e.png)

Now I step once, and you can see that `$config` has collapsed...

![screen shot 2018-04-05 at 2 14 37 pm](https://user-images.githubusercontent.com/975844/38347021-f75fd28c-38db-11e8-9ef8-60ade4ee7f8d.png)

**Comment by asharpe** [comment]
I just tested the node debugger and it works as expected

**Comment by anatoli26** [comment]
Same issue here. I have a lot of deep nested structures, doing 5 clicks on each step becomes quite tedious quickly.

**Comment by zobo** [comment]
Cant reproduce with latest code. Is this sill relevant?
