### ISSUE TITLE
Feature request: Add support for Logpoints

### ISSUE THREAD

**Issue by kajes** [xdebug/vscode-php-debug#258]
In version 1.22 of VS Code, released in March 2018, there is a new Logpoints feature introduced. With Logpoints, developers get the ability to log output using VS Code's debugger, but without stopping execution of the code.

According to the [release notes](https://code.visualstudio.com/updates/v1_22#_logpoints), debug extensions will have to add support for this new feature to be able to use it.

I would love to see this feature being implemented for the PHP debugger too.

**Comment by felixfbecker** [comment]
Happy to review a PR

**Comment by insprintorob** [comment]
+1 for this

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)
