### ISSUE TITLE
Variable content as long string is truncated

### ISSUE THREAD

**Issue by blufix79** [xdebug/vscode-php-debug#261]
PHP version:  5.5.8
XDebug version:  2.2.3

Your launch.json:  
"version": "0.2.0",
```
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9001
        }
    ]
```

In debug mode, the variable value that contains long string is truncated and not is showed all, both in preview and in the variables panel. How can this behavior be resolved?

Thank you.

**Comment by mciesin** [comment]
@skippednote @felixfbecker maybe it would be possible to implement getting full value of a property using dbgp's [property_value](https://xdebug.org/docs-dbgp.php#property-get-property-set-property-value) command, e.g. when copying the value using context menu.

Changing `max_data` explicitly to `-1` may cause the slow down in some cases.

I saw that you can get full value using PHPStorm without changing `max_data` in XDebug's configuration - they are probably using `property_value` command to achieve this result.

**Comment by zobo** [comment]
There's sadly no native interface in VS Code to "view property value" like in Visual Studio. There is a "Copy Value" option that could be used for this.
