### ISSUE TITLE
env option in launch.json

### ISSUE THREAD

**Issue by Spown** [xdebug/vscode-php-debug#264]
v1.12.3

it doesn't do anything

``<property name="$_ENV" fullname="$_ENV" type="array" children="0" numchildren="0" page="0" pagesize="32"></property>``

**Comment by Spown** [comment]
I found that env settings are getting applied to ``$_SERVER`` superglobal. Is this intentional?

**Comment by felixfbecker** [comment]
Please provide the documents asked for in the issue template.

**Comment by zobo** [comment]
If you "listen" for Xdebug and not start the process, it cannot set the env. Also $_ENV is only set when `variables_order` is properly set in php.ini. https://www.php.net/manual/en/reserved.variables.environment.php#98113

There was also a _bug_ where setting `env` in `launch.json` and starting a `program` would set only the defined variables and not merge them with current env.
