### ISSUE TITLE
"(object value omitted)"

### ISSUE THREAD

**Issue by ghost** [xdebug/vscode-php-debug#277]
PHP version:  7.2.4
XDebug version:  php_xdebug-2.6.0-7.2-vc15-nts-x86_64.dll
Adapter version:  

Your launch.json:  {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
XDebug php.ini config:  
[xdebug]
zend_extension=php_xdebug-2.6.0-7.2-vc15-nts-x86_64.dll
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_connect_back = 1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  n/a
Adapter logfile (from setting `"log": true` in launch.json):  n/a

Code snippet to reproduce:  n/a

So, all objects show the string "(object value omitted)"; unsure what the use of this is for debugging with things other than primitive types?

**Comment by SidIcarus** [comment]
try adding this to your launch config: `"xdebugSettings": { "show_hidden": 1 }`

**Comment by zobo** [comment]
Seems to be with XML or DOM in PHP. Closing. Please reopen with log and code sample if this is still an issue.
