### ISSUE TITLE
VS code on Windows mangling remote paths on linux

### ISSUE THREAD

**Issue by richardeaxon** [xdebug/vscode-php-debug#283]
When using VS code on Windows to do remote debug on linux but with VS code mounting the workspace via SSH FS on linux is there any way to get the paths to not be mangled into Windows format (backslashes)? I have no local source code on my Windows machine.

I have the following path mappings (VS code says the workspace is at ssh://dev/):

```
            "pathMappings": {
                "/var/www/html/richarde": "ssh://dev/${workspaceFolder}"
            }

```
If I set a breakpoint I get the following in the log:

```
-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments: 
   { source: 
      { name: 'Port.php',
        path: 'ssh://dev/axonvx-backend/lib/classes/Port.php' },
     lines: [ 392 ],
     breakpoints: [ { line: 392 } ],
     sourceModified: false },
  type: 'request',
  seq: 3 }

```
This is clearly incorrect as ssh://dev/ should read /var/www/html/richarde

If I then manually force a breakpoint using xdebug_break() in the code I get the following response:

```
<- stackTraceResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'stackTrace',
  success: true,
  body: 
   { stackFrames: 
      [ { id: 1,
          name: 'Port->getDetails',
          source: 
           { name: 'Port.php',
             path: 'C:\\VScode\\ssh:\\dev\\axonvx-backend\\lib\\classes\\Port.php' },
          line: 391,
          column: 1 },

```
Where does C:\\VScode come from - the C:\\VScode was not in the pathmapping so the local file cannot be found? 

Is there a way to fix the set breakpoint mapping and the response path mapping?

**Comment by jasonterando** [comment]
Looking at paths.ts - I think the plug-in might be getting confused because of "ssh:" - there's some code that tries to detect drive letters when setting up the XDebug URIs. 

I think your choices are:

1. Create an NFS connection to your Linux box (probably not much fun and may not even be possible based upon security)
2. If you can do a shell connection via SSH, you should be able to copy the file files locally using something like WinSCP, and set up your pathMapping reference to where you copy them to

**Comment by AnrDaemon** [comment]
Mount remote FS locally, or setup two-way rsync to your dev box.
Either way, this is not really VScode issue.

**Comment by zobo** [comment]
I'm not sure if I want to support `ssh://` file formats. I have not yet seen this. Today the far superior solution is to use VS Code Remote - SSH.
Let me know if this is still an issue, and what extensions are in use to set this up.
