### ISSUE TITLE
File not found - Mac client with Windows IIS server

### ISSUE THREAD

**Issue by Hackmodford** [xdebug/vscode-php-debug#284]
PHP version:  7.0
XDebug version:  php_xdebug-2.6.0-7.0-vc14-nts.dll

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "c:\\inetpub\\mamobile dev\\mamobile": "${workspaceFolder}"
            }
        }
    ]
}
```

Problem:
VSCode cannot find files because the path is incorrect. I believe this is because I am using a mac as a client debugger with the host being a windows IIS server.

<img width="467" alt="screen-shot-2018-07-12-at-5 47 58-pm" src="https://user-images.githubusercontent.com/326668/42713071-11d13d08-86bc-11e8-81a5-c11d47dc6eaf.png">

```
/Users/hackmodford/Code/PHPStorm Projects/ma-mobile-webservice/routes\Inventory.php (incorrect path in message)
/Users/hackmodford/Code/PHPStorm Projects/ma-mobile-webservice/routes/Inventory.php (path of file in vscode)
/Users/hackmodford/Code/PHPStorm Projects/ma-mobile-webservice/routes/Inventory.php (path in FS)
```

Looks like the paths.ts needs to be fixed to address this.

**Comment by Hackmodford** [comment]
This seems to be related to #216

**Comment by Hackmodford** [comment]
Adding this to line 48 of paths.ts solves the problem for me. However, I am no typescript expert, so I imagine there is a better solution?

```    
if (serverIsWindows && !isWindowsUri(localPath)) {
        //Change all the backslashes to forward slashes.
        let re = /\\/gi;
        localPath = localPath.replace(re, "/");
}
```

**Comment by zobo** [comment]
Closing this as it is very old and this part of code was improved and tested. Please reopen if the case is still there.

The configuration posted by OP is correct.
