### ISSUE TITLE
[Feature request] Don't halt on events outside the project tree / Halt only on specific files

### ISSUE THREAD

**Issue by andvaranaut** [xdebug/vscode-php-debug#291]
Hi, first of all, great work on the extension!

I have been debugging a few projects lately which work on a database. As such, I usually have phpmyadmin open in another browser tab.

Unfortunately, due to some incompatibilities with PHP 7.2, the phpmyadmin I'm using has an annoying habit of throwing exceptions, which are then caught by XDebug. This leads to VS Code getting focus, stopping execution of phpmyadmin and opening a phpmyadmin file in a new tab.

I have worked around this adding the phpmyadmin directory to the "ignore" glob in launch.json, which works fine (although it's, of course, a phpmyadmin-specific fix). But it might be nice to have a specific setting key to ignore all exceptions, warnings and such coming from outside the root of the current project. 

Perhaps supporting something like an "include" or "onlyFiles" key (the complement of "ignore"), which could in turn then be set to ["${workspaceFolder}/**"] would be enough.

Best regards!

**Comment by zobo** [comment]
I'm currently finishing #874 where `skipFiles` uses a positive and negative globs. I could similarly extend matching of `ignored` and you could then do a  `["!${workspaceFolder}/**","**"]`.
