### ISSUE TITLE
Can't open file on a network folder while debugging

### ISSUE THREAD

**Issue by arnakazim** [xdebug/vscode-php-debug#298]
PHP version:  7.0.29
XDebug version:  2.6.0
Adapter version: 1.12.4

My launch.json:  

```
{
    // Utilisez IntelliSense pour en savoir plus sur les attributs possibles.
    // Pointez pour afficher la description des attributs existants.
    // Pour plus d'informations, visitez : https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        }
    ]
}

```
My PHP project is on a network folder (//srv-fic01/utilisateurs/ArnaudO/Development/nutri-uk/). I opened it with this path (not a mapped folder).

I have setup breakpoints for debugging. I launch debugging of the project and execute the script in my browser.

The execution of the scripts stops at the first breakpoint (shown in the call stack of the debugging tool) but VSCode can't open the file to highlight where it has stopped and an error message is shown stating that it is unable to open the file.

The error message is showing that it is trying to open the file "file:///UTILISATEURS/ArnaudO/Development/nutri-uk/src/public/test.php" instead of the file "file:///**srv-fic01**/UTILISATEURS/ArnaudO/Development/nutri-uk/src/public/test.php" and it is where lies the issue.

![image](https://user-images.githubusercontent.com/18421982/44455823-4ce32c00-a5ff-11e8-8605-dea865ba5791.png)

**Comment by zobo** [comment]
Hi. I'm still digging through old issues. Has this been solved for you, or just became irrelevant?

**Comment by arnakazim** [comment]
Hello, the way I solved it was to have a local copy on my local disk and I synced it with my network folder.
