### ISSUE TITLE
Pauses on breakpoint but only for a few seconds, acts like it's stopped but can't see any variables

### ISSUE THREAD

**Issue by billrobclark** [xdebug/vscode-php-debug#302]
PHP version:  7.0
XDebug version:  2.6.1
Adapter version:

Your launch.json:  
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
XDebug php.ini config:
xdebug.remote_enable = 1
xdebug.remote_autostart = 1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

This is just in VSCode when running the debugger and I refresh the page I'm debugging. Localhost. Seems like some definite weirdness going on.

**Comment by steyep** [comment]
I've been experiencing the same thing. Changing xdebug's config to port 9001 appeared to resolve the issue but evidently that was only temporary.

**Comment by ettoredn** [comment]
Do you by any chance trigger another request while the first is paused on the breakpoint? If so, this might relate to #301

**Comment by steyep** [comment]
Yeah, actually. My issue seems to be identical to what's described in #301

**Comment by billrobclark** [comment]
Yeah port 9001 seems to stay on breakpoint longer, but not permanently.

**Comment by franksl** [comment]
I'm having the same problem, it happens especially when I step the debugger into a file that is not actually open in the editor, as soon as the file opens up the debugger seems to disconnect, the variables/watch tab becomes empty and I have to restart the debugger. Trying to hit the pause button doesn't do anything.
Frank

**Comment by billrobclark** [comment]
Any update on this? Very hard to debug this way.

**Comment by franksl** [comment]
In the meantime you can download and use the previous version 1.12.4, this worked to me. Please refer to  #301 for instructions (the two issues may be related)

**Comment by zobo** [comment]
Old issue, closing.
