### ISSUE TITLE
Not hitting at Break point  when using laravel

### ISSUE THREAD

**Issue by aneeskodappana** [xdebug/vscode-php-debug#303]
Breakpoint only hit when using localhost/laravel/public URL.

When i use ``` php artisan serve ``` It's not hitting.

PHP version:  PHP 7.1.9
XDebug version:  2.6.1
Adapter version:

launch.json:  
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```
XDebug php.ini config:
zend_extension = c:\wamp64\bin\php\php7.1.9\ext\php_xdebug-2.6.1-7.1-vc14-x86_64.dll

**Comment by abovetempo** [comment]
I was using wamp with laravel and had problems getting breakpoints to hit in vs code. To fix it I had to add the xdebug settings to the php.ini file artisan serve uses as well as the file wamp was using. Here is what i added to the php.ini file that my artisan serve uses:

`[xdebug]
zend_extension="c:/wamp64/bin/php/php7.0.29/ext/php_xdebug-2.6.1-7.0-vc14-x86_64.dll"

xdebug.remote_enable = On
xdebug.remote_autostart = 1
xdebug.profiler_enable = off
xdebug.profiler_enable_trigger = off
xdebug.profiler_output_name = cachegrind.out.%t.%p
xdebug.profiler_output_dir ="c:/wamp64/tmp"
xdebug.show_local_vars=0`
