### ISSUE TITLE
Not stopping on breakpoint when using Docker

### ISSUE THREAD

**Issue by ChrisTaylorDeveloper** [xdebug/vscode-php-debug#316]
PHP version:  7.1
XDebug version:  2.6.1 
Adapter version: 1.12.6

launch.json:  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": true,
            "pathMappings": {
                "/var/www/html": "/home/chris/test-debugging"
              }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

XDebug php.ini config (in fact this is /usr/local/etc/php/conf.d/xdebug.ini):
zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_host=172.17.0.2
xdebug.remote_log=/var/www/html/xdebug.log
xdebug.remote_connect_back=0
xdebug.remote_port=9000

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Log opened at 2018-10-14 05:47:16
I: Connecting to configured address/port: 172.17.0.2:9000.
W: Creating socket for '172.17.0.2:9000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(
Log closed at 2018-10-14 05:47:16

Adapter logfile (from setting `"log": true` in launch.json):
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }

Code snippet to reproduce:

Hello, I cannot get vscode php debug to stop on any breakpoints - I am using a very simple test php project.  I am running the project from Docker on my Ubuntu laptop.  Any advice greatly appreciated.

**Comment by danielcaldas** [comment]
Had the same issue, but for me the problem was that my mapping was wrong. Are you sure you have the proper mapping `"/var/www/html": "/home/chris/test-debugging"`?

**Comment by CTaylorGuitar** [comment]
Hello, thank you for your message.

I got everything working in the end with the set up outlined in this 
Gist https://gist.github.com/CTaylorGuitar/d37e29fab3d5db72fdd8f8a533ec125d

Chris

**Comment by paulmiller3000** [comment]
Just ran into the exact same problem. Unfortunately the gist @ChrisTaylorDeveloper mentioned is no longer available. Any advice?

**Comment by zobo** [comment]
Try to enable `log:true` in launch.json. See if IDE receives the connection from PHP in docker.
Try to add xdebug_info(); somewhere in index.php and look at the logs if the connection is established.
Try to add xdebug_break() somewhere to see if it break. Probably missing pathMappings.

You can also try using vscode remote containers...

**Comment by paulmiller3000** [comment]
Wow that was fast, thanks @zobo ! Solved it with the following:

```
// Excerpt from launch.json
{
    "name": "Listen for Xdebug",
    "type": "php",
    "request": "launch",
    "port": 9003,
    "pathMappings": {
        "/var/www/html": "${workspaceRoot}"
    }
},
```
zend_extension=xdebug

[xdebug]
xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
xdebug.start_with_request=yes
xdebug.client_port=9003
```
