### ISSUE TITLE
Change font family to custom one | macOS

### ISSUE THREAD

**Issue by Mibeon** [xdebug/vscode-php-debug#317]
PHP version:  7.2
XDebug version:  2.6.1

Hello dear dev team,

could you tell us how to change font-family on macOS in your extension?
Currently "Monaco" font is used.
I use in all my dev tools another font and want to change it also here.

Please, give us a tipp or build it into extension settings.

Thank you guys.

**Comment by zobo** [comment]
This is a vscode setting. Like this for example https://stackoverflow.com/questions/29960057/which-font-is-used-in-visual-studio-code-editor-and-how-to-change-fonts
