### ISSUE TITLE
Simplify generated launch.json 

### ISSUE THREAD

**Issue by isidorn** [xdebug/vscode-php-debug#318]
Hey,

VSCode dev here. This milestone I am looking into simplifing generated `launch.json` for various extensions Microsoft/vscode#62851

The `launch.json` that PHP generates is attached at the end. I think it is cool and not too complex but we can improve this a bit

- [ ] How often do user change `port`, should it be removed. Can you auto detect what port to use, to potentially append it in the [resolveDebugConifguraiton](https://github.com/Microsoft/vscode/blob/b4c6906b62e3199eee87c17649979939a4e43323/src/vs/vscode.d.ts#L8214) call. The resolve could also nicely append the cwd based on the program attribute and the user should not be worried about that one
- [ ] Consider using a [DebugConfigurationProvider](https://github.com/Microsoft/vscode/blob/b4c6906b62e3199eee87c17649979939a4e43323/src/vs/vscode.d.ts#L8191) and the provideDebugConfiguration could use the quickPick api to ask the user he would like to listen to xDebug or to launch current file, and based on that only create one configuration
- [ ] You are not contributing `configurationSnippets`. These snippets make it easier for the user to add new launch configurations. Here's an [example](https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L169) how node is doing it

If you agree with the suggestions I am making here I am also here to help with any potential questions you might have. The changes should not require a lot of work but will simplify the flow a lot imho. It should be much less complex and not too much like a wizard experience

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

```

**Comment by isidorn** [comment]
@felixfbecker Are there any plans to address this?
Do you agree with my suggesstions here?
If you do not have cycles to address this but would like to see it done, I can try to get some users to provide a PR which tackles this.

Thanks a lot

**Comment by felixfbecker** [comment]
The suggestions make sense to me, but unfortunately I don't have capacity to implement them. Happy to review a PR though.

**Comment by isidorn** [comment]
Thanks for your reponse. I will add a Help Wanted in the issue in VSCode and we will see if we get some volunterees

**Comment by AnrDaemon** [comment]
Re: port: there's no other way to differentiate debugging sessions.
Yes, you would not change it often, but you WILL have change it, when need to debug more than one script at a time, or when connecting foreign debugger configured for a different port.

**Comment by zobo** [comment]
This is a terribly old issue. But let's see:
- I would not remote `port` as it's so important and using the wrong one causes the worst problems (debugging does not start). By leaving it there, the user is reminded of it. We have a `resolveDebugConifguraiton` call now and I plan to extend it with php executable and Xdebug detection. But that can only work when starting the debug program. In listen scenario, we are still unable to do this.
- quickPick sound interesting, I'll make a task and see how it works out.
- `configurationSnippets` were implemented
