### ISSUE TITLE
无法在 ".vscode" 文件夹内创建 "launch.json" 文件 ({0})。

### ISSUE THREAD

**Issue by kouzhudong** [xdebug/vscode-php-debug#322]
PHP version:  
XDebug version:  
Adapter version:

Your launch.json:  
XDebug php.ini config:

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php

```

**Comment by phoenixgao** [comment]
I have the same issue:

VSCode: Insider 1.29
 After installing the extension and try to open the launch.json, I got this error message:

`Unable to create 'launch.json' file inside the '.vscode' folder ({0}).`
