### ISSUE TITLE
XDebug is disconnected by VSCode with "HandleAsyncRequest timeout"

### ISSUE THREAD

**Issue by rr-appadaptive** [xdebug/vscode-php-debug#323]
It is about three weeks, that I did the last php-debug with VSCode (successfully then). Now the debugging session always stops with "HandleAsyncRequest timeout" whenever a XDebug session is started and a request is sent to the php-backend running in a docker-container.

PHP version:  7.2.11
XDebug version:  2.6
Adapter version:

Your launch.json:  
`{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9021,
            "log": true,
            "pathMappings": {
                "/var/www/Web": "${workspaceRoot}"
            }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9021
        }
    ]
}`
XDebug php.ini config:
`[xdebug]
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
; The IP pointing to the client machine's IP Address you are DEBUGGING with
xdebug.remote_host=192.168.6.43
; xdebug.remote_host=docker.for.mac.host.internal
xdebug.remote_port=9021
xdebug.remote_log=/var/www/Web/xdebug.log`

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Log opened at 2018-12-07 10:13:43
I: Connecting to configured address/port: 192.168.6.43:9021.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///var/www/Web/index.php" language="PHP" xdebug:language_version="7.2.11" protocol_version="1.0" appid="22"><engine version="2.6.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>

<- breakpoint_list -i 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="1"></response>

<- breakpoint_list -i 2
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="2"></response>

<- breakpoint_set -i 3 -t exception -x *
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="3" id="220001"></response>

<- run -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="4" status="stopping" reason="ok"></response>

Log closed at 2018-12-07 10:14:29
Adapter logfile (from setting `"log": true` in launch.json):
`<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true }

new connection 1
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 1 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  seq: 3,
  type: 'request' }

<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }

-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [ '*' ] },
  seq: 4,
  type: 'request' }

<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 4,
  command: 'setExceptionBreakpoints',
  success: true }

-> configurationDoneRequest
{ command: 'configurationDone', seq: 5, type: 'request' }

-> threadsRequest
{ command: 'threads', seq: 6, type: 'request' }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 6,
  command: 'threads',
  success: true,
  body: 
   { threads: [ Thread { id: 1, name: 'Request 1 (11:13:43 AM)' } ] } }

-> disconnectRequest
{ command: 'disconnect',
  arguments: { restart: false },
  seq: 7,
  type: 'request' }

-> threadsRequest
{ command: 'threads', seq: 8, type: 'request' }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 8,
  command: 'threads',
  success: true,
  body: 
   { threads: [ Thread { id: 1, name: 'Request 1 (11:13:43 AM)' } ] } }

`

Code snippet to reproduce:

```php

```

**Comment by zobo** [comment]
Closing very old issue. Looks like a part of the code that was completely rewritten.
