### ISSUE TITLE
"debug.openExplorerOnEnd": true => No debug view on restarting debug

### ISSUE THREAD

**Issue by anatoli26** [xdebug/vscode-php-debug#324]
Hi,

Great add-on, very useful, thanks a lot! I've just found 2 issues, here's one (and probably it's not the fault of the add-on, but rather the VS Code itself, please advise):

When I choose the option `"debug.openExplorerOnEnd": true`, it works as intended, i.e. when I stop the debugger, I get the Explorer view. But if I restart the debug session, I get the Explorer view too, though it should show the Debug view.

**Comment by zobo** [comment]
Yes, out of scope of this extension. It is a VS Code feature.
