### ISSUE TITLE
Longest prefix matching for pathMapping server paths?

### ISSUE THREAD

**Issue by bjoluc** [xdebug/vscode-php-debug#331]
In my docker container with XDebug I have two volumes mounted: 

- `/var/www/html` mounts a `wordpress` folder in my Code workspace. That folder is ignored by git, as it only contains a WordPress installation.
- `/var/www/html/wp-content/themes/my-theme` mounts a  `my-theme` folder in my workspace, which is subject of my work and tracked by git.

I have added pathMappings to my launch.json like this:
```json
"pathMappings": {
     "/var/www/html/wp-content/themes/my-theme": "${workspaceRoot}/my-theme",
     "/var/www/html": "${workspaceRoot}/wordpress"
}
```

Unfortunately, as soon as I include `"/var/www/html"` in the `pathMappings`, server files within `/var/www/html/wp-content/themes/my-theme` are mapped to the corresponding `${workspaceRoot}/wordpress` subdirectory, instead of the `${workspaceRoot}/my-theme` folder.
What I would like the extension to do in this scenario is performing a longest prefix matching for server paths.
Are there any plans for implementing this in the future? Or am I missing a point here maybe?
If this feature is welcome, I would certainly offer to implement it!

**Comment by alecgeatches** [comment]
@felixfbecker @bjoluc Would also love this feature as well. When mounting volumes with vagrant/docker, the local file structure often doesn't match the remote file structure, and this makes the current `pathMappings` setup only work for one mount at a time.
