### ISSUE TITLE
Can not show long query on Debug Console

### ISSUE THREAD

**Issue by ithieund** [xdebug/vscode-php-debug#334]
Issue: long text variable such as long query can not be fully displayed in the Debug Console, the string was truncated.

Expected behavior: show the full text.

PHP version:  All
XDebug version:  2.5.5
Adapter version: 1.12.6

Your launch.json:  
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```

XDebug php.ini config:
zend_extension = "{$path}/php-5.6/lib/extensions/xdebug.so"
xdebug.remote_enable=1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
None

Adapter logfile (from setting `"log": true` in launch.json):
None

Code snippet to reproduce:
Not needed

**Comment by zobo** [comment]
This is controlled by `xdebugSettings` `max_data`.
