### ISSUE TITLE
[Feature request] Stop execution without stop listening to XDebug

### ISSUE THREAD

**Issue by lllopo** [xdebug/vscode-php-debug#335]
I often want to stop the execution of the currently debugged php process, but this also stops VS Code from further listening to XDebug. This behavior is very annoying, since on each such case, I have to re-launch the debugger listening (which I sometimes forget). 
I'd rather say the stop button should only kill the process without stopping the debugger listening or (if this is possible) to have two separate buttons for the current and my suggested behavior.

**Comment by felixfbecker** [comment]
The restart button should do what you want

**Comment by lllopo** [comment]
Ok, thanks. A bit confusing, though.

**Comment by zobo** [comment]
Related #366 . Closing.
