### ISSUE TITLE
Cannot make remote connection at all

### ISSUE THREAD

**Issue by bvanschie** [xdebug/vscode-php-debug#336]
PHP version:  7.0.32
XDebug version:  2.61
Adapter version: 1.12.6

Your launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "log": true,
            "port": 9000,
            "stopOnEntry": true,
            "pathMappings": {
                "/home/u15160p14642/domains/[domainName]/public_html": "${workspaceFolder}"               
              }
            },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}  
XDebug php.ini config:
[xdebug]
zend_extension="c:/wamp64/bin/php/php7.0.32/zend_ext/php_xdebug-2.6.1-7.0-vc14-x86_64.dll"
xdebug.remote_enable =1
xdebug.remote_autostart =1
xdebug.remote_autorestart=1
xdebug.remote_log = /domains/[domainName]/public_html/xdebug_log.log
xdebug.idekey = "VSCODE"
xdebug.remote_connect_back=1
xdebug.extended_info = 1
xdebug.remote_port = 9000
xdebug.remote_host = 127.0.0.1

XDebug logfile (from setting `xdebug.remote_log` in php.ini): 
 - empty (non-existant)
Adapter logfile (from setting `"log": true` in launch.json):
-  empty (non-existant)

Dear reader,

I think I am missing a few points here (as a relative beginner). 
So, I am trying to enable remote debugging on a remote (shared) host. A typical shared hosting with many domains, of which one I would like to remote debug. So, via DirectAdmin I activated the Xdebug extensions on php 7.0.33 and it comes with Xdebug 2.6.0. 
Then, in the public_html folder I placed a simple index.php file, which I also placed on my local computer under c:/wamp64/www. 
Normal debugging works fine as always (many thanks btw!), when I visit localhost:8080 (my apache port). 
I also installed the Debug Helper Chrome extension. I even made a local SSH connection with port forwarding to port 9000 (as came up on Googling the issue), but to no avail.
But, I think I am missing some important things here, as nothing happens at all, when I visit http://[domainName]. Ideally, I would want the debugger on my local computer to light up as it normally does, but nothing (no breakpoint, logging) happens. 
Shouldn't I do more on the server side? Which might be hard btw, as it is shared hosting and you cannot control much. For example, although the Xdebug extension is enabled server side, it is not being active. Configurations like xdebug.remote_enable are all set to "off". Should I copy the local php.ini xdebug settings to server side phi.ini settings?
Am I missing other points too?

I am happy to hear from you.

**Comment by bilogic** [comment]
I faced the same issue and based on all the tests, I concluded the issue was at my shared hosting and after months, they were still unable to make it work.

Essentially, shared hosting xdebug logs says it was unable to connect to my debugger. However, ```telnet``` from my shared hosting to debugger port worked. ```telnet``` to my debugger from as many locations as I could test also worked without any issues.

Fixing this will greatly depend on how competent your shared hosting folks are. In the end, I found workarounds so that all debugging takes place on my development/staging servers.
