### ISSUE TITLE
Xdeb8g throws an error by using the jquery method $().load()

### ISSUE THREAD

**Issue by Thomas1664** [xdebug/vscode-php-debug#337]
PHP version:  7.3.2
XDebug version:  2.7
Adapter version: Where can I find this Information?

Your launch.json:  

XDebug php.ini config:
"version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost/login.php",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9001
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9001
        }
    ]

XDebug logfile (from setting `xdebug.remote_log` in php.ini): 

[Sat Mar 09 23:56:58.899576 2019] [php7:notice] [pid 20068:tid 1996] [client 127.0.0.1:57481] Xdebug could not open the remote debug file 'C\\xampp\\php\\tmp\\log.txt'.
[Sat Mar 09 23:56:58.999787 2019] [php7:notice] [pid 20068:tid 1968] [client 127.0.0.1:57487] Xdebug could not open the remote debug file 'C\\xampp\\php\\tmp\\log.txt'., referer: http://localhost/Desktop/
[Sat Mar 09 23:56:59.338089 2019] [php7:notice] [pid 20068:tid 1968] [client 127.0.0.1:57487] Xdebug could not open the remote debug file 'C\\xampp\\php\\tmp\\log.txt'., referer: http://localhost/Desktop/
[Sat Mar 09 23:56:59.338089 2019] [php7:notice] [pid 20068:tid 1996] [client 127.0.0.1:57481] Xdebug could not open the remote debug file 'C\\xampp\\php\\tmp\\log.txt'., referer: http://localhost/Desktop/
[Sat Mar 09 23:56:59.338089 2019] [php7:notice] [pid 20068:tid 1976] [client 127.0.0.1:57485] Xdebug could not open the remote debug file 'C\\xampp\\php\\tmp\\log.txt'., referer: http://localhost/Desktop/

Adapter logfile (from setting `"log": true` in launch.json):

new connection 1
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 1 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'class.educator.php',
        path:
         'C:\\xampp\\htdocs\\services\\activity\\classes\\class.educator.php' },
     lines: [ 16, 22 ],
     breakpoints: [ { line: 16 }, { line: 22 } ],
     sourceModified: false },
  type: 'request',
  seq: 3 }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'xdebugConnection.js',
        path:
         'C:\\Users\\thhei\\.vscode\\extensions\\felixfbecker.php-debug-1.13.0\\out\\xdebugConnection.js' },
     lines: [ 55 ],
     breakpoints: [ { line: 55 } ],
     sourceModified: false },
  type: 'request',
  seq: 4 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'setBreakpoints',
  success: true,
  body:
   { breakpoints:
      [ { verified: true, line: 16 }, { verified: true, line: 22 } ] } }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 4,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 55 } ] } }

-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 5 }

<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 5,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }

-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [ '*' ] },
  type: 'request',
  seq: 6 }

<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 6,
  command: 'setExceptionBreakpoints',
  success: true }

-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 7 }

<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 7,
  command: 'configurationDone',
  success: true }

<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'exited', threadId: 1 } }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 8 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 8,
  command: 'threads',
  success: true,
  body: { threads: [] } }

new connection 2
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 2 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 9 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 9,
  command: 'threads',
  success: true,
  body:
   { threads: [ Thread { id: 2, name: 'Request 2 (23:54:00)' } ] } }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'class.educator.php',
        path:
         'C:\\xampp\\htdocs\\services\\activity\\classes\\class.educator.php' },
     lines: [ 16, 22 ],
     breakpoints: [ { line: 16 }, { line: 22 } ],
     sourceModified: false },
  type: 'request',
  seq: 10 }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'xdebugConnection.js',
        path:
         'C:\\Users\\thhei\\.vscode\\extensions\\felixfbecker.php-debug-1.13.0\\out\\xdebugConnection.js' },
     lines: [ 55 ],
     breakpoints: [ { line: 55 } ],
     sourceModified: false },
  type: 'request',
  seq: 11 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'setBreakpoints',
  success: true,
  body:
   { breakpoints:
      [ { verified: true, line: 16 }, { verified: true, line: 22 } ] } }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 11,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 55 } ] } }

-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 12 }

<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 12,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }

-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [ '*' ] },
  type: 'request',
  seq: 13 }

<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 13,
  command: 'setExceptionBreakpoints',
  success: true }

-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 14 }

<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 14,
  command: 'configurationDone',
  success: true }

<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'exited', threadId: 2 } }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 15 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 15,
  command: 'threads',
  success: true,
  body: { threads: [] } }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 16 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 16,
  command: 'threads',
  success: true,
  body: { threads: [] } }

new connection 3
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 3 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

new connection 4
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 4 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

new connection 5
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 5 } }

<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'class.educator.php',
        path:
         'C:\\xampp\\htdocs\\services\\activity\\classes\\class.educator.php' },
     lines: [ 16, 22 ],
     breakpoints: [ { line: 16 }, { line: 22 } ],
     sourceModified: false },
  type: 'request',
  seq: 17 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 17,
  command: 'setBreakpoints',
  success: true,
  body:
   { breakpoints:
      [ { verified: true, line: 16 }, { verified: true, line: 22 } ] } }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'xdebugConnection.js',
        path:
         'C:\\Users\\thhei\\.vscode\\extensions\\felixfbecker.php-debug-1.13.0\\out\\xdebugConnection.js' },
     lines: [ 55 ],
     breakpoints: [ { line: 55 } ],
     sourceModified: false },
  type: 'request',
  seq: 18 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 18,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 55 } ] } }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'class.educator.php',
        path:
         'C:\\xampp\\htdocs\\services\\activity\\classes\\class.educator.php' },
     lines: [ 16, 22 ],
     breakpoints: [ { line: 16 }, { line: 22 } ],
     sourceModified: false },
  type: 'request',
  seq: 19 }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'xdebugConnection.js',
        path:
         'C:\\Users\\thhei\\.vscode\\extensions\\felixfbecker.php-debug-1.13.0\\out\\xdebugConnection.js' },
     lines: [ 55 ],
     breakpoints: [ { line: 55 } ],
     sourceModified: false },
  type: 'request',
  seq: 20 }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'class.educator.php',
        path:
         'C:\\xampp\\htdocs\\services\\activity\\classes\\class.educator.php' },
     lines: [ 16, 22 ],
     breakpoints: [ { line: 16 }, { line: 22 } ],
     sourceModified: false },
  type: 'request',
  seq: 21 }

-> setBreakpointsRequest
{ command: 'setBreakpoints',
  arguments:
   { source:
      { name: 'xdebugConnection.js',
        path:
         'C:\\Users\\thhei\\.vscode\\extensions\\felixfbecker.php-debug-1.13.0\\out\\xdebugConnection.js' },
     lines: [ 55 ],
     breakpoints: [ { line: 55 } ],
     sourceModified: false },
  type: 'request',
  seq: 22 }

-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 23 }

<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 23,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }

-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [ '*' ] },
  type: 'request',
  seq: 24 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 19,
  command: 'setBreakpoints',
  success: true,
  body:
   { breakpoints:
      [ { verified: true, line: 16 }, { verified: true, line: 22 } ] } }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 21,
  command: 'setBreakpoints',
  success: true,
  body:
   { breakpoints:
      [ { verified: true, line: 16 }, { verified: true, line: 22 } ] } }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 22,
  command: 'setBreakpoints',
  success: false,
  body:
   { breakpoints: [],
     error: { id: 205, format: 'no such breakpoint', showUser: true } },
  message: 'no such breakpoint' }

-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 25 }

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 20,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 55 } ] } }

-> setFunctionBreakpointsRequest
{ command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 26 }

<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 26,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] } }

-> setExceptionBreakpointsRequest
{ command: 'setExceptionBreakpoints',
  arguments: { filters: [ '*' ] },
  type: 'request',
  seq: 27 }

<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 27,
  command: 'setExceptionBreakpoints',
  success: true }

-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 28 }

<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 28,
  command: 'configurationDone',
  success: true }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 29 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 29,
  command: 'threads',
  success: true,
  body:
   { threads:
      [ Thread { id: 3, name: 'Request 3 (23:54:00)' },
        Thread { id: 4, name: 'Request 4 (23:54:00)' },
        Thread { id: 5, name: 'Request 5 (23:54:00)' } ] } }

-> threadsRequest
{ command: 'threads', type: 'request', seq: 30 }

<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 30,
  command: 'threads',
  success: true,
  body:
   { threads:
      [ Thread { id: 3, name: 'Request 3 (23:54:00)' },
        Thread { id: 4, name: 'Request 4 (23:54:00)' },
        Thread { id: 5, name: 'Request 5 (23:54:00)' } ] } }

Code snippet to reproduce:
The Code causing all the Trouble is Javascript:
$(".content-wrapper").load("index_api.php?environment=educator&cmd=list_educator_tpl", function (response, status, request) {
        console.log("hh");
    });
Using anotherjquery Ajax method such as $.Ajax or $.get it works fine.

**Comment by zobo** [comment]
Very old issue. I think it was connected to parallel PHP sessions that caused `no such breakpoint` error because breakpoints could not be properly synchronized...

This was solved by reimplementing the breakpoint handling code.
