### ISSUE TITLE
Renaming a file causes sudden Breakpoints disappearance

### ISSUE THREAD

**Issue by AnrDaemon** [xdebug/vscode-php-debug#338]
PHP version:  any
XDebug version:  any
Adapter version: 1.13.0

Your launch.json:  

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "stopOnEntry": true,
      "pathMappings": {
        "/home/ccenter": "${workspaceRoot}"
      }
    }
  ]
}
```

I was adding some files to workspace tree, when suddenly noticed that VS Code in the background window scrolled the `Breakpoints` section down, losing 5 or so breakpoints I've had set through the code.
Trying to follow on some of the last moves, I discovered much to my surprise, that renaming any file anywhere in the workspace, even a file unrelated to the project, PHP, xebug, or VS Code whatsoever, which you didn't open with VS Code, not to mention, had no breakpoints in, cause `PHP Debug` to lose all defined breakpoints.

**Comment by zobo** [comment]
I can confirm that when renaming a file that HAS breakpoints, those are lost. I cannot confirm that this happens to all breakpoints. Maybe it was a VS Code bug...
