### ISSUE TITLE
Debugger fails to connect (even locally)

### ISSUE THREAD

**Issue by MIKI0N** [xdebug/vscode-php-debug#339]
**PHP version:** 7.3.2
**XDebug version:** 2.7.0
Adapter version: Not sure what you mean, will be happy to provide it, once I know how to.

**Your launch.json:** 
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

**XDebug php.ini config:**
[XDebug]
zend_extension = C:\xampp\php\ext\php_xdebug-2.7.0-7.3-vc15-x86_64.dll
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_log= "C:\xampp\tmp\xdebug.txt"

**XDebug logfile (from setting `xdebug.remote_log` in php.ini):**
[18152] Log opened at 2019-03-15 01:39:33
[18152] I: Connecting to configured address/port: localhost:9000.
[18152] E: Time-out connecting to client (Waited: 200 ms). :-(
[18152] Log closed at 2019-03-15 01:39:33
[18152]
[18128] Log opened at 2019-03-15 01:45:48
[18128] I: Connecting to configured address/port: localhost:9000.
[18128] E: Time-out connecting to client (Waited: 200 ms). :-(
[18128] Log closed at 2019-03-15 01:45:49
[18128]

Adapter logfile (from setting `"log": true` in launch.json):
`"log": true` is set, but I don't know how to see this log. Again, will be happy to provide it, once I know how to.

**Code snippet to reproduce:**
Nothing in particular, debugger simply doesn't connect.

----------------------------------------------------------
I've been struggling with this problem for 4 days now. Whenever I try to start debugging, VSCode starts loading, then stops. And when I try to connect again, it would just say: "There's already a debug configuration 'Listen for XDebug' running". I need to close VSCode entirely and open it again, in order to be able to try again.

Every time this happens, new lines containing the exact same error get printed on the XDebug logfile.

**This is what I've tried so far:**
- Changing the port on which both listen
- Reinstalling the extension
- Reinstalling VSCode
- Reinstalling XAMPP
- Disabling my Firewall
- Check the ports to see if 9000 is in use (doesn't look like it)
- Re-check if php.exe is set in PATH variable

For what I've found on the web, experiences, where this debugger fails to start, has happened before to other people. But, curiously, gets solved "without doing anything special to solve it".
[https://github.com/gwomacks/php-debug/issues/259](url)

Also, my father (who also uses this extension to debug PHP) told me that he experienced the same experience once; "I couldn't use the debugger for 3 days, it got solved the next day".

On my case, well, seems like it's being more painful.

**I'm completely open to provide any additional information that could be required**, as I'm completely out of ideas at this point. The only 2 possible solutions that I can see, is, waiting to "suddenly" get solved (and on the meantime use the old way of prints and var_dump methods to debug), or reinstall the whole operative system (I don't think I would like to take it that far).

Thanks a lot in advance.

**Comment by bilogic** [comment]
Hi,

In IT, few things suddenly get solved :)

For adapter version, we are talking about this (pic1):
![image](https://user-images.githubusercontent.com/946010/56464559-fbee3680-641e-11e9-95ee-ce3604e43333.png)

I'm not sure if your vscode-php-debug adapter has started properly but it should go like this (pic2):
![image](https://user-images.githubusercontent.com/946010/56464588-a7978680-641f-11e9-840a-10c49dd7b10f.png) 

and you must see this (pic3):
![image](https://user-images.githubusercontent.com/946010/56464593-b9792980-641f-11e9-8977-23ea3c1d832f.png)

For such issues, I normally break them down to TCP connections.
1. I would test your VSCode port 9000 first using ```telnet <vscode's ip address> 9000```
2. If .1 worked, then there is something in between your vscode and the server's xdebug, e.g. firewall etc
3. If .1 failed, then ignore the server and focus just on vscode, I can help more if I knew which of the above pic is not happening for you.

**Comment by MIKI0N** [comment]
Thanks for your help.
For better understanding, here's my situation with images:

**I start the debugger (normally I just press F5 or start it from the Debug tab at the top, however, I did it your way this time, even though it does the same)**
![phpDebugError3](https://user-images.githubusercontent.com/38364924/56465454-0d095a00-63c3-11e9-8c67-8c0852c31b83.png)

**VSCode starts loading and the debugger controller appears as with your third image, however after some seconds they disappear, without any response from the debugger**
![phpDebugError](https://user-images.githubusercontent.com/38364924/56465544-d46a8000-63c4-11e9-895f-c901563819af.png)

**When I try to start the debugger again the following error message appears**
![phpDebugError2](https://user-images.githubusercontent.com/38364924/56465562-2b705500-63c5-11e9-8aa1-c9898a199b1e.png)

**Every time this happens, the same error lines get printed on the XDebug logfile**
![xDebuglog](https://user-images.githubusercontent.com/38364924/56465670-adfa1400-63c7-11e9-801b-0a3d9e59a8f5.png)

**The adapter version is the same as yours: 1.13.0**
![phpExtension](https://user-images.githubusercontent.com/38364924/56465689-bbfc6480-63c8-11e9-9533-6daf7df8438d.png)

I'm running XAMPP, VSCode and XDebug all on the same PC, so `<vscode's ip address>` it's using localhost (`127.0.0.1`)  as the address.

**Telnet is unable to connect**
![telnetConnection](https://user-images.githubusercontent.com/38364924/56465779-5362b700-63cb-11e9-838e-a885f948d00e.png)

Hope this resolves most doubts.

Also, I agree that things don't 'suddenly' get solved. But on cases where the solution where independent from user interaction, for the user would seem as if it got 'suddenly solved'. That's where I was going, I think xD.

**Comment by bilogic** [comment]
I'm guilty of wishing for miracles too, but it is a slippery path. I like to remind myself whenever I catch it. :)

1. Based on your ```telnet``` results, the issue is at the vscode end, I would start looking deeper there.
2. I will skip looking at the ```XDebug logfile```, this is generated by the server trying to talk to ```vscode-php-debug```, no point looking here now.
3. Set ```vscode-php-debug```'s ```"log": true``` in your vscode's settings/```launch.json``` and open ```DEBUG CONSOLE``` tab in your vscode terminal. Clues to your issue should pop up here.
3. Is ```telnet``` able to connect before the debugging controller disappears?

**Comment by MIKI0N** [comment]
Sorry for the delay.

- `"log": true` was already set, but nothing gets printed on the `DEBUG CONSOLE`.
- Very few seconds happen before the debugging controller disappear, I can't catch it up with Telnet.
-  I found out that if I call some action from the `DEBUG CONSOLE` like `echo hi`, VSCode starts loading again (and this time indefinitely). However, Telnet is still unable to connect.

![xDebugNoResponse](https://user-images.githubusercontent.com/38364924/56589327-9b8c0000-65aa-11e9-8846-254c4c245b3b.png)

Is there any other way I could see what's going on? Maybe even the whole VSCode log?

All was working just fine, some time ago.

**Comment by MIKI0N** [comment]
Worth mentioning as well, that this only happens when trying to debug PHP.

I've been working with React as well, no problem in there.

I'm not really sure if VSCode's really guilty. But I agree it might be a probability still.

**Comment by bilogic** [comment]
What I know about React is it's a javascript for frontend, i.e. it doesn't run on a server.

From your issue descriptions, e.g. ```no debug adapter```, it sounds like a problem in how ```vscode-php-debug``` was installed. I will try getting a new vscode instance and installing just ```vscode-php-debug```

**Comment by zobo** [comment]
Very old issue, very broad. Please open a new issue if you have not been able to solve this.
