### ISSUE TITLE
Variables declared by reference aren't showing their values in tooltips when hovering the declaration

### ISSUE THREAD

**Issue by AnrDaemon** [xdebug/vscode-php-debug#341]
PHP version: 5.6
XDebug version: 2.6.1
Adapter version: 1.13.0

Your launch.json: -
XDebug php.ini config: -

XDebug logfile (from setting `xdebug.remote_log` in php.ini): -
Adapter logfile (from setting `"log": true` in launch.json): -

Code snippet to reproduce:

```php
<?php
function a(&$b)
{
  $b++;
  print "$b\n";
}

a(1);
```

Hovering over `&$b` does not produce the same inspection tooltip as it works for `$b` anywhere else in the code.

**Comment by zobo** [comment]
Does not currently happen, as there was some improvements to the hover logic provided by `registerEvaluatableExpressionProvider` in VS Code extension...
