### ISSUE TITLE
Debug not starting when running in another VS instance

### ISSUE THREAD

**Issue by webkod3r** [xdebug/vscode-php-debug#345]
Issue Type: <b>Bug</b>

When you try to start an Xdebug session and you have another instance of Visual Studio code running you will expirience an error reading no php configuration available, even thoug there is a launch.json configured.
If the other session gets closed then you can work with out no problem at all. 

Note: I have 2 containers with two different ports each one. That way there is no port overlap between each other.

Extension version: 1.13.0
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by walkero-gr** [comment]
I have exactly the same problem in my setup, as well. This didn't happen before for sure. No overlapping ports here too.

The debug console gives me the following
`{ Error: listen EADDRINUSE :::9001
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at Promise (/Users/george.sokianos/.vscode/extensions/felixfbecker.php-debug-1.13.0/out/phpDebug.js:236:24)
    at new Promise (<anonymous>)
    at createServer (/Users/george.sokianos/.vscode/extensions/felixfbecker.php-debug-1.13.0/out/phpDebug.js:184:40)
    at PhpDebugSession.<anonymous> (/Users/george.sokianos/.vscode/extensions/felixfbecker.php-debug-1.13.0/out/phpDebug.js:240:27)
    at Generator.next (<anonymous>)
    at /Users/george.sokianos/.vscode/extensions/felixfbecker.php-debug-1.13.0/out/phpDebug.js:7:71
    at new Promise (<anonymous>)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 9001 }`

**Comment by zobo** [comment]
This is expected. When the vscode php debugger starts to listen it actually listens on a TCP socket (port 9001). There are manual ways around it by setting a different launch.json entry with a different port and also configuring php to connect to a different port.
There's also a feature in the works where in case of starting a php process we'll be able to allocate a free, random port and use that for the individual debug session.

Closing.
