### ISSUE TITLE
Extension not exporting activate function

### ISSUE THREAD

**Issue by tsmaeder** [xdebug/vscode-php-debug#346]
The [VSCode Documentation](https://code.visualstudio.com/api/references/activation-events#Start-up) requires an extension to export an activate function. However, vscode-php-debug does not seem to export one. While VS Code happily load the extension currently, this might change at any time.

**Comment by zobo** [comment]
This was a DAP-only extension and so did not need an `activate()` export. It was changed and expanded a lot since then...
