### ISSUE TITLE
Feature Request: show memory usage at breakpoint

### ISSUE THREAD

**Issue by derekyle** [xdebug/vscode-php-debug#351]
It would be great if this extension could simply show current memory usage of php at the breakpoint. Currently, I have to put something like 
`$memory_usage = memory_get_usage(); `
right before the breakpoint and that will show the usage as a variable in the variables tab. This works just fine but it would be very nice not to have to constantly add and remove the code snippet. If there was just an option to always insert the code right before the breakpoint silently and then remove it, I think that is all most people would need.
Even just showing an estimated size of the current variables would be helpful.

**Comment by zobo** [comment]
I think this is out of scope of this extension. You could probably add this function call to the Watch pane.
![image](https://user-images.githubusercontent.com/2456026/169524863-43740bc1-a3a3-4f0a-9451-ffbc2b277137.png)
