### ISSUE TITLE
Stepping through code in the debugger causes additional code to execute

### ISSUE THREAD

**Issue by bkline** [xdebug/vscode-php-debug#355]
Stepping through the constructor shown in the code snippet below using VS Code causes changes to the object being constructed which do not occur

1. when the code is run without the debugger; or
2. when we run in the debugger under VS Code, stopping at a breakpoint on the second of the three assignment statements in the constructor, and then pressing the `Continue (F5)` control to resume execution; or
3. when we run in the debugger under PhpStorm, stepping through each of the statements in the constructor

When debugging under VS Code with the debugger stopped at a breakpoint on the second assignment in the constructor (`$this->parent = $parent;`), the `list` member of `$this` is an empty array. Immediately after stepping through that assignment statement, `$this->list` is now an array with one element. There are no magic getters or setters at play (those would only kick in for assignments invoked by code which did not have access to the object's members, which obviously can't be the case for the object's own constructor, and they would also fire outside of the debugger, or when debugging in another IDE).

PHP version:  _7.2.10-0ubuntu0.18.04.1_
XDebug version:  _v2.6.0_
Adapter version: _1.13.0_
VS Code version: _1.33.1_

Your launch.json:  _inside attached archive_

[vscode-php-debug-logs.zip](https://github.com/felixfbecker/vscode-php-debug/files/3143485/vscode-php-debug-logs.zip)

XDebug php.ini config: _inside attached archive_

XDebug logfile (from setting `xdebug.remote_log` in php.ini): [xdebug.log](https://github.com/felixfbecker/vscode-php-debug/files/3144589/xdebug.log)

Adapter logfile (from setting `"log": true` in launch.json): _inside attached archive_

Code snippet to reproduce:

```php
  public function __construct(DataDefinitionInterface $definition, $name = NULL, TypedDataInterface $parent = NULL) {
    $this->definition = $definition;
    $this->parent = $parent;
    $this->name = $name;
  }
```

I realize that this is not going to be sufficient for reproducing the behavior. We have no idea how to boil the system down to a repro case. I'm not fond of creating bug reports for which I can't also provide a patch, or at the very least a useful repro case, but we're not in a position to share the code and environment of the customer.

**Comment by bkline** [comment]
Here's what `$this` looks like just before we step over line 65 in VS Code.

![Screen Shot 2019-05-03 at 12 20 44 PM](https://user-images.githubusercontent.com/1634628/57165795-226c8400-6dc6-11e9-9ba5-abf6458b56eb.png)

Same thing in PhpStorm.

![Screen Shot 2019-05-03 at 12 23 06 PM](https://user-images.githubusercontent.com/1634628/57165891-69f31000-6dc6-11e9-8e1c-dbac5ccd654a.png)

After stepping over (`Step In` does the same thing) in VS Code, note that _both_ `$this->parent` _and_ `$this->list` have changed:

![Screen Shot 2019-05-03 at 12 21 14 PM](https://user-images.githubusercontent.com/1634628/57165927-898a3880-6dc6-11e9-8c18-5c533aa0363f.png)

But in PhpStorm (note that `$this->parent` has changed, as expected, whereas `$this->list` is unchanged from an empty array, also as expected):

![Screen Shot 2019-05-03 at 12 24 41 PM](https://user-images.githubusercontent.com/1634628/57165938-973fbe00-6dc6-11e9-870e-c3c91f14fb62.png)

**Comment by bkline** [comment]
To further illustrate what's happening with and without debugging under VS Code, I created a hacked version of the Drupal code.

```php
  public function __construct(DataDefinitionInterface $definition, $name = NULL, TypedDataInterface $parent = NULL) {
    $this->definition = $definition;
    if ($name === 'moderation_state') {
      \drupal_set_message('BEFORE: ' . print_r($this->list, TRUE));
    }
    $this->parent = $parent;
    if ($name === 'moderation_state') {
      if (!empty($this->list)) {
        $value = 'VALUE IS ' . $this->list[0]->values['value'];
      }
      else {
        $value = '$this->list IS EMPTY!';
      }
      \drupal_set_message("AFTER: $value");
    }
    $this->name = $name;
  }
```

Running with that version of the code without any debugger, this is what the messages at the top of the page look like:

![Screen Shot 2019-05-03 at 3 10 29 PM](https://user-images.githubusercontent.com/1634628/57166234-893e6d00-6dc7-11e9-9961-6ebb09d3f649.png)

The messages look the same if we step through the constructor in PhpStorm, or we we press `Continue (F5)` after hitting the breakpoint on the `$this->parent = $parent;` line under VS Code.

But if we step over that line with VS Code and _then_ press `Continue (F5)` the messages look like this:

![Screen Shot 2019-05-03 at 3 15 03 PM](https://user-images.githubusercontent.com/1634628/57166346-e3d7c900-6dc7-11e9-90da-e5bb9156b86a.png)

So clearly VS Code has caused some additional code to execute which shouldn't have. And no, I don't know where that code is. As I mentioned earlier, attempting to step into the assignment doesn't succeed.

**Comment by zobo** [comment]
It could be that one of the set Watches caused the side effect. They are indeed (at the moment) evals, and not property-get operations...
I don't know Drupal enough to guess if perhaps `$this->query...` had some magic behind it...
