### ISSUE TITLE
only postman request works

### ISSUE THREAD

**Issue by webdeveloper0429** [xdebug/vscode-php-debug#364]
PHP version:  7.2.19
XDebug version:  2.7.2
Adapter version:

Your launch.json:  
```
{
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/var/www/html": "${workspaceRoot}/sources/designer"
            }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
```
XDebug php.ini config:
 -   xdebug.remote_autostart: on
 -   xdebug.remote_connect_back: on
*************************************************************************************************
I am debugging remote in docker.
xdebug works when I make request with postman. but it doesn't work when I request with browser.

Anybody has idea?

**Comment by CarryOnHxy** [comment]
@felixfbecker  me too

**Comment by zobo** [comment]
Please try with latest extension and Xdebug, add xdebug_info() to start of the code to see some information what is happening.
