### ISSUE TITLE
Elements of array

### ISSUE THREAD

**Issue by mgk98** [xdebug/vscode-php-debug#369]
Issue Type: <b>Bug</b>

arrays in the debug variables are limited at 32 elements

Extension version: 1.13.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (4.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Sigtechnica** [comment]
yes, thank you, drove me nuts, but I have the feeling the maintenance on the project is low :(

**Comment by Sigtechnica** [comment]
I think I fixed my issue, inside the launch.json.

you need to add a section xdebugSettings:
```
            "xdebugSettings": {
                "max_children": 512,
                "max_data": 1024,
                "max_depth": 4,
            }
```

to increase the limits, I have double the first 2 and increased the depth from 3 to 4.
I peaked into the phpinfo to get the defaults :)

**Comment by zobo** [comment]
Related #805
