### ISSUE TITLE
Anybody continuing the development of this extension?

### ISSUE THREAD

**Issue by AnrDaemon** [xdebug/vscode-php-debug#371]
Last commit to the repo is from March, and there's just too many bugs that block daily work.

**Comment by augustocdias** [comment]
Doesn't look like... There's 25 open pull requests and no comment on most of them

**Comment by zobo** [comment]
It's a shame, since this is a top match extension for when people search vscode and php debugging. Wonder if @felixfbecker would take a maintainer to at least comb over open PRs...

**Comment by austenc** [comment]
What are people using instead? I keep running into xdebug connection issues. It works, then it doesn't.. 🤔

**Comment by AnrDaemon** [comment]
It works reliable only if you keep only one session running. :/

**Comment by zobo** [comment]
Hm.. I did not have such cases yet...  How is it unstable, how to reproduce it?

**Comment by AnrDaemon** [comment]
If you have 2 or more xDebug connections simultaneously opened in the same VS Code window, it's impossible to switch between them.

**Comment by cjwijtmans** [comment]
start an active fork then?

**Comment by AnrDaemon** [comment]
Not in a position to do so. Else I would.

It got better with VS Code 1.41+ though (SUDDENLY!). But changing between debugging sessions is still problematic.

**Comment by cjwijtmans** [comment]
The only annoyance i had so far is that i get breaks when an exception is being display with no traces then i get another break on the same exception with a trace(if the exception is not caught). So i get two breaks on the same exception unless the exception is caught then i get one break with no stack trace. So why not just get rid of the first break without a stack trace. Not sure what is causing this behavior though.

**Comment by AnrDaemon** [comment]
`xdebug.remote_mode = jit` ?
That's how xdebug itself works. Extension is only listening, it can't know ahead of time, what xdebug will send to it.

**Comment by cjwijtmans** [comment]
> `xdebug.remote_mode = jit` ?
> That's how xdebug itself works. Extension is only listening, it can't know ahead of time, what xdebug will send to it.

Not what i am saying.  It appears that exception that are caught(later) are breaking with no stack trace. While exceptions that are not caught(later) are breaking once without stack trace and then again with a stack trace... So add an option to only break when there is a stack trace present.

**Comment by AnrDaemon** [comment]
Why not disable breaking on caught exceptions?

Sadly it can't be set in `"xdebugSettings": {…}`.

**Comment by Vaggal** [comment]
Why is this issue still open? The development is continuing and the latest comments are related to a different issue.

**Comment by zobo** [comment]
I agree, reports here went into a different direction. Please open a new specific issue if you still have it.
Closing this as solved, since I'm continuing development :)
