### ISSUE TITLE
Double layered array does show on mouse over. but does not show in Watch

### ISSUE THREAD

**Issue by Nander-MultiSafepay** [xdebug/vscode-php-debug#373]
![image](https://user-images.githubusercontent.com/53612979/64686208-927fca80-d488-11e9-8295-2968df16c9ac.png)

PHP version:  
XDebug version:  Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
Adapter version: 1.13.0

Your launch.json:  
 "name": "Listen for XDebug on Homestead",
            "type": "php",
            "request": "launch",
            "pathMappings": {
                "/home/vagrant/code/": "c:/MSP_PROJECTS/VIS"
            },
            "port": 9000
XDebug php.ini config:
zend_extension=xdebug.so
xdebug.remote_enable = 1
xdebug.remote_connect_back = 1
xdebug.remote_port = 9000
xdebug.max_nesting_level = 1024
xdebug.remote_autostart=1
xdebug.remote_host=192.168.10.10
xdebug.remote_log=/tmp/xdebug.log

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Normal no Errors
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:
Double layered array, doesnt show in watch
```php

```

**Comment by AnrDaemon** [comment]
Add to the launcher configuration:
```
          "xdebugSettings": {
            "max_children": 4096,
            "max_data": 512,
            "show_hidden": 1,
            "multiple_sessions": 1,
            "max_depth": 7,
            "extended_properties": 1
          },
```
(and modify for your preference)
Also, see the extension log for any settings debugger sets that may not be to your liking.
Watch for `feature_set` commands.

**Comment by zobo** [comment]
Age old problem, because Watch uses `eval`. Tracking possible changes here #808.

**Comment by anchan42** [comment]
The setting works but it make the step through the code slow down to a crawl.

**Comment by zobo** [comment]
@anchan42 Could be. Can you open a new issue with some screenshots a some logs, so I can see what kind of watch material you are working with?
