### ISSUE TITLE
No break the line in VScode when running php script on docker

### ISSUE THREAD

**Issue by kenziehong** [xdebug/vscode-php-debug#376]
PHP version:  7.2.15
XDebug version:  2.7.2
Adapter version: 1.13 PHP Debug
use: php-fpm

Your launch.json:  
 {
      "name": "Listen for XDebug on Docker",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "pathMappings": {
        "/var/www/fado_front-end/cli/": "${workspaceRoot}",
      },
      "log": true
    },
XDebug php.ini config:
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM

xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.cli_color=1
xdebug.profiler_enable=0
xdebug.profiler_output_dir="~/xdebug/phpstorm/tmp/profiling"

xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
![image](https://user-images.githubusercontent.com/32231963/67055627-18bbba80-f173-11e9-9a36-dba494b9335f.png)

Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php

```
![image](https://user-images.githubusercontent.com/32231963/67028777-24d55700-f136-11e9-90b4-47a5fefb3f68.png)

**Comment by lucasbp** [comment]
This worked for me, change these settings in your **php.ini**:
```
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_connect_back = 0
xdebug.remote_host = "172.17.0.1"
xdebug.remote_port = 9000
```

On Windows or Mac you can use:
```
xdebug.remote_host = "host.docker.internal"
```
Instead of:
```
xdebug.remote_host = "172.17.0.1"
```

The IP address **172.17.0.1** is the default docker host if you are using the default network. If you are using a different network in your container, you will need to find the IP of your host docker.

Sorry for the English writing!

**Comment by zobo** [comment]
Could be a path mapping issue. It's not obvious from the screenshots how your code "sees" the path of cli.php. Also not sure if you are running on windows or linux (mingw64 would suggest windows). The xdebug.log is also a bit funny. After the engine sends "<init ..." the client (code) is expected to send something back, but I do not see it here.

Anyway you probably need to edit your launch.json (debugger, config gear) and add to you "Listen for XDebug" something like this:
`"pathMappings": {
                "/var/www": "c:/my_code/var/www"
}`

Best,
Damjan

**Comment by pmourer** [comment]
I hadn't realized that `host.docker.internal` wasn't available on linux machines, thanks so much for pointing that out

**Comment by zobo** [comment]
Best guess, the launch.json needs to change to this as it seems `cli` folder is already part of the workspace.

```
"/var/www/fado_front-end/": "${workspaceRoot}",
```
