### ISSUE TITLE
not working with remote-ssh extension

### ISSUE THREAD

**Issue by proidit** [xdebug/vscode-php-debug#377]
Not working with remote-ssh extension.
my php/xdebug debugging ambient from same client/server work perfectly without using remote-ssh extension.
i have try with putty ssh tunnel source port 9000 / destination 127.0.0.1:9000 LOCAL/AUTO

PHP version:  7.3
XDebug version: v2.7.0RC2,  
Adapter version:

Your launch.json:  
		{
			"name": "Listen for XDebug",
			"type": "php",
			"request": "launch",
			"port": 9000,
			"log":true
		},

XDebug php.ini config:
zend_extension=xdebug.so
xdebug.profiler_enable_trigger = 1
xdebug.remote_autostart = 1
xdebug.remote_enable = 1
xdebug.remote_handler = dbgp
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_mode=req
xdebug.profiler_output_dir = "/tmp"
xdebug.remote_log="/tmp/xdebug_remote.log

![image](https://user-images.githubusercontent.com/4655081/68414004-a8132700-018f-11ea-870c-47a133fb8ac5.png)

**Comment by zobo** [comment]
The issue will probaby be the connect remote_connect_back setting. See if you use vscode remote the plugin is actually running on your server, not the workstation. However when you open you web page php will try to connect to your workstation (port 9000) because of the remote_connect_back setting. What you can do is set  xdebug.remote_host=127.0.01 and xdebug.remote_connect_back=0 .  Other option would be a dbgp proxy, but until this PR is merged https://github.com/felixfbecker/vscode-php-debug/pull/280 that will not work.

Your tunnel idea is also valid, but I guess you'd need to enable "Local ports accept connections from other hosts".

I bet you could find some more clues in your /tmp/xdebug_remote.log

Best!

**Comment by proidit** [comment]
yes with xdebug.remote_connect_back=0 and xdebug.remote_host=127.0.0.1 works perfectly.
the problem is that web browser without call through tunnel is not see in the xdebug engine from 127.0.0.1 but from a remote host and not respond to the host browser
The remote-ssh extension wait xdebug response from port 9000 of the remote ssh host and not from client ... this permit to vscode/remote-ssh extensions to intercept the local response of xdebug engine.
i have very bad english :)

**Comment by kenny1983** [comment]
I have the exact same issue. I'm running a CentOS 7 VirtualBox VM on a Windows 10 host. I have VS Code and the Remote SSH extension installed on Windows, while Apache, PHP and XDebug are all installed on the VM. XDebug shows as being a properly-loaded Zend module when I run `php -m` on the VM, but I can't for the life of me figure out how to get this extension working!!

I have the extension installed on the VM as well since that was the method recommended by Microsoft in their VS Code/Remote SSH docs. Should I have it installed locally instead?

Here is the relevant section of my `php.ini`:
```
[xdebug]
zend_extension="/usr/lib64/php/modules/xdebug.so"

xdebug.remote_enable = true
xdebug.remote_autostart = true
xdebug.remote_host = 127.0.0.1
xdebug.remote_port = 9000
xdebug.remote_log = /tmp/xdebug.log
xdebug.max_nesting_level = 1000
```
And my `launch.json`:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "php",
            "request": "launch",
            "name": "Listen for XDebug",
            "port": 9000,
            "log": true,
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```
I also had the `pathMappings` setting configured for a while but to no avail (which makes sense since all files are on the VM anyway).

This is absolutely maddening! Please help ASAP!

**Comment by zobo** [comment]
Maybe silly question, but did you run the debugger?
![image](https://user-images.githubusercontent.com/2456026/74225630-62e52080-4cbb-11ea-8acd-afd60ada9c40.png)
If yes, you can check the `/tmp/xdebug.log` to see if there is a connection? And the `DEBUG CONSOLE` in Vscode if there is anything?
I don't see an issue with the config...

I guess I should blog a howto article :)

**Comment by kenny1983** [comment]
Thanks for the response @zobo!
> Maybe silly question, but did you run the debugger?
LOL yes of course 😛 
> If yes, you can check the `/tmp/xdebug.log` to see if there is a connection? And the `DEBUG CONSOLE` in Vscode if there is anything?
Oh I forgot to mention that...another infuriating (but probably unrelated to this extension or even VS Code) problem that I'm having is the absence of an XDebug log in the location specified. I changed it to `/tmp` after suspecting a permissions issue, but even that directory (which has 666 permissions, as is normal on *nix systems) doesn't seem to be accessible to XDebug/PHP/Apache (which program/user/group is actually responsible for writing this log?).

As for the debug console in VS Code, it doesn't show much other than the fact that the launch was "successful"...but I still can't stop on breakpoints 😞 Sorry I'd give you more detailed info if I could but I'm not at my work machine right now.

In any case, my boss has instructed me to ditch the remote SSH extension and try debugging from a local project, that I will then have to manually sync with the server (or use some other extension for that). So I will let you know how things go with that setup and your extension 😄

Thanks again!

**Comment by zobo** [comment]
An empty `xdebug.log` would indicate that DBGP is not started at all. I have very good experience with the remote SSH. Maybe its your PHP setup. I'm guessing you are debugging a web project. Try to load a simple `http://whatever/phpinfo.php` to check that xdebug is really loaded and remote and remote_autostart are enabled. Then try to add a `"stopOnEntry": true,` to your `launch.json`. Here is part of mine:
```    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "stopOnEntry": true,
            "xdebugSettings": {
                "max_children": 100,
                "max_data": 100
            },
            "log": true,
```

When you can, dump your DEBUG CONSOLE here and maybe I'll get another idea.
Best!

**Comment by proidit** [comment]
use this  remore-ssh use config file:

Host xxxxxxx
	User root
	HostName xxx.xxx.xxx.xxx
	IdentityFile C:\.....
	LocalForward 127.0.0.1:8080 127.0.0.1:80

define the domain in apache/nginx whith a alias <yourdomain>.tunnel.local 

nginx:
server_name <your domain> www.<your domain>  <your domain>.tunnel.local www.<your domain>.tunnel.local;

in windows add this entry in System32/drivers/etc/hosts:
<server ip>	<domain name>.tunnel.local

start vscode with remore-ssh ... vscode strart the  tunnel througth config file

start debug

open the url http://<you domain>.tunnel.local:8080/
the request running in the server as 127.0.0.1:80 and xdebug intercept correctly the request from server localhost

it works for me

**Comment by kenny1983** [comment]
Thanks for your help guys; especially @zobo who suggested running a basic `phpinfo()` script to ensure that XDebug was being loaded. I was misled by other web sources to believe that `php -m` and `phpinfo()` would give me the exact same indication of success or failure. This was not the case, since `php -m` listed XDebug but `phpinfo()` did not.

This prompted me to search further until I eventually found this in apache's `error_log`:
```
Failed loading /usr/lib64/php/modules/xdebug.so:  /usr/lib64/php/modules/xdebug.so: cannot open shared object file: Permission denied
```
Finally I had a clue as to what was going on: something was preventing Apache from accessing the XDebug module!

After doing a little more digging, I finally worked out that SELinux was the culprit. Setting its mode to 'permissive' finally allowed the module to be properly loaded by Apache and everything else just fell into place automatically :D

**Comment by MeCrazyJunkie** [comment]
I have same problem with dockerized php on remote host with vscode-remote-ssh

docker-compose:

```
version: "3.7"
services:

    webserver:
      build: containers/nginx
      container_name: webserver
      volumes:
          - ${SITE_PATH}:${CONTAINER_SITE_PATH}
          - /etc/localtime:/etc/localtime:ro
      ports:
       - "80:80"
       - "443:443"
      restart: always

    php-fpm:
      build: 
        context: containers/php-fpm
        target: ${TARGET:-base}
      
      container_name: php-fpm
      working_dir: ${CONTAINER_SITE_PATH}
      volumes:
        - ${SITE_PATH}:${CONTAINER_SITE_PATH}
        - /etc/localtime:/etc/localtime:ro
      user: 1000:1000
      restart: always
```

xdebug.ini:

```
[xdebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = 172.17.0.1
xdebug.remote_connect_back = 0
xdebug.remote_log = "/var/log/xdebug"
```

check in running php-fpm container: php -i | grep xdebug.remote
```
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_host => 172.17.0.1 => 172.17.0.1
xdebug.remote_log => /var/log/xdebug => /var/log/xdebug
xdebug.remote_log_level => 7 => 7
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
```      
xdebug.remote_host = 172.17.0.1 I got from docker0 network from host:

```
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:66:9e:b3:73 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:66ff:fe9e:b373/64 scope link
       valid_lft forever preferred_lft forever
```

So I run Listen for Xdebug, open script in browser and nothing is happened. No stop at breakpoint, no symbols in vscode debug console, no file /var/log/xdebug in php-fpm container.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/4202834/80858395-c438e200-8c61-11ea-9fab-92e7e3f53370.png">


What am I doing wrong?

**Comment by zobo** [comment]
Looks about right. I suggest you create a phpinfo.php and open it in browser, to be sure that the xdebug settings are actually present in php-fpm and not just php-cli. It would be worth inspecting /var/log/xdebug in container.

**Comment by MeCrazyJunkie** [comment]
xdebug settings in browser:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/4202834/80883780-c6348c80-8cc5-11ea-9903-5d3386c73f41.png">

cat /var/log/xdebug in container:
`cat: /var/log/xdebug: No such file or directory`

**Comment by zobo** [comment]
Probaby the php process cannot write to /var/log/xdebug. Try changing it to /tmp/xdebug.log

Try to add xdebug_break(); to your code forcing a breakpoint.

It could also be a path mapping issue. What is the path of 1.php inside the container versus path outside container.

**Comment by MeCrazyJunkie** [comment]
Thank you!
I've changed log file path and see log:
```
[7] Log opened at 2020-05-02 20:35:21
[7] I: Connecting to configured address/port: 172.17.0.1:9000.
[7] E: Time-out connecting to client (Waited: 200 ms). :-(
[7] Log closed at 2020-05-02 20:35:22
```
So I had to open port 9000 in iptables on host. Then it's start working.
I expected vscode to do it for me :)

**Comment by tim-rohrer** [comment]
@MeCrazyJunkie, that is a good idea, unfortunately, it didn't work for me.

**Comment by zobo** [comment]
Since this is an older issue I will close it. Please open a new one if you still have issues. Always try with latest extension and Xdebug, and make a test file with `xdebug_info();` that will show lots of diagnostics.
