### ISSUE TITLE
breakpoints are randomly skipped

### ISSUE THREAD

**Issue by rotorboy** [xdebug/vscode-php-debug#383]
PHP version:  7.2
XDebug version:  2.6.1
Adapter version:

Your launch.json:  
"version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
XDebug php.ini config:

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

Breakpoints that are set wont fire properly all the time. This occurs mainly after clearing another breakpoint, followed by clicking "continue". Detaching and reattaching xdebug re-enables a set breakpoint for some number of firings.

**Comment by astecconsulting** [comment]
I am having the same issue. Did you ever resolve this?

**Comment by rotorboy** [comment]
Have not. 

-Avi

**Comment by astecconsulting** [comment]
I have been fighting this problem for a couple of weeks . Its intermittent and recurring but does not follow a predictable pattern .  Uninstalling and reinstalling the xdebug module in VS code plus some other random action seems to fix the issue in the last 24 hours. I will try to log the sequence to see if I can isolate it.

Doug Phillips

**Comment by rotorboy** [comment]
What I find works well is clearing all break points, quit out of the browser being used, quit code, then reopen everything, and re select breakpoints. 

-Avi

**Comment by astecconsulting** [comment]
Lol. I did have some success with a variation of that method but I thought it was a fluke and I was just imagining the correlation . Thank you for confirming I am not yet insane.

Doug Phillips

**Comment by rotorboy** [comment]
You’re welcome.

My guess of what’s happening is that if any code line is added or removed prior to where a breakpoint is set while debug mode is “started”/running, occasionally, the “monitor” will lose track what the new line that the breakpoint is on, and thus why it blows through a given breakpoint. 

The same effect likely can be had by just stopping debug mode, clearing all breakpoint via the “clear all breakpoints” ui item, then re-engaging the desired line breakpoint. I have done that as well, and it works too.

If I exit debug before making line count changes, the problem doesn’t show up.

-Avi

**Comment by zobo** [comment]
Tracking of breakpoints is mostly done in VS Code, and the extension only receives some changes..
Best to not change code while debugger is running...
