### ISSUE TITLE
PHP Debug XDebugger stops on breakpoint and doesn't step.

### ISSUE THREAD

**Issue by stevewh** [xdebug/vscode-php-debug#391]
Issue Type: <b>Bug</b>

Check Errors (Stop on Error)  in break-point pane
Check Exceptions (Stop on Exception)  in break-point pane
Start debug session.
Set break points
Run Browser page and gesture for service call (press button in this case)
Stops at first breakpoint
Press Restart, step or step in with no response (debugger could be looping with long time out)
After minutes, press stop and service fails.

Extension version: 1.13.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by stevewh** [comment]
Found another article suggesting to shut of "Stop on enter", this lead me to try to shut of stop on error and stop on exception, which avoids this issue.

**Comment by zobo** [comment]
Could be an old issue where errors in Watch expressions caused debugger not working. Fixed by Xdebug. Please reopen and provide info with latest extension and Xdebug.
