### ISSUE TITLE
VS code 1.43 prevents new local variables from local variable debugger listing

### ISSUE THREAD

**Issue by rotorboy** [xdebug/vscode-php-debug#394]
PHP version:  7.2
XDebug version:   
Adapter version:

Your launch.json:   
XDebug php.ini config:

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

Just upgraded from 1.42.1 to 1.43 VS code, and now, any variables on lines added to a php function after the upgrade are not displayed in the "variables" debugger pane.  Variables on lines present before the upgrade and which have not been edited are still visible in "variables" pane. However, changing code for a line existing prior to upgrade then prevents said local variable from listing. 

global variables can be added and are visible in the "variables" pane. Only new lexically-scoped variables within functions are not visible.

In the example photo, the stack variable $foo is visible in the 
<img width="603" alt="Screenshot at Mar 11 23-21-15" src="https://user-images.githubusercontent.com/34849704/76484120-4c7fd100-63ef-11ea-9bba-1171d854b2e0.png">
pane, but local heap variable $a is not.

**Comment by zobo** [comment]
PHP 8 / Xdebug 3 looks like this:

![image](https://user-images.githubusercontent.com/2456026/117671366-01a34a00-b1a9-11eb-8d2c-1aa5e5a3fa90.png)

PHP 7.2 is really old and [EOL](https://www.php.net/supported-versions.php)

Reopen if this is still an issue.
