### ISSUE TITLE
PHP process not stop after debug session stop

### ISSUE THREAD

**Issue by fernandomacho** [xdebug/vscode-php-debug#396]
PHP version:  7.4
XDebug version:  2.9.2
Adapter version: 

Your launch.json:  
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "API",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "xdebugSettings": {
                "max_children": 1024,
                "max_data": 18000,
                "max_depth": 5
            }
        },
        {
            "name": "Consumer rabbit",
            "type": "php",
            "request": "launch",
            "program": "/source/repo/src/BB/V1/Consumers/consumer.php",
            "args": ["/v1/updateconsent"],
            "cwd": "/source/repo",
            "port": 9000,
            "xdebugSettings": {
                "max_children": 1024,
                "max_data": 18000,
                "max_depth": 5
            }
        }
    ]
}

Scripting sessions usually work correctly, but sometimes stopping the debug vs code session for the debug session but the php process runs in the background. Which means that the debugging process has not really stopped.

This problem is especially acute when you use processes consuming messages from an asynchronous queue (in my case rabbitmq), since when the process was running in the background, the messages that should have remained in the queue, having stopped the debug session, are consume by the process that stays in the background.

**Comment by zobo** [comment]
When starting a process like in your "Consumer rabbit" example, the adapter should stop the process when it gets disconnected.
This only works when `externalConsole` is not defined of is left on `false`.

If the problem is still there, please reopen the issue and attach logs.
