### ISSUE TITLE
No Bug icon appears in the extension bar on the left

### ISSUE THREAD

**Issue by morfie78** [xdebug/vscode-php-debug#404]
PHP version:  7.2.24
XDebug version:  V2.9.5
Adapter version: 1.13.0

Your launch.json:  
`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "*************",
            "webRoot": "${workspaceFolder}"
        }
    ]
}`
XDebug php.ini config:
`
zend_extension = /usr/lib/php/20170718/xdebug.so
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_port=9000
xdebug.remote_connect_back=1`

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

On Windows 7, latest VSCode, When I install the PHP Debug extension, no "bug" icon in the left bar appears: http://puu.sh/FJzYk/43928404d8.png

**Comment by zobo** [comment]
This is quite old and I think around that time the vscode icon was changed from "bug" to "play+bug". Here is one similar issue: https://github.com/microsoft/vscode/issues/99625

I'll close this issue.
