### ISSUE TITLE
Feature request: Display value when hovering over an object property - attribute

### ISSUE THREAD

**Issue by c0rtex** [xdebug/vscode-php-debug#407]
Hello,

I'm sorry if this was already asked but I couldn't find any similar topics in the Issues list. Would it be possible to display the value of a property when one hovers over it? For example: $obj->PROPERTY.

If I hover over $obj it does show the values, but not when you hover over PROPERTY. I hope this makes sense.

Also, is it possible to have a global launch.json file? I'd like to be able to set some default values for xDebug, so I don't have to type them every single time I work on a new project.

Thank you for your time and your answers!
-Juan

**Comment by gabrielmaldi** [comment]
I'd love to be able to hover over `prop` in `$obj->prop;` and see its value.

**Comment by zobo** [comment]
This should work.
![image](https://user-images.githubusercontent.com/2456026/169771009-1d47d75b-7249-4fce-a34c-af0351d4c4a1.png)

But it could be connected to #689
