### ISSUE TITLE
extensions are not shown

### ISSUE THREAD

**Issue by Suman204** [xdebug/vscode-php-debug#410]
Issue Type: <b>Bug</b>

We cannot connect to the extension marketplace at this time please try again later. the above message is displayed everytime I try to install the extension

Extension version: 1.13.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by zobo** [comment]
Is this still happening? I've never seen it and this should probably go to microsot/vscode repository.
