### ISSUE TITLE
Clarify the Readme "VS Code Configuration" section for current workflow

### ISSUE THREAD

**Issue by jerclarke** [xdebug/vscode-php-debug#417]
Hi, thanks for this extension!

This is a small thing, but the following instruction got me tripped up for awhile:

> In your project, go to the debugger and hit the little gear icon and choose PHP. A new launch configuration will be created for you with two configurations:

I think maybe it refers to an older version of VS Code, or maybe it just misses the experience on a fresh copy of VS Code. 

For me, getting started required me to do the following (sorry it's not word-for-word, I can't find a way to get back to that "fresh state" again either):

- Open debug sidebar
- The bar is empty except for a text description of what to do next including a link to "Create launch.json file" (specifically, there's no "gear icon" that does what the description above claims)
- Click that JSON button
- Use the command bar to select from a list of the folders in the current workspace, then choose to create the json file

At that point, the whole UI of the debug sidebar changes, and I think it becomes the one you are expecting where there's a pulldown menu with more options and stuff. 

It's too bad they are so different, because it puts the onus on you to describe everything twice, but maybe it's worth it to make sure that brand new users are able to get off the ground? 

It could even be a statement like "If you are setting up debug for the ground, follow the on-screen instructions to set up a JSON file for the folder you want to debug." I wouldn't have gotten stuck if I'd been given that hint. 

Thanks for considering it!

**Comment by mocsa** [comment]
@jerclarke Totally agree. Without your instructions I couldn't have set up debugging.

**Comment by sKopheK** [comment]
thanks for the guide, added configuration according some other threads here

**Comment by zobo** [comment]
Indeed, a better guide would be welcome.

**Comment by zobo** [comment]
Perhaps the official VSCode documentation could also be used as reference: https://code.visualstudio.com/docs/editor/debugging
