### ISSUE TITLE
Clarify the README "Contributing" section

### ISSUE THREAD

**Issue by zer0uno** [xdebug/vscode-php-debug#422]
The README "Contributing" section should be updated or at least improved. 

Attempting to follow the instructions reported in the section brings you nowhere. In particular the `npm run compile` and `gulp compile` commands fail with, respectively, the error messages `missing script: compile` and `No gulpfile found`.

**Comment by zobo** [comment]
I'm not sure how this errors occurred, but I did rewrite the contributions section in #553
