### ISSUE TITLE
xdebug vs code some breakpoints not working

### ISSUE THREAD

**Issue by Siddharth-Ashri** [xdebug/vscode-php-debug#425]
PHP version:  7.3.25
XDebug version:  2.9.1
Adapter version: v1.13.0

Your launch.json:  
```
{
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9090,
      "pathMappings": {
        "/Users/sid/.config/valet/Nginx/": "${workspaceRoot}/public"
      }
    }
```
XDebug php.ini config:
```
xdebug.remote_enable=1
xdebug.remote_port=9090
xdebug.remote_log=/usr/local/var/tmp/logs/xdebug.log
xdebug.remote_handler=dbgp

```
I am running these configs on macos Big Sur The breakpoints seem to work on certain code snippets but not others. The code is specified in a callback function with a redis lock (that I've disabled for testing purposes). 
even while setting xdebug_break() the callback function that's supposed run still doesn't stop where the break point is set.

**Comment by zobo** [comment]
Please provide log from Debug Console and xdebug_info() diagnostics. There is not enough information to see if there is something wrong with path mappings that are usually problematic.
Reopen if this is still an issue for you.
