### ISSUE TITLE
Sample configuration doesn't appear on Gear icon click

### ISSUE THREAD

**Issue by dims12** [xdebug/vscode-php-debug#432]
PHP version:  Doesn't apply
XDebug version:  Doesn't apply
Adapter version: Doesn't apply

Your launch.json: Any 
XDebug php.ini config: Doesn't apply

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  Doesn't apply
Adapter logfile (from setting `"log": true` in launch.json): Doesn't apply

Code snippet to reproduce: Doesn't apply

It is said in documentation, that sample `launch.json` configurations will appear on clicking gear icon. But this doesn't happen.

**Comment by AnrDaemon** [comment]
Not specifically that way, but "Add configuration" dialog is missing PHP debugger.
You can only create template configuration if you don't have `launch.json` at all.

**Comment by zobo** [comment]
This was fixed a while back and should be in latest releases. It was also extended a lot in the last release (see #585 and #588)
