### ISSUE TITLE
"Everything" breakpoint is set by default when running

### ISSUE THREAD

**Issue by jasonwilliams** [xdebug/vscode-php-debug#481]
PHP version:  7.4.4
Adapter version: 1.1.4.5

When I start a debugging session "Everything" is pre-selected in Breakpoints on the bottom, so i need to keep unticking it. Is there a solution for this?

**Comment by zobo** [comment]
Hum. In my experience, the configuration is retained inside a workspace. How are you running your VS Code?

**Comment by jasonwilliams** [comment]
@zobo how do you mean exactly, that’s quite a broad question. Just a typical php project, when I launch “xdebug” everything is already selected.

Also what do you mean configuration is retained in the workspace?

**Comment by zobo** [comment]
Hi! Sorry it was indeed vague. The "Everything" exception breakpoint is indeed on by default, but VS Code should remember what you select after that. My experience:
1. Run VS Code and do Open Folder...
2. Change the breakpoints...
3. Close VS Code, reopen it and if needed Open Folder... again (or use Open Recent).

The changes you made to breakpoints should be retained. Do you see the same, or are you experiencing something different?

Aside from changing the default, there is not much I can do. Maybe it would make sense to have Errors and Exceptions on by default, but I'm not sure how to measure user feedback for cases like this...

**Comment by jasonwilliams** [comment]
> The "Everything" exception breakpoint is indeed on by default

@zobo no other debugger (I know of) has all exceptions or “Everything” on by default. The VSCode JavaScript debugger certainly doesn’t, it’s quite disruptive because I need to constantly turn it off. I really feel the default should be off and if someone needs “Everything” they can turn it on.

> The changes you made to breakpoints should be retained. Do you see the same, or are you experiencing something different?

Returning to a project (after closing it, reopening it, then starting the debugger again) it comes back on so I need to turn it off again. This extension is the only debugger where this happens. I’ve used other debuggers in VSCode and it hasn’t been an issue there.

**Comment by zobo** [comment]
> @zobo no other debugger (I know of) has all exceptions or “Everything” on by default. The VSCode JavaScript debugger certainly doesn’t, it’s quite disruptive because I need to constantly turn it off. I feel the default should be off and if someone needs “Everything” they can turn it on.

I'm inclined to agree with you here, however from my experience with Visual Studio there are some Exceptions that have breakpoints on by default. In any case that should not be "all". I will research the issue a bit and see if I want to change it to Off on all or to change default On on Exception and Error.

Thanks for bringing this to my attention.

> Do you know where the config is stored once I’ve selected it to off? It doesn’t seem to persist

I have not looked before, but did so now. A quick google: https://stackoverflow.com/questions/57767800/where-does-breakpoints-stores . I have looked on my PC and indeed there in the SQLite database I can see the breakpoints sate persist. Maybe you have an issue with your local permissions, I'm not sure on what OS you are working on.

**Comment by zobo** [comment]
After discussions with @derickr I have decided to change the default to all off.

**Comment by zobo** [comment]
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.16.0
