### ISSUE TITLE
1.14.6 Can't connect via SSH remote development but 1.14.5 works with same settings.

### ISSUE THREAD

**Issue by jtowe1** [xdebug/vscode-php-debug#490]
PHP version:  7.3.26
XDebug version:  2.9.6
Adapter version: 1.14.6

Your launch.json:  
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "log": true
        }
    ]
}
```
XDebug php.ini config:
```
; Enable xdebug extension module
zend_extension = xdebug.so
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_log = /home/me/log/xdebug.log
xdebug.remote_port = 9003
xdebug.show_error_trace = 1
```
XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
```
[21447] Log opened at 2021-02-02 17:25:10
[21447] I: Connecting to configured address/port: localhost:9003.
[21447] W: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[21447] E: Could not connect to client. :-(
[21447] Log closed at 2021-02-02 17:25:10
```
Adapter logfile (from setting `"log": true` in launch.json):
```
No log produced
```

I'm using SSH to remote debug.  If I use adapter version `1.14.6` and click the play button on the debug tab, the little blue loading thing under it goes by a few times and then nothing.  If I uninstall `1.14.6` and install `1.14.5` using the vsix file it all works with the same settings.  I have to assume it's an issue in `1.14.6` since I was using `1.14.5` yesterday and it worked, and then today I got `1.14.6` and it doesn't work.

**Comment by proidit** [comment]
same problem ... i have returned to the version1.14.5!

**Comment by zobo** [comment]
Hi. I’ll check it out. Thanks for reporting.

**Comment by hesperanca** [comment]
Same problem. Also had to return to 1.14.5

**Comment by charlesg99** [comment]
Same, 1.14.6 doesn't attach at all for me, no error in the ouput, it just stops. Had to revert to 1.14.5 as well.

**Comment by zobo** [comment]
I can confirm that the same thing happen here, but only on Remote-SSH. I'm looking for the source of the issue, since the code change was small. Thanks for reporting.

**Comment by charlesg99** [comment]
Over here I have the same behavior as described in the issue, without ssh. 1.14.5 works fine. Thanks!

**Comment by erickcomp** [comment]
Same thing here. Buuuuuuut I'm debugging on localhost. I use a VPN, but it is turned off when I'm debugging. I even restart the machine to be sure. 1.14.5 working great.

**Comment by zobo** [comment]
I found the root cause. Altho vscode is making debugging of debug extension really hard.

`Error: Cannot find module 'relateurl'`

I'll figure out where the change came from and revert it in the next few hours.

**Comment by jtowe1** [comment]
Sweet!  Thanks for jumping on that so quickly

**Comment by proidit** [comment]
thanks!
