### ISSUE TITLE
Need to set XDEBUG_TRIGGER for PHP-CLI debugging

### ISSUE THREAD

**Issue by SteveALee** [xdebug/vscode-php-debug#505]
In order for the Launch currently open script to work you need to set the debugger to trigger. I used the specified env var.

Also could  I suggest in the example configs you mention 9003 for v3 in a comment as I missed it in the later text.

Thanks

PHP version: PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Xdebug version: v3.0.2
Adapter version: n/a

Your launch.json:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387

  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9003 // changed for xdebug 3.x
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9003,
      "env": { "XDEBUG_TRIGGER": "1" } // Added so it works
    }
  ]
}
```

Xdebug php.ini config: added to tend of /etc/php/7.4/cli/php.ini
```
[xdebug]
zend_extension = /usr/lib/php/20190902/xdebug.so
xdebug.mode = develop,debug
```

Xdebug logfile (from setting `xdebug.remote_log` in php.ini):
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php

```

**Comment by zobo** [comment]
Hi. I'm already planning an improvement here. You are correct, that it would be better if the extension did as much work as possible for the user.
First I plan to merge in patches that allow the plugin to allocate random ports for the dbgp listener. This will allow easy side-by-side debugging of multiple scripts.
Then there are two options to force start debugging:
1. Using defines on command line: `php -dxdebug.start_with_request=1 -dxdebug.mode=debug -dxdebug.client_port=${port} ...`
2. Or using env `XDEBUG_CONFIG="start_with_request=1 mode=debug client_port=${port}" php ...`
3. Or other env combos like `XDEBUG_MODE=debug XDEBUG_TRIGGER=1 ...`

And then there's the issue of still supporting Xdebug 2...

I'm still considering what the best option is.

Best,
Damjan

**Comment by SteveALee** [comment]
Good to hear. I tried to come up with a good idea for supporting v2 and v3, but the best seems to be give one in the default config, with comments for the other.

Note the env var I set is for php cli not server. Though now I need both.

**Comment by marveloo** [comment]
I think to make it compatible with v2 and v3 out of the box, both `"XDEBUG_TRIGGER": "1"` and `"XDEBUG_SESSION": "1"` should be set in default `launch.json` configuration by the extension.

**Comment by marveloo** [comment]
Also, would it be possible to make it so, that if we don't explicitly specify port number in launch.json, then the extension listens on both port 9000 and port 9003? (Should I start a new issue for this?)

**Comment by LitileXueZha** [comment]
> Good to hear. I tried to come up with a good idea for supporting v2 and v3, but the best seems to be give one in the default config, with comments for the other.
> 
> Note the env var I set is for php cli not server. Though now I need both.

@SteveALee So is it not use for setting env in `launch.json` to start xdebug? And we have to set ini file for `xdebug.start_with_request=yes`.

I tried `xdebug.start_with_request=trigger` and added these environments to vscode, but failed.

**Comment by SteveALee** [comment]
As an update I found a workable solution to be to use the default config to start vocoder debugger  listening and add XDEBUG_SESSION to the command line running my script when required.
