### ISSUE TITLE
Launch.json intellisense doesn't include the envFile option

### ISSUE THREAD

**Issue by SteveALee** [xdebug/vscode-php-debug#506]
```
  "configurations": [
    {
      "name": "sync script",
      "type": "php",
      "request": "launch",
      "envFile": "${workspaceFolder}/.env",
      "program": "${workspaceFolder}/sync/sync.php",
      "cwd": "${workspaceFolder}/sync",
      "port": 9003
    },
```

The "envfile" has a yellow squiggle - but works perfectly (thank you).

VS Code say it is the [extension's responsibility](https://github.com/microsoft/vscode/issues/116654#issuecomment-778841966)

**Comment by zobo** [comment]
Hi!
We do not have support for "envFile". How would it work?
What's the version of the extension you are testing with? There has to be a different explanation how you are seeing desired results...

**Comment by SteveALee** [comment]
aha, found it. The env of the shell I ran `code .` from was inherited when I run the CLI debug. I forgot I had set this when I set the envFile option and thought that was working. But i had just done a `source .env`.

I only thought it was an option as the [VS Code docs say some extensions support it](https://code.visualstudio.com/Docs/editor/debugging#_launchjson-attributes). Ideally it save lots of entries in the env setting (and keeps privacy too)

**Comment by zobo** [comment]
Do you have an example of it? What's the format?  NAME=VAL ? Do you know of an debugger extension that uses this?

**Comment by SteveALee** [comment]
Here's one https://github.com/Microsoft/vscode/issues/36769#issuecomment-495437733

So [putting config in env vars](https://12factor.net/config) keeps it out of code and make it easy to configure your code for different settings (eg staging, live). .env files have been a convenience for some time letting you put all the config is a single file. I'm used to good support in the javascript world and coming back to PHP for a project id like it.  You can put secrets like API keys in the .env and never check into a public repo.

I hacked it a bit for simple use 

.env
```
MU_PAYPAL_CLIENTID=<hash>
MU_PAYPAL_CLIENTSECRET=<Hash>
```

loadenv.sh
```bash
#!/bin/bash

# Script to load a .env file to set and export env vars
# Run as : source ./setenv

set -a; source .env; set +a
```

at command line load an env
```bash
$ source ./loadenv.sh
```

An alternative would be to write PHP code to read it I guess. But there's all the usual putenv() _$ENV etc confusion.

Forr this adapter extension I guess I would like it set the env to all the vars defined in `envfFile`. Alt least for php_CLI. Injecting into the apache server process is harder - usually adding to htaccess but that causes duplicaton and security problems if you want to checkin your .htaccess.

**Comment by SteveALee** [comment]
Here's one https://github.com/Microsoft/vscode/issues/36769#issuecomment-495437733 and even an extension - https://marketplace.visualstudio.com/items?itemName=IronGeek.vscode-env

So [putting config in env vars](https://12factor.net/config) keeps it out of code and make it easy to configure your code for different settings (eg staging, live). .env files have been a convenience for some time letting you put all the config is a single file. I'm used to good support in the javascript world and coming back to PHP for a project id like it.  You can put secrets like API keys in the .env and never check into a public repo.

I hacked it a bit for simple use 

.env
```
MU_PAYPAL_CLIENTID=<hash>
MU_PAYPAL_CLIENTSECRET=<Hash>
```

loadenv.sh
```bash
#!/bin/bash

# Script to load a .env file to set and export env vars
# Run as : source ./setenv

set -a; source .env; set +a
```

at command line load an env
```bash
$ source ./loadenv.sh
```

An alternative would be to write PHP code to read it I guess. But there's all the usual putenv() _$ENV etc confusion.

Forr this adapter extension I guess I would like it set the env to all the vars defined in `envfFile`. Alt least for php_CLI. Injecting into the apache server process is harder - usually adding to htaccess but that causes duplicaton and security problems if you want to checkin your .htaccess.
