### ISSUE TITLE
Unexpected exception halt in debugger

### ISSUE THREAD

**Issue by SteveALee** [xdebug/vscode-php-debug#509]
I may not be understanding something I have some webserver code that stops in the debuger with an exceptio nand I do not expect it to.

The following causes an exception when code is not supplied in the URI querystring. I expect the @ to stop all errors / exceptions

```
$code = @$_GET["code"];
```

Exception has occurred.
Notice: Undefined index: code

In fact it happens a second time when I click continue in the debugger.

I have disabled (unchecked) exceptions in the breakpoint panel

![image](https://user-images.githubusercontent.com/618922/107954783-d38ce000-6f94-11eb-9bba-9b73ea0379f3.png)

Thanks.

**Comment by zobo** [comment]
It's there in the screenshot. You have "break on Notice" selected. This happened: `Notice: Undefined index: code`.
I suggest you select "Exceptions" and "Errors" for best experience.

I'm considering changing the default.

**Comment by SteveALee** [comment]
d'oh!. In my defence it also says '*Exception* has occurred.' Sigh.

Thanks so much.
