### ISSUE TITLE
VSTUDIO code don't attach to command from cli terminal

### ISSUE THREAD

**Issue by marioaprea** [xdebug/vscode-php-debug#510]
PHP version: 7.1.33
Xdebug version: 2.9.8
Adapter version: v1.14.9

Your launch.json: 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "log": true
        }
    ]
}
```

Xdebug php.ini (etc/php/7,1/apache2/php.ini) config:
```
; xdebug
zend_extension = /usr/lib/php/20160303/xdebug.so
;xdebug.remote_enable = 1
;xdebug.remote_autostart = 1


xdebug.profiler_enable_trigger=1
xdebug.profiler_enable=0

xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_connect_back=1
xdebug.remote_port=9000

xdebug.profiler_output_dir="/tmp"


xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_port = 9000
xdebug.client_host = "127.0.0.1"
xdebug.idekey = VSCODE

xdebug.remote_log=/tmp/xdebug.log
```

Xdebug php.ini (etc/php/7,1/apache2/php.ini) config:
```
; xdebug
zend_extentsion=/usr/lib/php/20160303/xdebug.so

xdebug.profiler_enable_trigger=1
xdebug.profiler_enable=0

xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_connect_back=1
xdebug.remote_port=9000

xdebug.profiler_output_dir="/tmp"


xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_port = 9000
xdebug.client_host = "127.0.0.1"
xdebug.idekey = VSCODE

xdebug.remote_log=/tmp/xdebug.log
```

Xdebug logfile (from setting `xdebug.remote_log` in php.ini):
Not created

Adapter logfile (from setting `"log": true` in launch.json):
Not created

Code snippet to reproduce:

```
from terminal in project folder

php app/console oro:cron:ben:mgm:catalog-update


```

**Comment by zobo** [comment]
Hi. You are stating that you are using Xdebug 2, however in the php.ini directives are also those of Xdebug 3. Also the php.ini files you pasted seem to be for apache2 not for cli - maybe that was a typo.

I suggest you try running  `php -v` to see if Xdebug is loaded and of expected version and then `php -i | find "xdebug"` (on windows) or `php -i | grep xdebug` (on linux) to check if the configuration is really applied.

Alternately you could pass them on command line, providing Xdebug is actually loaded into php:
`php -dxdebug.remote_autostart=1 -dxdebug.remote_enable=1 app/console oro:cron:ben:mgm:catalog-update`

**Comment by marioaprea** [comment]
This is result for php -v
PHP 7.1.33-29+ubuntu20.10.1+deb.sury.org+1 (cli) (built: Feb 14 2021 14:14:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-29+ubuntu20.10.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

This is image from phpinfo from web
![image](https://user-images.githubusercontent.com/15245144/108222598-39b26800-7139-11eb-9818-c0c6e4a0bd53.png)

if i make php -i | grep xdebug
I had no results

The debug works well from browser but non from cli commands. 
If i use php -dxdebug.remote_autostart=1 -dxdebug.remote_enable=1 app/console oro:cron:ben:mgm:catalog-update
debug don't work

Thank you for help

**Comment by marioaprea** [comment]
I solved the problem, i wrote zend_extentsion in cli php ini file :( sorry
