### ISSUE TITLE
VS Code + PHP on macOS Big Sur 11.2.1 - issues with default interpreter

### ISSUE THREAD

**Issue by tuck1s** [xdebug/vscode-php-debug#516]
Issue Type: <b>Bug</b>

1. Start with PHP 7.4.8 in /usr/local/bin. `$PATH` has this listed first, rather than the macOS default.

```
which -a php                       
/usr/local/bin/php
/usr/bin/php
```

2. Install VSCode PHP extension and xdebug extension
2. Install xdebug following the "wizard" advice
3. Amend /usr/local/etc/php/7.4/php.ini file to enable xdebug:

```
zend_extension = /usr/local/lib/php/pecl/20190902/xdebug.so
xdebug.mode = debug
xdebug.start_with_request = yes
```

4. Start VS Code. Confirm in Terminal window that the debugger is active.
```
php -v
PHP 7.4.8 (cli) (built: Jul 30 2020 02:10:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
```

5. Run phpinfo() in a test script. Output shows
```
phpinfo()
PHP Version => 7.3.24-(to be removed in future macOS)
```

which of course doesn't have xdebug active, so stepping etc. doesn't work.

6. Workaround: edit `launch.json`. Edit the "Launch currently open script" section. Add

```
            "runtimeExecutable": "/usr/local/bin/php",
```

7. VS Code then runs the correct PHP version.

---

Extension version: 1.14.9
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id 32a33cc6-f35a-4159-a5a0-68ec1a950bc7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30265425

```

</details>

**Comment by zobo** [comment]
This was fixed in #706 Please see #705 for more detailed explanation what was happening.
