### ISSUE TITLE
Debug doesn't stop on break points in VS Code, The restApi was created thru AppServ 

### ISSUE THREAD

**Issue by uliloewi** [xdebug/vscode-php-debug#519]
PHP version: 7.3.10
Xdebug version: php_xdebug-3.0.3-7.3-vc15-x86_64.dll
Adapter version:

**my launch.json:**
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
**my Xdebug php.ini config:**

[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
zend_extension = "C:\AppServ\php7\ext\php_xdebug.dll"

Xdebug logfile (from setting `xdebug.remote_log` in php.ini):
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php

```

Does XDebug give NO support for AppServ.org?

**Comment by stotes** [comment]
@uliloewi You're using XDebug version 3.0 with the old version 2 parameters. 
If you refer to the updated [Readme](https://github.com/xdebug/vscode-php-debug/blob/main/README.md), the version 3.0 recommended configuration exists there.

[https://xdebug.org/docs/upgrade_guide](https://xdebug.org/docs/upgrade_guide) details the change in the paramters set in your `php.ini` config. If you refer to the updated 

I've been battling with this over the past few days as the PHP repository ppa:ondrej/php has updated to xdebug 3.0 for PHP7.4.

Here is my configuration using Windows 10 WSL2 Ubuntu 20.04 
`/etc/php/7.4/cli/con.f/20-xdebug.ini`
```
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request = yes
xdebug.client_port = 9003
xdebug.client_host = 127.0.0.1
xdebug.log = "\tmp\xdebug.log"
xdebug.idekey = VSCODE
```

`launch.json`
```json
{
    "name": "Listen for XDebug",
    "type": "php",
    "request": "launch",
    "port": 9003,
    "log": true,
    "xdebugSettings": {
        "max_children": 10000,
        "max_data": 10000,
        "show_hidden": 1
    }
}
```

**Comment by zobo** [comment]
No feedback, closing. Please reopen if this is still an issue for you. Provide Debug Console logs and xdebug_info() output.
