### ISSUE TITLE
Extension is not starting...totally....

### ISSUE THREAD

**Issue by sharpi22** [xdebug/vscode-php-debug#529]
PHP version: 1,14,11

I have really strange problem with xdebug on vscode on several OS (Ubuntu 20 04, windows 7, windows 10)

Totally don't know why but - it's not working. After installation I'm selecting PHP for debugging, and I see for 2-3 microseconds a window with JSON configuration file and...that's all. Debugger is not starting, on verbose mode there is no errors in vscode console - nothing. Totally don't know what's going on. I have this problem from 1 month, maybe I'm doing something wrong but hey - in the past I was just installing an extension, adding some options to json and thats all o_O.

**Comment by zobo** [comment]
Whats the extension version and vscode version?

**Comment by jkopkiewicz** [comment]
extemsopm 1.14.11 vscode 1.54.3

**Comment by jkopkiewicz** [comment]
Any tips? VSCode was my main tool, today I received new laptop with clean windows 10 - still the same issue.

**Comment by zobo** [comment]
Can you describe your setup? Vscode on windows? What web server and php on what location? Or do you have a remote mount of files? I’ll let you know how launch.json needs to look.

**Comment by Balkoth** [comment]
Something broke vor me too. VSCode (1.54.3) debugger is no longer starting on 1.14.12. Going back to 1.14.9 lets me debug again.

The configuration is:
{
  "name": "Listen for XDebug",
  "type": "php",
  "request": "launch",
  "port": 9003,
  "xdebugSettings": {
	  "max_data": -1
  }
},

**Comment by zobo** [comment]
Hello. Can you also supply your php and xdebug version and the xdebug part of php.ini or better yet phpinfo() part with xdebug settings. Also the xdebug log. Are you running on windows? Wsl? Linux? MacOS? Are you using vscode remote?
How does the plugin fail? Does the debugging start? If you enable log in launch.json is there any activity in debug console? 
Thanks!

**Comment by jkopkiewicz** [comment]
It's happenig on both Windows 10 and Linux (ubuntu 20.04), i described it before. At the moment I have newest wersion of vscode and phpdebug. PHP version and xdebug is not related to this - even we can't start debugging, and it's failing with and without installed php on system. It's just totally NOT starting. Nothing will happend except on first run It's possible to see a json configuration window for 1 or 2 ms.

**Comment by zobo** [comment]
I’ll try to setup a clean setup. Do you think you can catch a screenshot?

**Comment by zobo** [comment]
I'm trying to reproduce this and simply can't. Can you confirm that 1.14.9 works and 1.14.10 does not? Changes there were mostly just comments and a class name. Can you specifically define what version still works and which not any more?

**Comment by zobo** [comment]
I have just tested a fresh vscode install on MacOS and it worked without problems. The only thing I noticed is the process of creating the launch.json. I had to click the “link” Create launch configuration...

**Comment by Balkoth** [comment]
```
OS: Windows 10 2004 (Build 19041.804)
VSCode: 1.54.3
XDebug: php_xdebug-3.0.2-7.4-vc15-nts-x86_64
PHP: 7.4.14
```
```
;[XDebug]
xdebug.mode = debug
xdebug.start_with_request = yes
```

I don't know what is going on either. Today i updated the extension again to 1.14.12 and now debugging is working again. Nothing on my machine has changed. I even restarted the machine yesterday a few times when it was not working.
I just can say that when it did not work, VSCode would try to launch the debugging, but immediately cancel it. I could not find any location where VSCode would log what happened?

**Comment by zobo** [comment]
There was one release a while back that was broken. Some dependency was missing from release. In that case, when you pressed F5 to start the debugger, a small progress bar would show and then nothing. I could also not find any log back then and had to do some command line magic to figure out.  I still need to open an issue with vscode because of that.

**Comment by zobo** [comment]
@jkopkiewicz is the problem still there for you? Can you try to disable all other extensions?

**Comment by zobo** [comment]
No feedback, hopefully issue solved.
