### ISSUE TITLE
Some Superglobal variables array elements are missed

### ISSUE THREAD

**Issue by palansher** [xdebug/vscode-php-debug#538]
Hello! Thank you for such a useful extension!

On breakpoint stop, I cannot see $_SERVER['REQUEST_METHOD'] value and some other $_SERVER values in "Variables/Superglobals" windows. The same in the "mouseover" pop-up window. Pls, look at the screenshot:
43 array elements are declared in the title but much less are shown:

![image](https://user-images.githubusercontent.com/24850253/112925064-ea892b00-9119-11eb-8239-84081be15781.png)

At the same time, the  $_SERVER['REQUEST_METHOD'] value is vsible on xdebug dump web page (shown by exception).
What can I do to be able to watch missed global variables array values in vs code debug interface?

PHP version: 7.2
Xdebug version: 3.0.1
Adapter version: 1.14.12

Your launch.json: 
```
{
"name": "remote XDebug gt-vladp-dev1",
"type": "php",
"request": "launch",
"port": 9000,
 "log": true,
			}
```
Xdebug php.ini config: 

```
[XDebug]
zend_extension = /usr/lib/php/20170718/xdebug.so
xdebug.mode=debug,develop,trace,profile
xdebug.client_port = 9000 
xdebug.idekey=VSCODE
xdebug.start_with_request=no
xdebug.trigger_value = ""
xdebug.start_upon_error = no
xdebug.collect_assignments = 1
xdebug.collect_params = 4
xdebug.collect_return = 1
xdebug.output_dir = /home/vladp/dev/sites/gt-vladp-dev1/public_html/trace
xdebug.start_with_request=trigger
xdebug.trace_format = 1 
xdebug.trace_options = 0 
xdebug.trace_output_name =gtrace.%t.%R
xdebug.var_display_max_children = -1 
xdebug.var_display_max_data = -1 
xdebug.dump_undefined = true 
xdebug.dump.COOKIE = *
xdebug.dump.FILES = *
xdebug.dump.GET = *
xdebug.dump.POST = *
xdebug.dump.REQUEST= *
xdebug.dump.SERVER = *
xdebug.dump.SESSION = *
xdebug.show_error_trace = 1 
xdebug.show_local_vars = 1 
xdebug.var_display_max_depth = -1 
```

Xdebug logfile (from setting `xdebug.remote_log` in php.ini): will be provided if necessary
Adapter logfile (from setting `"log": true` in launch.json): will be provided if necessary

```
xdebug.var_display_max_children | -1 
xdebug.var_display_max_data | -1 
xdebug.var_display_max_depth | -1
```

**Comment by zobo** [comment]
Hi. Yes this is normal and can be overridden by adding the following to your launch.json config:
```
      "xdebugSettings": {
        "max_data": -1,
        "max_children": 200,
        "max_depth": 200
      }
```

I have a task to implement paginated variable retrieval...

**Comment by zobo** [comment]
Related PR not sure if I will implement it like this though #805
