### ISSUE TITLE
index.php breakpoint even when "Everything" unset

### ISSUE THREAD

**Issue by therobyouknow** [xdebug/vscode-php-debug#539]
Same details for below as in: https://github.com/xdebug/vscode-php-debug/issues/532

PHP version:
Xdebug version:
Adapter version:

Your launch.json:
Xdebug php.ini config:

Xdebug logfile (from setting `xdebug.remote_log` in php.ini):
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php

```

**Comment by zobo** [comment]
Please attach Xdebug log. That would help see if there is something strange going on the DBGp communication.

**Comment by zobo** [comment]
Is this still relevant? In the other issue you mention that you have "stopOnEntry": true. Is this the case of your issue?

**Comment by zobo** [comment]
Closing for now due to no feedback. Latest version of the plugin has extended the logging facility. Please provide the plugin log if assistance is needed.
