### ISSUE TITLE
No stop on breakpoint with xdebug on WSL2 (ubuntu, without docker)

### ISSUE THREAD

**Issue by trogne** [xdebug/vscode-php-debug#547]
Hi,

I'm not able to make work xdebug on my WSL2 ubuntu.

I'm not using docker here.  My xdebug with docker works fine (Laravel Sail).

On my WSL2 ubuntu, I have setup PHP and Apache.

I access the website on Windows, at localhost.

\\wsl$\Ubuntu\home\trogne\codecourse\quickeasylwdt
Inside wsl : 
/home/trogne/codecourse/quickeasylwdt
This is where I run "code ." to open vscode.

Maybe my pathMappings is wrong ? 

PHP version:  8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )
Xdebug version:  v3.0.3
Adapter version:  php8.0-xdebug

Launch.json:
{
	"name": "Listen for XDebug",
	"type": "php",
	"request": "launch",
	"port": 9003,
	"pathMappings": {
		"/home/trogne/codecourse/quickeasylwdt" : "${workspaceFolder}"
	},
	"hostname": "localhost"
},

Xdebug config:
/etc/php/8.0/cli/conf.d/
	20-xdebug.ini -> /etc/php/8.0/mods-available/xdebug.ini

/etc/php/8.0/mods-available/xdebug.ini : 
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.discover_client_host=1
xdebug.client_port = 9003
xdebug.max_nesting_level = 512
xdebug.client_host=172.23.208.1
xdebug.start_with_request=yes 
xdebug.log = "/var/www/html/xdebug.log"

/etc/resolv.conf 
nameserver 172.23.208.1

**Comment by zobo** [comment]
I have tested things with WSL1 and they work fine. Can you also attach `xdebug.log`? I haven't yet used WSL2, I understand roughly what the difference is and perhaps this is the problem: `"hostname": "localhost"`. I'm not sure what magic Microsoft did in the network stack, so I could be wrong.

**Comment by trogne** [comment]
thanks zobo!   
It was exactly the problem :  "hostname": "localhost"
It works without.

But "hostname": "localhost" is mandatory for Docker on WSL2.   I don't know why.

**Comment by zobo** [comment]
That's really strange, since running docker on wsl2 would mean that the application is even one more network deeper than this. I'll have a look at it when I can, but since this works I'm closing this case.
