### ISSUE TITLE
`breakpoint_remove` not being sent when removing breakpoints

### ISSUE THREAD

**Issue by bilogic** [xdebug/vscode-php-debug#556]
# PHP version: 
PHP 7.4.13 (cli) (built: Nov 24 2020 10:03:34) ( NTS )
# Xdebug version: 
php74-php-pecl-xdebug.x86_64      2.9.8-1.el8.remi
# VS Code extension version: 
PHP Debug 1.14.0

# Your launch.json:
```
  "launch": {
            "configurations": [
                {
                    "name": "XDebug:9000",
                    "type": "php",
                    "request": "launch",
                    "port": 9000,
                    "log": true,
                    "xdebugSettings": {
                        "max_children": 64,
                        "max_data": 256,
                        "max_depth": 5
                    },
                    "pathMappings": {
                        "\/media\/sf_new\/project": "${workspaceFolder:project}",
                        "\/media\/sf_new\/package-repo\/packages": "${workspaceFolder:project}\/vendor"
                    }
                }
            ]
        },
```

# Xdebug php.ini config:
```
[xdebug]
xdebug.remote_enable=1
xdebug.remote_host=192.168.214.3
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=0
xdebug.remote_connect_back=0
xdebug.remote_log=/var/log/xdebug.log
xdebug.remote_log_level=5
xdebug.idekey=VSCODE

xdebug.trace_format=0
xdebug.auto_trace=0
xdebug.show_mem_delta=1
xdebug.profiler_enable=0
```

# Xdebug logfile (from setting `xdebug.log` in php.ini):
Extracted from my logfile with some comments manually inserted
```BASH

# BREAKPOINT WAS ADDED BEFORE RUNNING THE PHP CODE
# ...

[12744] <- eval -i 11 -- JHJlc291cmNlcw==
[12744] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="11" status="break" reason="ok"><error code="206"><message><![CDATA[error evaluating code]]></message></error></response>

[12744] <- eval -i 12 -- Y29uZmlnKCdtYWlsZ3VuLndlYmhvb2tfam9iJyk=
[12744] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="12"><property type="string" size="40" encoding="base64"><![CDATA[QXZleHNvZnRcVGVjaGJveERvbWFpblxNYWlsZ3VuV2ViaG9va0pvYg==]]></property></response>

# FIRST BROKE INTO MY EXISTING BREAKPOINT, GOING TO REMOVE IT

[12744] <- breakpoint_list -i 13
[12744] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="13"><breakpoint type="line" filename="file:///media/sf_new/package-repo/packages/abc/domain/src/whois.php" lineno="258" state="enabled" hit_count="1" hit_value="0" id="127440001"></breakpoint></response>

# BREAKPOINT REMOVED AT THE MOMENT, GOING TO ADD

[12744] <- breakpoint_list -i 14
[12744] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="14"><breakpoint type="line" filename="file:///media/sf_new/package-repo/packages/abc/domain/src/whois.php" lineno="258" state="enabled" hit_count="1" hit_value="0" id="127440001"></breakpoint></response>

[12744] <- breakpoint_set -i 15 -t line -f file:///media/sf_new/project/vendor/abc/domain/src/whois.php -n 258
[12744] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="15" id="127440002"></response>

# EXITING

```
# VS Code extension logfile (from setting `"log": true` in launch.json):

There was no output on my `Log (Extension Host)` or other `Log (...)` windows.

# Code snippet to reproduce:

Affects all my code.

When I remove my breakpoint (causing `-i 13`), `breakpoint_remove` is not being sent.
I'm unable to capture any logs on my VSCode, which I believe will pinpoint the cause.

Appreciate any assistance. Thank you!

**Comment by bilogic** [comment]
1. I installed this https://github.com/RobberPhex/vscode-php-debug and his did not exhibit the issue.
2. On closer look, I found he had fix https://github.com/RobberPhex/vscode-php-debug/commit/da35648bf720aee412d35d41f6e8789becea7ff2
3. Installed @felixfbecker extension and swapped my path, this time the issue went away
```
"pathMappings": {
    "\/media\/sf_new\/package-repo\/packages": "${workspaceFolder:project}\/vendor", // path of code being debugged
    "\/media\/sf_new\/techbox": "${workspaceFolder:project}"
}
```
4. Possible to incorporate the fix?

Thank you.

**Comment by zobo** [comment]
Hi!

The "VS Code extension logfile" can be viewed in the "DEBUG CONSOLE" in the Panel.

This patch was already incorporated, to some extent, see: https://github.com/xdebug/vscode-php-debug/commit/f2a0dce18017e539cd5b2f52d7c2c4fe2297aa10

Even the prefix path length patch was applied: https://github.com/xdebug/vscode-php-debug/commit/3c66f87f2ad2b6167465ef7e12b7f78c94112cc8

However the path mappings format became a bit more strict in the later versions.

Fist I'm not sure where the backslash characters in the left-hand side of the mappings come from. Second, if your local OS is windows, you should use backslashes. 

```
"pathMappings": {
    "/media/sf_new/package-repo/packages": "${workspaceFolder:project}\\vendor", // path of code being debugged
    "/media/sf_new/techbox": "${workspaceFolder:project}"
}
```

Also, your logs don't really match your path mappsing.

I see `file:///media/sf_new/package-repo/packages/abc/domain/src/whois.php` and `file:///media/sf_new/project/vendor/abc/domain/src/whois.php` where your latest config contains `techbox`.

I could use the whole Xdebug log and the whole VS Code log to get a better understanding of the issue and project structure.

BEst!

**Comment by bilogic** [comment]
@zobo thanks, first, `techbox` was typo.
I will try your suggestions and get back. 

Thank you.

**Comment by bilogic** [comment]
@zobo 

Is there any reason why A works ok but B has the issue?
The only difference is I swapped the order of the paths

```JSON
workspaceFolder:project = E:\projectx\site\new\project\

// A - ok
"pathMappings": {
    "/media/sf_new/package-repo/packages": "${workspaceFolder:project}\\vendor",
    "/media/sf_new/project": "${workspaceFolder:project}"
}

// B - has issues
"pathMappings": {
    "/media/sf_new/project": "${workspaceFolder:project}",
    "/media/sf_new/package-repo/packages": "${workspaceFolder:project}\\vendor"
}
```

I mean, it could save us the trouble of sharing logs if there is an easy explanation.
What I observe from the logs is that when removing the break point, `DEBUG CONSOLE` shows it is removing (`<- setBreakpointsResponse` with `body: { breakpoints: []`}, but XDebug log does not show the same `breakpoint_remove`.

**Comment by zobo** [comment]
Hi!
If VS Code is removing breakpoints, but Xdebug is not receiving this it tells me that the extension cannot match breakpoints returned by `breakpoint_list` with mapped file paths...

The order of the keys should really not matter, as a the code always takes the longest prefix. When mapping a file from IDE to Xdebug it looks at the right side, and when mapping from Xdebug to IDE it looks at the left side of the mapping definitions.

Can you check your extension version again? It should be 1.14.12 not 1.14.0 ?

If that was just a typo, I can try to take the info you gave me so far and write a test.

I was wondering, what kind of setup do you have on your server, that you need two different mappings to the same "local" files? 

Best,
Damjan

**Comment by bilogic** [comment]
Hi @zobo 

![image](https://user-images.githubusercontent.com/946010/116819050-e4ff8480-aba0-11eb-9874-388f6865e371.png)

1. Definitely 1.14.0, I wonder why not the latest, maybe it is due to my VSCode 1.50.1?
2. I'm curious why `DEBUG CONSOLE` did not throw an error when `breakpoint_remove` command was not successful.
3. I swap paths because of the earlier fix was for the extension not being able to process multiple paths properly.
4. My setup is a Windows 10 host, Centos8 guest on VirtualBox using VB's shared folders. VSCode runs on Windows 10. There are 2 mappings because some folders in `/media/sf_new/project/vendor/` are symlinked to `/media/sf_new/package-repo/packages`.

Let me try and figure out why it's stuck at `1.14.0`. Thank you.

**Comment by zobo** [comment]
Interesting. The current VS Code requirements are 1.53.0 (https://github.com/xdebug/vscode-php-debug/blob/main/package.json#L18). And the next bigger release will require the latest VS Code (1.56) since I'm using features that are only just implemented. One option for you to test this could also be to download a standalone zip for vscode insiders...

**Comment by bilogic** [comment]
Ok, let me try with the latest VS Code. Will update again. Hopefully this gets solved for good, it was hampering my ability to debug properly (Imagine being unable to remove breakpoints in a big loop).

Thank you!

**Comment by bilogic** [comment]
@zobo great news! I'm on 1.55.2 and no more issues.

> ```
> // B - has issues
> "pathMappings": {
>     "/media/sf_new/project": "${workspaceFolder:project}",
>     "/media/sf_new/package-repo/packages": "${workspaceFolder:project}\\vendor"
> }
> ```

And I specifically tested with this config. Thank you so much!
