### ISSUE TITLE
Disable `error evaluating code` toast

### ISSUE THREAD

**Issue by bilogic** [xdebug/vscode-php-debug#557]
![image](https://user-images.githubusercontent.com/946010/116851324-c347e100-ac24-11eb-8993-bef5ca900e59.png)

![image](https://user-images.githubusercontent.com/946010/116851508-086c1300-ac25-11eb-9330-45f38113e6d8.png)

Hi!

Is there a way to disable the `error evaluating code` popup?

I understand why it shows up, but it's quite distracting. After all, it is already indicated quite clearly in the `WATCH` area.

Thank you!

**Comment by zobo** [comment]
If its already presented in the watch pane, then it doesn't make sense.. I'll have a look

**Comment by zobo** [comment]
Doesn't seem to be possible. Will open an issue with Microsoft.

**Comment by zobo** [comment]
I found this: https://github.com/microsoft/vscode/issues/87443 It seems possible. Will investigate.

**Comment by zobo** [comment]
Should be solved in the latest release.

**Comment by bilogic** [comment]
Wow thanks!

**Comment by zobo** [comment]
I'd appreciate a field test :) Let me know if something broke.

**Comment by bilogic** [comment]
Just did. Works! I also did a took a peek at the commit, 4 lines of changes, no damage done. :)
Thanks alot!
