### ISSUE TITLE
XDebug not working. All sems fine.

### ISSUE THREAD

**Issue by BGFR** [xdebug/vscode-php-debug#559]
I am trying to run XDebug, but the steps do not work. When press "Start Debug" the steps menu only flashes and the result appears in the Debug Console. It must be something small, but i cannot figure it out. There are no log files. XDebug works fine with PhpStorm on the same PC.
![image](https://user-images.githubusercontent.com/33952672/117130725-1d71af00-ada9-11eb-9ecc-2f3e4181cfb4.png)
![image](https://user-images.githubusercontent.com/33952672/117130543-e3a0a880-ada8-11eb-93c4-3dff1e03e9e8.png)

**PHP version:** 
PHP 8.0.3 (cli) (built: Mar  2 2021 23:34:05) ( ZTS Visual C++ 2019 x64 )
Zend Engine v4.0.3, Copyright (c) Zend Technologies

**Xdebug version:** Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
VS Code extension version: 1.55.2 

**Your launch.json:**
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "runtimeExecutable": "D:\\Program Files\\xampp\\php\\php.exe",
            "log": true
        }
    ]
}

**Xdebug php.ini config:**

[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
zend_extension = "D:\Program Files\xampp\php\ext\php_xdebug.dll"

**Xdebug logfile (from setting `xdebug.log` in php.ini):**

**VS Code extension logfile (from setting `"log": true` in launch.json):**

**Code snippet to reproduce:**
```php
$input = explode(" ","123 234 12");
$sum = 0;
for($i = 0; $i < count($input); $i++){
   $sum += strrev($input[$i]);
}
echo $sum;
```

**Comment by zobo** [comment]
Seems like it doesn’t hit the breakpoint. If Insee right you are running this on windows (IDE and PHP). Can you attach the whole vscode log and xdebug remote log? It looks like you are running Xdebug 2. The setting is xdebug.remote_log

**Comment by BGFR** [comment]
Hi zobo, thank you for paying attention. 

I added xdebug.remote_log at the end of [XDebug] in php.ini, but there is nothing in it. Is that what you meant?
```
[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
zend_extension = "D:\Program Files\xampp\php\ext\php_xdebug.dll"
xdebug.remote_log="D:\PHP\xdebuglog.txt"

```
Below is the full vscode log, which i enabaled by adding "log": true to launch.json
```

<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true
}

<- outputEvent
OutputEvent {
  seq: 0,
  type: 'event',
  event: 'output',
  body: { category: 'stdout', output: '774' }
}

774
<- terminatedEvent
TerminatedEvent { seq: 0, type: 'event', event: 'terminated' }

-> disconnectRequest
{
  command: 'disconnect',
  arguments: { restart: false },
  type: 'request',
  seq: 3
}
```



> 
> 
> Seems like it doesn’t hit the breakpoint. If Insee right you are running this on windows (IDE and PHP). Can you attach the whole vscode log and xdebug remote log? It looks like you are running Xdebug 2. The setting is xdebug.remote_log

**Comment by zobo** [comment]
Yes, I just realized you have Xdebug 3, so php.ini is wrong.

From the README the correct configuration would be:

```ini
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.log = D:\PHP\xdebuglog.txt
```

And change your port from 9000 to 9003 in `launch.json`.

**Comment by BGFR** [comment]
> 
> 
> Yes, I just realized you have Xdebug 3, so php.ini is wrong.
> 
> From the README the correct configuration would be:
> 
> ```ini
> xdebug.mode = debug
> xdebug.start_with_request = yes
> xdebug.log = D:\PHP\xdebuglog.txt
> ```
> 
> And change your port from 9000 to 9003 in `launch.json`.

Ok. As a matter of fact i started with setting for xdebug 3 and then switched to setting for xdebug 2.
Anyway, currently php.ini is changed as follows
```
[XDebug]
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.log = D:\PHP\xdebuglog.txt
xdebug.client_port = 9003
```
and edited launch.json as follows:

```
{
   "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9003,
            "runtimeExecutable": "D:\\Program Files\\xampp\\php\\php.exe",
            "log": true
        }
    ]
}
```
then i restarted it all and ran the php test code and result is the same. It is still not hitting breakpoints and xdebuglog.txt is empty

**Comment by zobo** [comment]
If the xdebug.log is still empty, my guess would be, your .ini is not loaded... Try running `php -i` and look at the output of what .ini files are loaded, and what the value of relevant xdebug settings actually are.

You can also try with this `launch.json`. This will force the right php settings over command line and env.

```
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9003,
      "runtimeArgs": ["-dxdebug.start_with_request=yes"],
      "env": {
        "XDEBUG_MODE": "debug,develop",
        "XDEBUG_CONFIG": "client_port=9003"
      }
    }
```

**Comment by BGFR** [comment]
> 
> 
> If the xdebug.log is still empty, my guess would be, your .ini is not loaded... Try running `php -i` and look at the output of what .ini files are loaded, and what the value of relevant xdebug settings actually are.
> 
> You can also try with this `launch.json`. This will force the right php settings over command line and env.
> 
> ```
>     {
>       "name": "Launch currently open script",
>       "type": "php",
>       "request": "launch",
>       "program": "${file}",
>       "cwd": "${fileDirname}",
>       "port": 9003,
>       "runtimeArgs": ["-dxdebug.start_with_request=yes"],
>       "env": {
>         "XDEBUG_MODE": "debug,develop",
>         "XDEBUG_CONFIG": "client_port=9003"
>       }
>     }
> ```
Regarding php -i output. 650 lines do not contain "xdebug". 
Below are the first 40 lines, where **Debug Build => no**
I am not sure what to look for
```

D:\Program Files\xampp\php>php -i
phpinfo()
PHP Version => 8.0.3

System => Windows NT USER 10.0 build 18363 (Windows 10) AMD64
Build Date => Mar  2 2021 23:26:36
Build System => Microsoft Windows Server 2016 Standard [10.0.14393]
Compiler => Visual C++ 2019
Architecture => x64
Configure Command => cscript /nologo /e:jscript configure.js  "--enable-snapshot-build" "--enable-debug-pack" "--with-pdo-oci=c:\php-snap-build\dep-aux\oracle\x64\instantclient_19_9\sdk,shared" "--with-oci8-12c=c:\php-snap-build\dep-aux\oracle\x64\instantclient_12_1\sdk,shared" "--with-oci8-19=c:\php-snap-build\dep-aux\oracle\x64\instantclient_19_9\sdk,shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--without-analyzer" "--with-pgo"
Server API => Command Line Interface
Virtual Directory Support => enabled
Configuration File (php.ini) Path =>
Loaded Configuration File => D:\Program Files\xampp\php\php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
PHP API => 20200930
PHP Extension => 20200930
Zend Extension => 420200930
Zend Extension Build => API420200930,TS,VS16
PHP Extension Build => API20200930,TS,VS16
**Debug Build => no**
Thread Safety => enabled
Thread API => Windows Threads
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => disabled

Registered PHP Streams => php, file, glob, data, http, ftp, zip, compress.zlib, compress.bzip2, https, ftps, phar
Registered Stream Socket Transports => tcp, udp, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters => convert.iconv.*, string.rot13, string.toupper, string.tolower, convert.*, consumed, dechunk, zlib.*, bzip2.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v4.0.3, Copyright (c) Zend Technologies
```


With the new launch.json settings step menu stuck on the top with step arrows still inactive.
![image](https://user-images.githubusercontent.com/33952672/117144329-7ac22c00-adba-11eb-81ed-20b31b593560.png)

**Comment by zobo** [comment]
Hi. I guess I mislead you a bit.  Since you don't have your php.exe in PATH add this `"runtimeExecutable": "D:\\Program Files\\xampp\\php\\php.exe",` back to your launch.json.

Then I'm guessing the [xdebug] section of your ini is part of your main `php.ini` file. From what I see this is here: `D:\Program Files\xampp\php\php.ini`.

Since your `php -i` doesn't show Xdebug being loaded, you probably removed this line `zend_extension = "D:\Program Files\xampp\php\ext\php_xdebug.dll"`. Add it back to php.ini.

You can also paste all this phpinfo() output into https://xdebug.org/wizard and it will give you some hints. More Xdebug installation instructions can be found here: https://xdebug.org/docs/install

Let me know if you can run your php script again and if Xdebug is loaded again and if xdebug.log is still empty after that.

**Comment by BGFR** [comment]
> 
> 
> Hi. I guess I mislead you a bit. Since you don't have your php.exe in PATH add this `"runtimeExecutable": "D:\\Program Files\\xampp\\php\\php.exe",` back to your launch.json.
> 
> Then I'm guessing the [xdebug] section of your ini is part of your main `php.ini` file. From what I see this is here: `D:\Program Files\xampp\php\php.ini`.
> 
> Since your `php -i` doesn't show Xdebug being loaded, you probably removed this line `zend_extension = "D:\Program Files\xampp\php\ext\php_xdebug.dll"`. Add it back to php.ini.
> 
> You can also paste all this phpinfo() output into https://xdebug.org/wizard and it will give you some hints. More Xdebug installation instructions can be found here: https://xdebug.org/docs/install
> 
> Let me know if you can run your php script again and if Xdebug is loaded again and if xdebug.log is still empty after that.

Hi zobo, it works like a charm now. I was in a rush and I did not realize those are basic settings. It all works fine now. Thank you for all your help.

**Comment by zobo** [comment]
Great!
