### ISSUE TITLE
Restrict ide key/session name

### ISSUE THREAD

**Issue by andrews05** [xdebug/vscode-php-debug#572]
Is it possible to specify an ide key that the client should listen for, ignoring any sessions that don't match?

**Comment by zobo** [comment]
Not currently. The IDEKEY is usually part of the dbgp proxy setup. I have this in the pipeline. In that use case you'd actually get the functionality you are requesting here. I was wondering what's your use case. Is this a shared setup? Is it a local setup and you are using this for some sort of filtering?
Let me know, so I can asses what the best solution would be.

**Comment by andrews05** [comment]
Thanks for your answer, yeah I think the proxy would probably solve this. Any idea when that might be coming?

Basically yeah, it's a shared setup where multiple people may be debugging on different ports and we don't want to pick up each other's exceptions.

**Comment by zobo** [comment]
I might add "filter by idekey", I'm just wondering if it actually solves your issue or not. Do you use "connect back" option and everybody uses the same port?
I plan on adding proxy support in the next major release. Hopefully next month after I do some smaller fixes. Time is limited :)

**Comment by andrews05** [comment]
We use the remote development extensions, so effectively it's all "local" and the connect back doesn't apply. Not too worried about multiple people debugging at the same time, but certainly multiple people are accessing the server at the same time and the person debugging will end up catching everyone's errors.

An alternative solution could be to restrict the file paths. You can currently set an ignore list in the launch.json but if you could instead just whitelist a specific folder then that would fix our issue too.

That said, probably best to focus on the proxy for now as it could well be the solution.

**Comment by zobo** [comment]
This is the same problem we have. Currently we just "take turns", but the right way is the proxy. It's one of the next big things I intend to cover.
