### ISSUE TITLE
Breakpoints became "Unverified Breakpoint" immediately during a remote debugging session

### ISSUE THREAD

**Issue by slyang-git** [xdebug/vscode-php-debug#581]
PHP version:
```
php -v:

PHP 7.4.9 (cli) (built: Aug 31 2020 12:39:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```
Xdebug version: v3.4.0
VS Code extension version: 1.15.1

Your launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "stopOnEntry": false,
            "pathMappings": {
                "/home/application/pre-sale/v1": "/Users/slyang/pre-sale"
            },
            "xdebugSettings": {
                "max_children": 128
            },
            "log": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```
Xdebug php.ini config:
```
[xdebug]
zend_extension=/home/xiaoju/php7/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so
xdebug.idekey=vscode
xdebug.client_host=172.25.48.20
xdebug.client_port=9003
xdebug.client_handler=dbgp
xdebug.auto_trace=1
xdebug.log=/tmp/xdebug.log
xdebug.mode=debug
```

Xdebug logfile (from setting `xdebug.log` in php.ini):
```

[6481] [Step Debug] <- breakpoint_set -i 56 -t line -f file:///home/xiaoju/webroot/gulfstream/application/pre-sale/v1/app/logics/estimatePrice/ParamsLogic.php -n 562

[6481] [Step Debug] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="56" id="64810027" resolved="unresolved"></response>

```
VS Code extension logfile (from setting `"log": true` in launch.json):
```
-> setBreakpointsRequest
{
  command: 'setBreakpoints',
  arguments: {
    source: {
      name: 'ParamsLogic.php',
      path:  '/home/application/pre-sale/v1": "/Users/slyang/pre-sale'
    },
    lines: [ 562 ],
    breakpoints: [ { line: 562 } ],
    sourceModified: false
  },
  type: 'request',
  seq: 171
}

<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 171,
  command: 'setBreakpoints',
  success: true,
  body: {
    breakpoints: [
      {
        verified: false,
        line: 562,
        source: {
          name: 'ParamsLogic.php',
          path: '/Users/slyang/pre-sale/app/logics/estimatePrice/ParamsLogic.php'
        },
        id: 198
      }
    ]
  }
}

2
<- breakpointEvent
BreakpointEvent {
  seq: 0,
  type: 'event',
  event: 'breakpoint',
  body: { reason: 'changed', breakpoint: { id: 198, verified: false } }
}
```

### Additional Info
- I have tried on PHPStorm IDE the same way, it works well.

**Comment by zobo** [comment]
Hi!
This is expected behavior since 1.15. When the debugger connects to Xdebug it sends all breakpoints to it and checks the response.  As is seen in the log, the breakpoint is unresolved: `resolved="unresolved"`. When Xdebug first encounters the file file:///home/xiaoju/webroot/gulfstream/application/pre-sale/v1/app/logics/estimatePrice/ParamsLogic.php breakpoint will become resolved and will turn red again.

If that does not happen, please check that PHP execution eventually reaches this file, and then please send me the whole xdebug.log. There should be a notify in there that changes the resolved value.

**Comment by zobo** [comment]
There is another aspect of this bug. If the debugger is running and listening, but there is no connected sessions, a change in breakpoints will result the being in unverified state. That part does not make much sense... I'll look at this.

**Comment by TonyGravagno** [comment]
I recently noticed this behavior too. Debugging a WordPress plugin, the breakpoints in the WP code are set, but my plugin breakpoints are unverified (shown as disabled or at least not red) until that code is executed. I might have that wrong. I think I saw the breakpoints appear to disable as well. Suffice to say there is some visual awkwardness here that catches the eye.

However it works, it's fine, as long as we know how it works, but the immediate thought is that there is something wrong. I'm thinking a doc note on this might be all that's required. Or maybe changing the breakpoint icon or color would help when the breakpoint is not in a red/active state.

Thanks!

**Comment by zobo** [comment]
Although technically correct - Xdebug can only verify the breakpoint once the PHP file in question is loaded. With language runtimes like node.js and .NET all files are usually loaded right away so the unverified/disabled indicator is not there for long.
I have a feeling this will start to bother more people and I'm considering not marking them as unverified... Perhaps I'll move this behavior behind a launch.json flag.

**Comment by zobo** [comment]
I have fixed this, at least partially. Breakpoints will be verified if there are no active connections.
