### ISSUE TITLE
Debugger not breaking at breakpoint - Windows 10

### ISSUE THREAD

**Issue by HiteshDutt** [xdebug/vscode-php-debug#583]
PHP version:  PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:48) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Xdebug version:  NA
VS Code extension version: v1.15.1

Your launch.json:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

Xdebug php.ini config:

NA

Xdebug logfile (from setting `xdebug.log` in php.ini):
VS Code extension logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php
Main File: index.php
<?php

require_once __DIR__.'/person.php';

$person = new Person('Micky', '32');

echo "Person Name is " . $person->getName();

?>

Class File: person.php

<?php

class Person{
    private $name;
    private $age;

    public function __construct($name, $age)
    {
        $this->name = $name;
        $this->age = $age;
    }

    public function getName()
    {
        return $this->name;
    }
}
 ?>
```

ISSUE:

Even After installing the extension I am not able to debug code, I can see correct output in DEBUG CONSOLE terminal, but code does not break at breakpoint

![image](https://user-images.githubusercontent.com/14161283/119248917-225c9e00-bbb2-11eb-89f9-e6c1af431d7f.png)

Looking for help to enable debug directly from visual studio code, xdebug is not used so far

**Comment by zobo** [comment]
Hi @HiteshDutt !

This extension provides a frontend to interact with PHP/Xdebug. It speaks the DBGp debug protocol that is exposed by Xdebug.

The PHP engine in itself does not have remote debugging support and an extension (Xdebug) is required for that. 

I looked at your PHP version and you need this Xdebug build: PHP 7.3 VC15 TS (64 bit)

It's best you start here https://xdebug.org/docs/install#windows and then look over the configuration described in this plugins README. There's also a lot of YouTube videos on this topic...

I'll close this issue, but let me know if you can't set it up and I'll give some more pointers.

**Comment by HiteshDutt** [comment]
@zobo ,

Thank you for your response, I am not trying to debug a remote application, but trying to debug a script directly using the second part of configuration.  "Launch currently open script"

I am not sure if my understanding is correct, but xdebug is required to debug the applications deployed on xampp or apache2 and using port 9000.

Now again apologies for my limited understanding of this extension, I am just trying to debug my single page script that echos person details. and it does echo it to debug console, just that the debug point is not hit.

**Comment by zobo** [comment]
Hi!
Yes, ignore the “remote” part as that is just a technical detail. 
Even if you try to debug a local script, Xdebug is required. 

You see the script output since this plugin launches the script, but because there is no Xdebug a debug connection is never created and the script runs without debugging. 

I’ll try to find some resources that explain this better later...

**Comment by HiteshDutt** [comment]
@zobo ,

Thank you for taking time. Apologies for my misunderstanding about xdebug being used for only remote debugging.

I have now used xdebug version downloaded based on phpinfo and it is working like a charm.

Thanks a ton
