### ISSUE TITLE
Can not find xampp database

### ISSUE THREAD

**Issue by seyedrezabazyar** [xdebug/vscode-php-debug#587]
PHP version: 8.0.6
Xdebug version:  PHP Debug 1.15.1
VS Code extension version: 1.56.2 (Universal)

hello
I installed the latest version of php. I also installed the latest version of vscode. I also installed the latest version of xampp
My debugger could not find the xampp database

I created a database called world
I'm connected to it with mysqli

my code:
`<?php
$mysqli = new mysqli("localhost" , "root" , "" , "world");
if ($mysqli->connect_errno) {
    echo "ERROR:" . $mysqli->connect_errno;
    exit;
}
echo "connected";
?>`

Answer in the browser: connected

Answer in vscode debugger: 
`PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in /Users/myusername/.bitnami/stackman/machines/xampp/volumes/root/htdocs/tempCodeRunnerFile.php on line 2
PHP Stack trace:
PHP   1. {main}() /Users/myusername/.bitnami/stackman/machines/xampp/volumes/root/htdocs/tempCodeRunnerFile.php:0
PHP   2. mysqli->__construct($hostname = 'localhost', $username = 'root', $password = '', $database = 'world') /Users/myusername/.bitnami/stackman/machines/xampp/volumes/root/htdocs/tempCodeRunnerFile.php:2

Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /Users/myusername/.bitnami/stackman/machines/xampp/volumes/root/htdocs/tempCodeRunnerFile.php on line 2

Call Stack:
    0.0007     395536   1. {main}() /Users/myusername/.bitnami/stackman/machines/xampp/volumes/root/htdocs/tempCodeRunnerFile.php:0
    0.0009     395920   2. mysqli->__construct($hostname = 'localhost', $username = 'root', $password = '', $database = 'world') /Users/myusername/.bitnami/stackman/machines/xampp/volumes/root/htdocs/tempCodeRunnerFile.php:2

ERROR:2002`

In xampp software, I click on the "open terminal" button and it connects to the database (mysql -u root -p)
BUT
The vscode debugger terminal does not connect to the database

**Comment by AnrDaemon** [comment]
mysql uses socket to connect to "localhost". Use 127.0.0.1.
And never use "root" unless you are performing database administration tasks.

Not an xdebug, VS Code or extension issue.

**Comment by zobo** [comment]
I'm not sure if this is the same on windows (inferred from the reported path), but in any case, yes, this has nothing to do with the debugger... Closing.

**Comment by AnrDaemon** [comment]
> I'm not sure if this is the same on windows

It is. (I'm using Windows primarily.)
