### ISSUE TITLE
Education-Course-Study-Pro

### ISSUE THREAD

**Issue by Mohamph2** [xdebug/vscode-php-debug#598]
Issue Type: <b>Bug</b>

Education-Course-Study-Pro

Extension version: 1.16.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz (2 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|1.97GB (0.44GB free)|
|Process Argv|C:\\Users\\ABAB PRINTING\\Desktop\\Education-Course-Study-Pro --crash-reporter-id dcccc67d-3478-4d3e-aae3-0f72ce804315|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by zobo** [comment]
Hi. I'm not sure what you are reporting here. Can you give me more info? Best.

**Comment by zobo** [comment]
Since there is no feedback on this I'll close the issue.
