### ISSUE TITLE
New and unexpected restriction on Xdebug Client listening

### ISSUE THREAD

**Issue by skyred** [xdebug/vscode-php-debug#601]
PHP version: 7.4
Xdebug version: 3.0.3
VS Code extension version: 1.16.0
VSCode version: 

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic snap
```

Your launch.json: 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "pathMappings": {
                "/opt/drupal": "${workspaceRoot}"
            },
            "log": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9003,
            "log": true
        }
    ]
}
```
Xdebug php.ini config:

https://github.com/INsReady/docker-drupal-dev/blob/f1c0413f2ddc23f2e2f28397c1ec7f458c03aee2/8/Dockerfile#L26-L32

Xdebug logfile (from setting `xdebug.log` in php.ini):
VS Code extension logfile (from setting `"log": true` in launch.json):

```
[3562] [Step Debug] INFO: Checking remote connect back address.
[3562] [Step Debug] INFO: Checking header 'HTTP_X_FORWARDED_FOR'.
[3562] [Step Debug] INFO: Checking header 'REMOTE_ADDR'.
[3562] [Step Debug] INFO: Client host discovered through HTTP header, connecting to 172.20.0.1:9003.
[3562] [Step Debug] WARN: Creating socket for '172.20.0.1:9003', poll success, but error: Operation now in progress (29).
[3562] [Step Debug] WARN: Could not connect to client host discovered through HTTP headers, connecting to configured address/port: host.docker.internal:9003. :-|
[3562] [Step Debug] WARN: Creating socket for 'host.docker.internal:9003', poll success, but error: Operation now in progress (29).
[3562] [Step Debug] ERR: Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
```

Code snippet to reproduce:

```php

```

Recently, I noticed that the Xdebug Client cannot listen to services/requests from either docker container or remote hosting. After turning on the debugging, I ran `sudo ss -tulpn | grep 9003`, and below is the result

![image](https://user-images.githubusercontent.com/164034/122956812-eafd2f00-d3b3-11eb-82d8-0daf9470ec6a.png)

I am guessing previously the port was open on `0.0.0.0:9003`. For comparison, this is from Phpstorm: `*:9003             *:*`

So, is this a new default security feature (from vscode)? How can we override it to listen to any network?

**Comment by zobo** [comment]
Hi. I have not yet seen that issue, but it could be something from vscode. Try adding host: “0.0.0.0” to configuration. I will research it as soon as I can.

**Comment by skyred** [comment]
How? `launch.json` can't accept `port:0.0.0.0:9003`

**Comment by skyred** [comment]
Tested with vscode

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-74-generic
```

The network listening result is below:

```
sudo ss -tulpn | grep 9000
tcp     LISTEN   0        511                    *:9003                 *:*      users:(("code",pid=10557,fd=27))
```

**Comment by skyred** [comment]
Found t he culprit: https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_57.md#port-forwarding-tunnels-are-bound-to-localhost

So, the solution is in that link, in most case, just change the setting `remote.localPortHost` to `allInterfaces`
