### ISSUE TITLE
Possible conflict with PHP-DI / PHP-DI container

### ISSUE THREAD

**Issue by palansher** [xdebug/vscode-php-debug#602]
PHP version: 7.4
Xdebug version: 3.04
VS Code extension version: v1.16.0

Hello there !!! That for a pretty good debugging tool. But today I was left without it :(

Would you please help me to find how the third-part composer package affects your extension!

I noticed the problem (after I migrated from PHP 7.2 to 7.4 and added a lot of composer packages)  that the step-debug mode still active for only 2-3 seconds, after triggered from the Chrome add-on.
  I record the [video](https://www.dropbox.com/s/78f7fyt17dnezjh/mhoxfUEjTa.mp4?dl=0).

BTW: VS Code is on local Windows 10 PC. The managed server is on ssh remote ununtu server.

In the video I showed two examples:
1
- set the break point
- started debugging in vs code
- refreshed the web page

and we see that debugging mode stopped itself involuntarily after a couple of seconds

2
then I commented offending line:
`$container = $containerBuilder->build()`
and repeated previous steps

Now we see in the video that step-debug mode still active infinitely: we can see traced variables etc.
So the extension now works as designed.
`$container = $containerBuilder->build()` 
-> its is the command to set up worldly popular dependency injection container: https://github.com/PHP-DI/PHP-DI  (latest v6.3.4)

Also I commented lines, that loaded configuration of container:
`$containerBuilder->addDefinitions(__DIR__ . '/../config/admin_container.php');` 
to exclude possible effect.
But no difference- the only '->build' method makes the problem.

I am ready to provide more details if necessary. Please help to decide who is blamed: me, the extention or PHP-DI  :)

thank you!

Your launch.json:
```
"name": "remote XDebug gt-vladp-dev1",
				"type": "php",
				"request": "launch",
				"port": 9003,
				"xdebugSettings": { //Переопределяет значения по умолчанию
					"max_data": -1,
					"max_children": 200,
					"max_depth": 200
				},
```
			

```
Xdebug php.ini config:
[XDebug]
xdebug.client_host=localhost

xdebug.mode=develop,debug
xdebug.client_port = 9003
xdebug.log=/var/log/xdebug.log
xdebug.log_level = 3

xdebug.idekey=vscode
xdebug.trigger_value = ""
xdebug.start_upon_error = no

;trace
xdebug.collect_assignments = 1
xdebug.collect_params = 4
xdebug.collect_return = 1
xdebug.output_dir = /home/vladp/dev/sites/gt-vladp-dev1/var/trace
xdebug.start_with_request=trigger

xdebug.trace_format = 1 
xdebug.trace_options = 0 
xdebug.trace_output_name =gtrace.%t.%R
xdebug.var_display_max_data = -1 

xdebug.dump_undefined = true 
xdebug.dump.COOKIE = *
xdebug.dump.FILES = *
xdebug.dump.GET = *
xdebug.dump.POST = *
xdebug.dump.REQUEST= *
xdebug.dump.SERVER = *
xdebug.dump.SESSION = *
xdebug.show_error_trace = 1 

xdebug.show_local_vars = 1 

xdebug.var_display_max_depth = -1 
xdebug.var_display_max_children = 10
xdebug.var_display_max_data = 1024
```

Xdebug logfile (from setting `xdebug.log` in php.ini):
VS Code extension logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php
$containerBuilder = new ContainerBuilder();
// Set up settings
$containerBuilder->addDefinitions(__DIR__ . '/../config/admin_container.php');
// Build PHP-DI Container instance
$container = $containerBuilder->build();  // this one makes the problem

```

**Comment by zobo** [comment]
Hi! This is indeed interesting. Can you try the process again with “log”: true so that all traffic is logged into Debug Console in VSCode. Attach that here please. 

When I think about how this could happen. Some sort of execution limit would need to apply. Perhaps the Xdebug log could show what happened. 

Let me know if you have problems creating the log.

**Comment by palansher** [comment]
> Let me know if you have problems creating the log.

Good evening!

Here is the log file for 1st scenario (disconnection after 1-3 sec):
[debug_console.txt](https://github.com/xdebug/vscode-php-debug/files/6704739/debug_console.txt)

Really hope for your help!

Also, I sometimes see a Notice in my general app log, but I think it is not connected to the main problem, because it generated different time:

```
ut started at /home/vladp/dev/sites/gt-vladp-dev1/public_html/admin.php:584)  on line 594 in file /home/vladp/dev/sites/gt-vladp-dev1/public_html/admin.php  
[2021-06-23T08:12:11.680012+03:00] 60d2c2ab6b6f1.NOTICE: ErrorException Code 0 level 8 E_NOTICE Undefined variable: arResponse  on line 1 in file xdebug://debug-eval  
[2021-06-23T08:12:11.681141+03:00] 60d2c2ab6b6f1.NOTICE: ErrorException Code 0 level 8 E_NOTICE Undefined variable: error  on line 1 in file xdebug://debug-eval  
[2021-06-23T08:14:34.685356+03:00] 60d2c33a667c9.NOTICE: ErrorException Code 0 level 8 E_NOTICE Undefined variable: arResponse  on line 1 in file xdebug://debug-eval  
[2021-06-23T08:14:34.689319+03:00] 60d2c33a667c9.NOTICE: ErrorException Code 0 level 8 E_NOTICE Undefined variable: error  on line 1 in file xdebug://debug-eval  


```

**Comment by zobo** [comment]
Hi! There is definitely something strange. When the debugger requests the local variables there is no response from Xdebug. I’ll try to reproduce the issue, but I’m currently on vacation. 
can you also attach the /var/log/xdebug.log file? Maybe something else is in there… 

Thanks!

**Comment by zobo** [comment]
Hi!
I managed to reproduce the issue locally. The problem comes from `max_depth: 200` setting. The built container contains a lot of recursion, causing the variable resolver to drill very deep and generate an enormous XML response.

There is no need for the `max_depth` setting as the adapter is capable to drill down and request the data incrementally.

Here is an image that shows the recursion:

![image](https://user-images.githubusercontent.com/2456026/123302376-f3bd4480-d51c-11eb-873c-8dcacfd98904.png)

I will also look if the Debug Adapter Protocol has any special support for variable recursion.

**Comment by palansher** [comment]
Good day!

Wow, you did it, you found it !!! 
Now I'm saved! :)

>`max_depth: 200`

I commented it out and now the Ext. works as expected! 
/var/log/xdebug.log is unusually empty as never been before,   nothing to attach :)

> There is no need for the `max_depth` setting as the adapter is capable to drill down and request the data incrementally.

I did by the advice of another dev in https://github.com/xdebug about half a year before. The reason was that huge variable arrays like $_POST was cut and I could not see all details in step debug.
Do you think I will not meet such issues (big vars display ) in the future?


> ![image](https://user-images.githubusercontent.com/2456026/123302376-f3bd4480-d51c-11eb-873c-8dcacfd98904.png)
> Here is an image that shows the recursion:

Interesting, how did you get such an informative log?

> I will also look if the Debug Adapter Protocol has any special support for variable recursion.

It would be great if you pay attention to this!

Damjan , thank you so much for your extremely valuable help during your vacation!

Hope I can visit Kobarid in Slovenia again for paragliding and also buy you a beer in Ljubljana!

**Comment by zobo** [comment]
> I did by your advice in #538 . The reason was that huge variable arrays like $_POST was cut and I could not see all details in step debug.
> Do you think I will not meet such issues (big vars display ) in the future?

Oh darn, I did not think this will come back to bite me :D

There are three options there: `max_data`, `max_children` and `max_depth`. Their in-depth explanation can be found here https://xdebug.org/docs/dbgp#feature-names but a very short explanation would be:

#538 would require only `max_children`. I'm working on solving that problem as well.

`max_depth` should not be needed, as each depth can be requested incrementally.

The plan is there will not be a need for any of them and that the plugin will handle this all on its own.

> Interesting, how (which tool) did you get such an informative log?

That's just the screenshot of the variable pane from VScode after I removed `max_depth`.

> Damjan , thank you so much for your extremely valuable help during your vacation!
> 
> Hope I can visit Kobarid in Slovenia again for paragliding and also buy you some beer/cookies in Ljubljana! :)

That's great to hear people heard of and visited our small country! Don't hesitate to ping me if you are anywhere near.
