### ISSUE TITLE
Works, but extremely slow performance on Windows WSL2-Ubuntu + docker

### ISSUE THREAD

**Issue by mkarulin** [xdebug/vscode-php-debug#605]
Hi.
I recently moved from PHPstorm to vscode and everything is working apart from the extreme slowness of php debuging in vscode compared to PHPStorm. 
My development stack consists of Windows 10 vscode and WSL2-Ubuntu with Docker.
PHP and Xdebug are installed on docker container from the DDEV team. Files are on the WSL2 Ubuntu filesystem.
The debugger it self works and i can browse the variables, but the time between steps is aroun 10-30 seconds.
I have phpstorm installed on the same machine, with identical setup, and its debugger is quick as a bullet.

Has anyone have had similar experience or have found a solution?
Thank you for your time.

PHP version: 7.4.20
Xdebug version: v3.0.4
VS Code extension version: 1.14.0

Your launch.json:
`{
   "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/var/www/html": "${workspaceRoot}"
            },
            "xdebugSettings":  {
                "max_depth": 9
            },
            "hostname": "localhost"
        }
    ]
}`

**Comment by zobo** [comment]
This is really strange behavior. I have not yet seen something like that. If you enable adapter logging (`launch.json` `log: true`) do you see when such delays happen? I know the log does not yet add timestamps so I could not see it...

Does this happen with every script, or do you perhaps have some particularly large stack? I see you have `max_depth` set to 9. This should not be needed, as the plugin fetches nested variables on request. Remove that and try again.

Best,
Damjan

**Comment by zobo** [comment]
No feedback, closing. Please reopen if this is still an issue for you. Provide Debug Console logs and xdebug_info() output.
