### ISSUE TITLE
After 1.57.0 version, the extension PHP Debug is broken

### ISSUE THREAD

**Issue by jjasoncool** [xdebug/vscode-php-debug#607]
PHP version:8.0
Xdebug version:3.0.4
VS Code extension version:1.16.1

Your launch.json:
```json
"launch": {
    "version": "0.2.0",
    "configurations": [{
          "name": "Listen for XDebug",
          "type": "php",
          "request": "launch",
          "port": 9003,
          "xdebugSettings": {
              "max_children" : 50,
              "max_data": 0,
              "max_depth" : 3
          },
          "pathMappings": {
              "/var/www/html/": "${workspaceRoot}"
          }
    }]
}
```
Xdebug php.ini config:.
```conf
zend_extension=xdebug
xdebug.mode=debug
xdebug.start_with_request = yes
xdebug.discover_client_host = true
xdebug.client_port = 9003
xdebug.log=/tmp/xdebug.log
```

Xdebug logfile (from setting `xdebug.log` in php.ini):NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.55.13:9003 (through xdebug.client_host/xdebug.client_port) :-(

VS Code extension logfile (from setting `"log": true` in launch.json):

please ref
https://github.com/microsoft/vscode/issues/128310

**Comment by zobo** [comment]
I believe you are mentioning vscode remote ssh in your original issue. Have you tried this yet? https://github.com/xdebug/vscode-php-debug/issues/601#issuecomment-866467459

**Comment by jjasoncool** [comment]
> 
> 
> I believe you are mentioning vscode remote ssh in your original issue. Have you tried this yet? [#601 (comment)](https://github.com/xdebug/vscode-php-debug/issues/601#issuecomment-866467459)

Big Thanks.
