### ISSUE TITLE
Hit count breakpoints

### ISSUE THREAD

**Issue by felixfbecker** [xdebug/vscode-php-debug#61]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#debug-protocol-additions
https://xdebug.org/docs-dbgp.php#id1

**Comment by adriancuadrado** [comment]
@felixfbecker Any progress on this issue?

**Comment by adriancuadrado** [comment]
Sorry, didn't see this:

![image](https://user-images.githubusercontent.com/29214635/128242831-e9737a31-1579-4fda-a4ce-9a452457fd81.png)

However, it seems like that PR never got merged to master :(

**Comment by zobo** [comment]
I'll see if I can port it to current main. The breakpoint subsystem was heavily modified so I'll need to change the implementation a bit.

**Comment by zobo** [comment]
Implementation ready but waiting for some feedback: https://github.com/microsoft/vscode/issues/130904
