### ISSUE TITLE
php-fpm process with high CPU freezing computer

### ISSUE THREAD

**Issue by nboisteault** [xdebug/vscode-php-debug#614]
Hi,
I used `xdebugSettings` to watch my variables more deeply with the configuration above. I then watched my computer freezing while having a php-fpm with high CPU in my docker stack. If I remove some parameters everything works fine.
Maybe a warning should be added in README.md?
There is a warning here : https://xdebug.org/docs/all_settings#var_display_max_depth. Is there any link between `var_display_max_depth` and `max_depth`?

PHP version:7.4.21
Xdebug version:3.0.4
VS Code extension version:V1.16.1

Your launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "pathMappings": {
                "/srv/lzm/": "${workspaceFolder}/"
            },
            "port": 9000,
            "xdebugSettings": {
                "max_children": 999,
                "max_data": 2048,
                "max_depth": 999,
            }
        }
    ]
}
```
Xdebug php.ini config:
```
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.client_host=172.17.0.1
xdebug.client_port=9000
xdebug.discover_client_host=1
xdebug.start_with_request=yes
```

**Comment by zobo** [comment]
Indeed I see no reason why anyone would need to change `max_depth`. The variables are fetched incrementally. I'll add a note in the readme.

**Comment by nboisteault** [comment]
I modified those parameters without thinking twice and get no issue at first until I reached some part of my code freezing my computer.
Thanks for the note. Hope it will help someone.

**Comment by zobo** [comment]
Yes, the problem happens when you have recursive object references. There things get bad.

https://github.com/xdebug/vscode-php-debug/pull/615
