### ISSUE TITLE
Debugging won't start in 1.16.2

### ISSUE THREAD

**Issue by evs-xsarus** [xdebug/vscode-php-debug#624]
Clicking on 'play' does nothing, the debugger stops within a second.

Workaround: go back to v1.16.1

PHP version: n/a
Xdebug version: n/a
VS Code version: 1.58.2 Linux
VS Code extension version: 1.16.2

Your launch.json:
Xdebug php.ini config:

Xdebug logfile (from setting `xdebug.log` in php.ini):
```json
{
    "launch": {
        "configurations": [
            {
                "name": "Listen for XDebug",
                "type": "php",
                "request": "launch",
                "port": 9099,
                "pathMappings": {
                    "/sites": "/home/evs/sites"
                },
                "xdebugSettings": {
                    "max_children": 256,
                    "max_depth": 3
                }
            },
            {
                "name": "Listen for XDebug CLI",
                "type": "php",
                "request": "launch",
                "port": 9099,
                "pathMappings": {
                    "/site": "${workspaceFolder}"
                },
                "xdebugSettings": {
                    "max_children": 256,
                    "max_depth": 3
                }
            }
        ]
    }
}
VS Code extension logfile (from setting `"log": true` in launch.json):
Not available, debug won't start.

**Comment by samtarling** [comment]
I too am having this issue. On clicking the play button, the "debug toolbar" (whatever its called) pops up for ~1 second then disappears.

Have additionally tested with the testproject, launch.json as:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      //"debugServer": 4711, // Uncomment for debugging the adapter
      "name": "Listen for Xdebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "log": true
    },
    {
      //"debugServer": 4711, // Uncomment for debugging the adapter
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 0,
      "runtimeArgs": ["-dxdebug.start_with_request=yes"],
      "env": {
        "XDEBUG_MODE": "debug,develop",
        "XDEBUG_CONFIG": "client_port=${port}"
      }
    },
    {
      //"debugServer": 4711, // Uncomment for debugging the adapter
      "name": "Launch Built-in web server",
      "type": "php",
      "request": "launch",
      "runtimeArgs": [
        "-dxdebug.mode=debug",
        "-dxdebug.start_with_request=yes",
        "-dxdebug.client_port=${port}",
        "-S",
        "localhost:0"
      ],
      "program": "",
      "cwd": "${workspaceRoot}",
      "port": 0,
      "serverReadyAction": {
        "pattern": "Development Server \\(http://localhost:([0-9]+)\\) started",
        "uriFormat": "http://localhost:%s",
        "action": "openExternally"
      }
    }
  ]
}
```

**PHP version**
```
PHP 8.0.3 (cli) (built: Mar  2 2021 23:34:05) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

**VS Code version**
```
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

**VC Code extension version**
`v1.16.2`

Have set `xdebug.log=C:\tmp\xdebug_errors.log` but not getting any entries so unfortunately cannot provide a log file. Will continue to keep trying i/r/t getting some logs.

**Comment by zobo** [comment]
The "age old" dev dependency problem. I need to figure out how to run a GitHub actions test for this.

**Comment by zobo** [comment]
Thanks for reporting, should be out in a few minutes.

**Comment by samtarling** [comment]
> Thanks for reporting, should be out in a few minutes.

Just noting that this resolves the issue, many thanks!

**Comment by sinnayman** [comment]
Thank you for your quick fix guys, I kinda freaked out today when I started coding and realised the debugger didn't wanna :D

**Comment by RAFA3L** [comment]
> I too am having this issue. On clicking the play button, the "debug toolbar" (whatever its called) pops up for ~1 second then disappears.

I'm having this same issue, the green icon beside "Listen for XDebug" work fine, but the icon in the top-right toolbar start it just for a second.

**Comment by zobo** [comment]
Hi! The top right icon is "run this file". Can you open a fresh file, add `
``
<?php

xdebug_info()
```

to it  and see what happens? Maybe the php script runs, but it can't connect wit the debugger?

Best

**Comment by RAFA3L** [comment]
thanks @zobo, I understand, but maybe you tried to add some example in your post that was not included,

**Comment by RAFA3L** [comment]
I don't know if is the same, but adding "runtimeExecutable" with my php path make "Launch currently open script" works, but the top right icon doesn't. 

I've always used Listen for XDebug but recently noticed the icon at the top right, I don't remember if it's new.

**Comment by zobo** [comment]
Ok, this is a good hint.

The debug button on the right starts the debugging process without using the `launch.json` configuration. In the readme here is some explanation:

> Note: You can even debug a script without launch.json. If no folder is open, and the VS Code status bar is purple, pressing F5 will start the open script with Xdebug3 specific parameters. If the php executable is not in path, you can provide it with the setting `php.debug.executablePath`. For debugging to work, Xdebug must still be correctly installed.

So what is probably happening is that you have more than one PHP instances on your system and the debugger isn't using the right one. Try setting the mentioned setting in vscode.

**Comment by RAFA3L** [comment]
Thanks! you are right, adding `php.debug.executablePath` now is keeping the debug running in the file, but don't stop in any breakpoint, or maybe I don't understand the proper functionality, I can't find any information about this icon. What is the difference with "Launch currently open script"?

I have Xdebug v2.9.2

**Comment by zobo** [comment]
Yes. It's roughly the same thing as "Launch currently open script", but works by creating the config on the fly, and can be used when VSCode does not have an open folder.

I have written about it here https://damjan.cvetko.org/blog/2021-10-15-vscode-php-debug-release-september-2021/ but it would probably need some extra explanation.

There's sadly not way to trigger a `log: true` in the no-folder scenario...

But since you mentioned Xdebug 2.9.2.: The no-folder is currently expecting Xdebug 3. So it listen on 9003 port and does not pass Xdebug v2 specific php defines, but rather v3 specific php command line arguments and environment...

**Comment by RAFA3L** [comment]
Thanks, very helpful your explanation and the post, maybe could help changing the note in the readme to a subtitle like "VS Code without configuration" and with the link to your post.

I really pay attention to this icon after install the Reveal extension, witch show an icon in the same toolbar. As I understand the idea is to create an ease onboarding for new users and debug simple files quickly, but in my case it is very rare to open a PHP file outside the project.

I don't know if is possible, but would be nice something like the same play icon in the left side toolbar by default behave with this new mode when there is no config (and selectable in the dropdown when config exist), maybe the new icon is not necessary.

**Comment by zobo** [comment]
Hey. I did not think this was going to be a problem, but now I am seriously considering hiding the icon while in blue (folder) mode...
I should also add VSCode settings to set parameters like, `log`, `port` and or `Xdebug version`....
Or I should add some logic to detect if Xdbeug is properly installed and configured... Not easy...

**Comment by RAFA3L** [comment]
> but now I am seriously considering hiding the icon while in blue (folder) mode...

Excellent! much better idea, for now I hide it with the Customize UI extension.
