### ISSUE TITLE
Add support for DBGp "enum" facet, to support PHP 8.1 better

### ISSUE THREAD

**Issue by derickr** [xdebug/vscode-php-debug#628]
Xdebug 3.1 will add an `enum` facet to PHP 8.1's enum classes:

```
<property name="$eur" fullname="$eur" type="object" facet="enum" classname="Currency" children="1" numchildren="2" page="0" pagesize="32">
        <property name="name" fullname="$eur-&gt;name" facet="public" type="string" size="3" encoding="base64"><![CDATA[RVVS]]></property>
        <property name="value" fullname="$eur-&gt;value" facet="public" type="string" size="3" encoding="base64"><![CDATA[4oKs]]></property>
</property>
```

PHP 8.1 enums are implemented as classes, which one or two properties. The `name` is always present, but `value` is not. I would suggest that the plugin at least marks objects that also have the `enum` facet as such. These two properties are also `readonly` (see #627).

**Comment by zobo** [comment]
I have added basic facet support in #655.

The provided XML is a bit outdated, this is a more recent one (ignore the extended properties, not the point):
```xml
<property name="$eur" fullname="$eur" type="object" facet="enum" classname="Currency" children="1" numchildren="2" page="0" pagesize="32">
  <property name="name" fullname="$eur-&gt;name" facet="public readonly" type="string" size="3" encoding="base64"><![CDATA[RVVS]]></property>
  <property facet="public readonly" type="string" size="3">
    <name encoding="base64"><![CDATA[dmFsdWU=]]></name>
    <fullname encoding="base64"><![CDATA[JGV1ci0+dmFsdWU=]]></fullname>
    <value encoding="base64"><![CDATA[4oKs]]></value>
  </property>
</property>
```

Here each property already has the `readonly` facet witch makes things easier. `readOnly` is the only [attribute](https://microsoft.github.io/debug-adapter-protocol/specification#Types_VariablePresentationHint)  VS Code uses as far as I understand, and even that does not yet matter for this extension until I implement #46.
