### ISSUE TITLE
Does this extension provide "Go to the reference" functionality?

### ISSUE THREAD

**Issue by len0xx** [xdebug/vscode-php-debug#644]
I was using the extension called "**PHP IntelliSense**" from this author. And now after switching from _Windows 10_ to _Debian 11_ I found out that the extension I got so much used to is gone from the marketplace. I decided to install the "**PHP Debug**" and realized that I can no longer go to the reference of the function by clicking it while pressing Ctrl.

Does this extension have this kind of functionality or is it just gone?
And if it's gone then what's the alternative that I can use?

**Comment by zobo** [comment]
No. This extension is a Debug Adapter (Protocol) where as the other is a Language Server (Protocol). I reached out to the original author and I'll see if something can be done about republishing that extension.
