### ISSUE TITLE
VS passing old xdebug parameters,  Setting renamed... 

### ISSUE THREAD

**Issue by blaze-Youssef** [xdebug/vscode-php-debug#646]
I have an issue whe debugging in VS code, The debugging works fine, but every time I run it, a warning shows in the top of DEBUG CONSOLE :
Xdebug: [Config] The setting 'xdebug.remote_autostart' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)

Xdebug: [Config] The setting 'xdebug.remote_host' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_host (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_mode' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_mode (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_port' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_port (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)

I Think I have everthing good in php ini. Any suggestions.

PHP version: 8.0.6
Xdebug version: 3.0.4
VS Code extension version: latest

Your launch.json: 
  
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "XDEBUG_CONFIG": "client_host=192.168.42.34 log=/tmp/xdebug.log",
            "runtimeArgs": [
                "-dxdebug.start_with_request=yes"
         

Xdebug php.ini config:

zend_extension = "C:\php8\ext\php_xdebug-3.0.4-8.0-vs16-nts-x86_64.dll"
xdebug.mode=debug
xdebug.start_with_request = yes
xdebug.idekey = VSCODE
xdebug.log_level = 0
xdebug.log = "%sprogdir%/userdata/temp/xdebug/log.txt"
xdebug.client_host=127.0.0.1
xdebug.client_port=9003

**Comment by zobo** [comment]
I would guess the these configs come from somewhere else. I suggest you add a `phpinfo()` to your script and see what `.ini` files are loaded and search in those. Maybe the new `xdebug_info()` can also help, but I'm not sure.

**Comment by zobo** [comment]
It's not obvious where the setting are coming from with provided information. Either the old settings are in a .ini file, environment, or you are using a different launch.json section not shown here. Will close, comment if you still need help.
