### ISSUE TITLE
vscode-php-debug isn't work in vim via vimspector plugin

### ISSUE THREAD

**Issue by hadji-developer** [xdebug/vscode-php-debug#650]
PHP version: 7.4.21
Xdebug version:3.2
VS Code extension version:1.17

Vim: 8.2

This extension work normally in vscode, but isn't work in vim via vimspector plugin. I like programming in vim the most, so if you have the opportunity - could you please check the php7.4.21 - vim8.2 - vimspector - vscode-php-debug1.17 bundle. I really don't want to switch to vscode, vim is much better. Thanks.

**Comment by hadji-developer** [comment]
This issue can help for someone, who use this adapter with vim - I forgot install node.js. Without node.js this adapter doesn't work.

**Comment by zobo** [comment]
Great to hear it still works well with vim! Let me know if there will be any issues.

**Comment by hadji-developer** [comment]
Thanks for your contributions and your work. It's only one way to debug php code in vim - vimspector + vscode-php-debug. No any STABLE php debuging plugins in vim. One yet thanks for you. If I will find any problems in bundle vimspector + vscode-php-debug - I will open issue in this repository. Thanks a lot.
