### ISSUE TITLE
Breakpoints not working, but xdebug_break() works

### ISSUE THREAD

**Issue by robson-alcantara** [xdebug/vscode-php-debug#652]
PHP version: 8.0.0
Xdebug version: 3.0.4
VS Code extension version: 1.16.3

Your launch.json:
[launch.json.txt](https://github.com/xdebug/vscode-php-debug/files/7155838/launch.json.txt)

Xdebug php.ini config:

[XDebug]
zend_extension=C:\xampp_\php\ext\php_xdebug.dll
xdebug.remote_autostart = 1
xdebug.remote_enable = 1
xdebug.default_enable = 1
xdebug.mode=debug

Xdebug logfile (from setting `xdebug.log` in php.ini):
[xdebug.log](https://github.com/xdebug/vscode-php-debug/files/7155918/xdebug.log)

VS Code extension logfile (from setting `"log": true` in launch.json):
[vs_code_part_log.txt](https://github.com/xdebug/vscode-php-debug/files/7155942/vs_code_part_log.txt)

Code snippet to reproduce:

```php

```

**Comment by zobo** [comment]
Hi. The vs_code_part_log.txt has only 3 lines in there, not much to go on. And the breakpoint ID is not in the other log either. And I cannot find an instance of execution break to see how Xdebug sees the files either. Could you get me a full log from VS Code debug panel

**Comment by gentig** [comment]
Mine stopped working altogether. It doesn't even stop on stopOnEntry.

**Comment by robson-alcantara** [comment]
Here are the complete logs

[vs_code_log.txt](https://github.com/xdebug/vscode-php-debug/files/7177323/vs_code_log.txt)
[xdebug.log](https://github.com/xdebug/vscode-php-debug/files/7177324/xdebug.log)

**Comment by zobo** [comment]
Hi. Thanks for the logs. They do show some strange things, but it would help if I could also see the file.

The log shows:
breakpoints on lines 65, 69.

First execution line is 70 (stopOnentry).

Break after continue, again line 70. This is strange.

On what line is xdebug_break() ?

Ideally, if possible, clean up the file of any sensitive content and attach it here.

Best,
Damjan

**Comment by robson-alcantara** [comment]
Yes, in the line 70 has a xdebug_break(); command. Any more?

**Comment by robson-alcantara** [comment]
The file has copyrights and unfortunately it won't be possible to publish

**Comment by zobo** [comment]
Hi. I completely understand.

Do you think you could try to create a simple file that also demonstrates such behavior? 

My question about your current source would be: if line 70 is the first line to be executed, and xdebug_break is on it whats is in all the lines before?
You define two breakpoints. Are they inside functions? Classes?

Best!

**Comment by robson-alcantara** [comment]
Here is the requested scenario

![image](https://user-images.githubusercontent.com/20538912/133773577-105ba13d-c304-405f-b52b-032e43b524d6.png)
[vs_code_log.txt](https://github.com/xdebug/vscode-php-debug/files/7185141/vs_code_log.txt)

xdebug.log is empty

**Comment by marlboroman3** [comment]
I am having the same issue, suddenly I can't make the debugger stop on any breakpoints.  One day it worked, the next, nothing.  So, a bit weird.  Perhaps VSCode updated itself in the interim, but php.ini and launch.json haven't changed for months.

**Comment by zobo** [comment]
Hi @marlboroman3. 
> I am having the same issue, suddenly I can't make the debugger stop on any breakpoints. One day it worked, the next, nothing. So, a bit weird. Perhaps VSCode updated itself in the interim, but php.ini and launch.json haven't changed for months.
Can you also provide some info about your setup?:
- VS Code version
- php-debug extension version
- Xdebug version
- PHP version
- Xdebug related php.ini directives
- attach launch.json file that you are using
- what configuration is selected in RUN AND DEBUG
- describe how you run php:
   - is it a script executed on the same system as VS Code
   - is it inside WSL
   - is it inside Docker or other container
   - is it on a remote server and you are using Samba network file system to access the files
   - is it on a remote server and you are using VS Code Remote
   - other combinations?
- if possible, state the path to your workspace and if in a remote/container the path where php files are
- make a small php file to reproduce the issue and attach this file so we can try to reproduce the issue ourselves,
- add `"log":true` to your launch.json configuration
- add `xdebug_info()` to your code (only Xdebug 3) and attach a screen show of the output
- attach the whole output of DEBUG CONSOLE (right click, Copy All) after reproducing the issue.

It's best if you open up a new issue with all this information attached. Let me know if it's clear what I need, and I will try to improve the issue template to provide users with a better starting point.

**Comment by zobo** [comment]
Hi @robson-alcantara , sorry for not getting back earlier. See the previous post if there is any more info you can provide. Since there was no Xdebug/DBGp connection in your case, please run a `xdebug_info()` and attach a screenshot of that if it helps us determine the source of the issue.

**Comment by robson-alcantara** [comment]
Follow

![image](https://user-images.githubusercontent.com/20538912/134233215-21a9c3f9-3eb3-439d-b33f-b77f3e61cc56.png)

![image](https://user-images.githubusercontent.com/20538912/134233325-6c5f4085-e67a-4d06-ad69-b60c0980e126.png)

![image](https://user-images.githubusercontent.com/20538912/134233401-e08d2ead-f024-46bf-b9e0-2af2dc4360d1.png)

![image](https://user-images.githubusercontent.com/20538912/134233474-64ce6d8d-ac6b-43ef-9d4f-bb2f5394146b.png)

**Comment by marlboroman3** [comment]
New issue #659 opened.

**Comment by zobo** [comment]
This is quite old. Please open a new one if this is still the case.
