### ISSUE TITLE
Debugging stopped working with specific folder/workspace

### ISSUE THREAD

**Issue by Balkoth** [xdebug/vscode-php-debug#662]
PHP version: 7.4.14
Xdebug version: 3.0.4
VS Code extension version: 1.18.0

Your launch.json:
{
	"name": "Listen for XDebug",
	"type": "php",
	"request": "launch",
	"xdebugSettings": {
		"max_data": -1
	}
}

Xdebug php.ini config:
xdebug.mode = debug
xdebug.start_with_request = yes

I have a folder where an initial breakpoint is hit, but F5 or F10 just breaks any exectution. If i copy the folder and work from here everything just works again as expected. I am a little clueless what is going on here. I am guessing that vscode or the extension cache something somewhere which has gone stale. Restarting vscode or the webserver did not help either.

**Comment by zobo** [comment]
Interesting. Can you try to add log:true and attach what is in Debug Console? Also, I'm not sure if max_data is allowed to be -1, but I can't check right now. Try to set it to 1024 or similar.

**Comment by zobo** [comment]
I'm going to close the issue since we don't have anything to go on. If it happens again, please reopen and let's figure it out then.
