### ISSUE TITLE
Launching local php executable for remote projects

### ISSUE THREAD

**Issue by t-schroeder** [xdebug/vscode-php-debug#680]
# Details

PHP version: 7.3.31
Xdebug version: 2.9.8
VS Code extension version: 1.21.0

Your launch.json:

<details>
  <summary>Click me</summary>
  
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}"
        }
    ]
}
```
</details>

Xdebug php.ini config:

<details>
  <summary>Click me</summary>
  
```ini
zend_extension=xdebug.so
xdebug.collect_params = 1
xdebug.idekey = vscode-xdebug
xdebug.max_nesting_level = 1000
xdebug.profiler_append = 1
xdebug.profiler_enable_trigger = 1
xdebug.profiler_enable_trigger_value = "bla"
xdebug.profiler_output_dir = /home/php-profiling
xdebug.remote_autostart = true
xdebug.remote_enable = true
xdebug.trace_enable_trigger = true
xdebug.trace_enable_trigger_value = "blub"
xdebug.trace_format = 1
xdebug.trace_options = 1
xdebug.trace_output_dir = /var/www/trace
xdebug.var_display_max_depth = 7
```
</details>

Xdebug logfile (from setting `xdebug.log` in php.ini): empty
VS Code extension logfile (from setting `"log": true` in launch.json):

<details>
  <summary>Click me</summary>

```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true
}
<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }
<- outputEvent
OutputEvent {
  seq: 0,
  type: 'event',
  event: 'output',
  body: {
    category: 'console',
    output: 'Error: spawn C:\\php-7.3.9-nts-Win32-VC15-x64\\php.exe ENOENT\n' +
      '    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)\n' +
      '    at onErrorNT (internal/child_process.js:465:16)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:80:21) {\n' +
      '  errno: -2,\n' +
      "  code: 'ENOENT',\n" +
      "  syscall: 'spawn C:\\\\php-7.3.9-nts-Win32-VC15-x64\\\\php.exe',\n" +
      "  path: 'C:\\\\php-7.3.9-nts-Win32-VC15-x64\\\\php.exe',\n" +
      "  spawnargs: [ '/home/st-admin/moodle-webservice-client/get_contents.php' ]\n" +
      '}\n'
  }
}
Error: spawn C:\php-7.3.9-nts-Win32-VC15-x64\php.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn C:\\php-7.3.9-nts-Win32-VC15-x64\\php.exe',
  path: 'C:\\php-7.3.9-nts-Win32-VC15-x64\\php.exe',
  spawnargs: [ '/home/st-admin/moodle-webservice-client/get_contents.php' ]
}
-> setFunctionBreakpointsRequest
{
  command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 3
}
<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] }
}
-> setExceptionBreakpointsRequest
{
  command: 'setExceptionBreakpoints',
  arguments: { filters: [] },
  type: 'request',
  seq: 4
}
<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 4,
  command: 'setExceptionBreakpoints',
  success: true,
  body: { breakpoints: [] }
}
-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 5 }
<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 5,
  command: 'configurationDone',
  success: true
}
-> threadsRequest
{ command: 'threads', type: 'request', seq: 6 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 6,
  command: 'threads',
  success: true,
  body: { threads: [] }
}
```
</details>

Code snippet to reproduce:

```php
<?php
echo "hello";
```

# Description

I'm running vscode on a Windows 10 machine connected via "Remote - SSH" extension to a CentOS 7 machine. Since updating "PHP Debug" extension to version 1.20 it always launches the local php binary to execute remote php scripts. That gives me this error:

```
Error: spawn C:\php-7.3.9-nts-Win32-VC15-x64\php.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn C:\\php-7.3.9-nts-Win32-VC15-x64\\php.exe',
  path: 'C:\\php-7.3.9-nts-Win32-VC15-x64\\php.exe',
  spawnargs: [ '/home/st-admin/moodle-webservice-client/get_contents.php' ]
}
```

With version 1.19 the extension uses the remote php binary when I have a remote folder opened and tell it to execute a php script in there.

# Workarounds

Either:

- go back to version 1.19 or
- put `"php.executablePath": "/usr/bin/php"` in the settings.json for the Remote.

**Comment by nickchomey** [comment]
I believe I'm getting errors related to this as well. I cannot use PHP Debug and PHP Intellisense at the same time - they have a conflict with phpexecutable. It was driving me insane with my Laragon-based site stalling out repeatedly when I used xdebug. 

Xdebug is my priority, but I NEED Intellisense too!

I'm happy to help debug anything if necessary.

https://user-images.githubusercontent.com/88559987/138384496-0deb861b-2495-4914-a225-6d4762caec75.mp4

**Comment by zobo** [comment]
Hi @nickchomey.

That is correct, they do have a conflict in this setting. I choose this setting but then later re-published PHP IntelliSense and just then realized that this causes a conflict.

However, this is just a warning and they should still both work (at least this is my experience here).

Do you need to use different PHP versions? Can you tell me how it does not work? Is IntelliSense reporting any errors?

Also, I'm not sure how both "PHP Intelephense" and "PHP IntelliSense" work together, since they both provide a language server...

**Comment by zobo** [comment]
I just started my day and can work on this after work.
I do not have experience with Laragon...

After installing 1.19 did the problems also stop?

I think Intelephense also provides all of that, but you need to pay for it. PHP IntellIsense also provides definition lookups and jump-to. I'd suggest trying to disable one of them.

It's really strange that this things would conflict with each other... Can you check under OUTPUT / PHP Language Server if there are any errors?

![image](https://user-images.githubusercontent.com/2456026/138394223-35485696-a6fa-4e79-bc0f-397818b201f1.png)

When your page stop/stall is the debugger active? If you add  `"log": true` to your launch configuration, does it show anything?

You are probably using `Listen for Xdebug`? And there that setting should not have any effect...

**Comment by zobo** [comment]
I'll close this as the resolving of `executablePath` changed in #685.
