### ISSUE TITLE
The debugger stops after the breakpoint

### ISSUE THREAD

**Issue by BigTaur** [xdebug/vscode-php-debug#692]
php: 7.4.26 nts vc15 x64
Xdebug version: 3.1.1-7.4-vc15-nts-x86_64
VS Code extension version: v1.22.0
Your launch.json:
        {
            "name": "Launch currently open script php",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "stopOnEntry":false,
            "env": { "XDEBUG_TRIGGER": "1" } // Added so it works
        }
Xdebug php.ini config:
[xdebug]
zend_extension='C:\php\ext\php_xdebug-3.1.1-7.4-vc15-nts-x86_64.dll'
xdebug.mode=debug
xdebug.start_with_request = yes
xdebug.remote_handler=dbgp
xdebug.log = "C:\php\xdebug.log"
xdebug.client_host=localhost
xdebug.client_port=9000

Xdebug logfile (from setting `xdebug.log` in php.ini):

[20084] [Step Debug] <- step_over -i 23
[20084] [Step Debug] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="step_over" transaction_id="23" status="stopping" reason="ok"></response>

[20084] [Step Debug] <- stop -i 24
[20084] [Step Debug] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="stop" transaction_id="24" status="stopped" reason="ok"></response>

[xdebug.log](https://github.com/xdebug/vscode-php-debug/files/7563587/xdebug.log)

VS Code extension logfile (from setting `"log": true` in launch.json):
Code snippet to reproduce:

```php
echo "Hello world!!!";
echo 'PHP version: ' . phpversion(); //breakpoint
phpinfo();
```
Stops at a breakpoint. When trying to continue debugging. The program stops working.

![изображение_2021-11-18_174321](https://user-images.githubusercontent.com/66425400/142436945-0bd85d74-1f5f-4843-9dbc-6f09d08fd9d6.png)
![php1](https://user-images.githubusercontent.com/66425400/142437643-448849f8-abcb-48d7-a463-7393fabb94a6.png)
![изображение_2021-11-18_174711](https://user-images.githubusercontent.com/66425400/142437662-69e9651f-ec36-4f6e-a7e6-c81befcb34b4.png)

In this example, phpinfo(); is not executed

**Comment by zobo** [comment]
Hi! Sorry about the late reply. I looked at the logs you provided and see there are some watches defined that get evaluated. This is a know Xdebug issue in various version combinations. I see that the reserved word "namespace" in one of you watches is causing the issue... There is not much I can do. I can tell you that in PHP 8.0.12/Xdebug 3.1.1 the issue is not present and the code does not stop.

https://bugs.xdebug.org/view.php?id=1993
