### ISSUE TITLE
While debugging, hover tooltip takes 3 seconds to show

### ISSUE THREAD

**Issue by GeeZuZz** [xdebug/vscode-php-debug#739]
PHP version: 8.0.6
Xdebug version: v3.0.4
VS Code extension version: v1.23.0

- Using PHP and xDebug
- Put a breakpoint
- Press F5 to enter debugging
- Wait for VS code to break at the breakpoint
- While stopped at a breakpoint. hover over a variable in the code
- I have to wait an excessively long time (about **3 seconds**) before the tooltip with variable info shows up.

I expect the hover tooltip show up more quickly, or behave according to the setting "Editor › Hover: Delay". Changing this setting does not make any difference.

**Important:** This bug has been introduced in a release the past few months. I have two identically setup PCs, where one hasn't been updated in a while. While trying to confirm the bug, I tested it on the old PC, but there I couldn't recreate it (tooltip showed up quickly, like expected). Then I updated VS Code to latest version on that machine also, and now that PC also have the issue with delayed tooltip (3 seconds).
I don't know how to see which version it had before I updated.

**Comment by zobo** [comment]
Hi. Indeed there were some changes in this area. You can install an older version of the plugin in the Extensions side bar. Can you try it with an older version. 
And please collect a debug log from debug console.

**Comment by GeeZuZz** [comment]
I tried installing the previous version, but it doesn't work, it just uninstalls it when I select that version. No errors.

**Comment by zobo** [comment]
Ah yes. We migrated the extension to a new publisher, so thats probably not possible. Can you try to produce the log instead? Add `log: true` to your launch.json an then attach the contents of the Debug Console.

**Comment by GeeZuZz** [comment]
I cleared the log before hover, and this is what shows up in the log when I hover. $database is just a normal variable in my code. 

Here is the console output after hovering two different variables:

`-> evaluateRequest
{
  command: 'evaluate',
  arguments: { expression: '$test', frameId: 1, context: 'hover' },
  type: 'request',
  seq: 17
}
xd(1) <- context_names -i 12 -d 0
xd(1) -> <?xml version="1.0" encoding="iso-8859-1"?><response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="12"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context><context name="User defined constants" id="2"></context></response>
xd(1) <- property_get -i 13 -d 0 -c 0 -n "$test"
xd(1) -> <?xml version="1.0" encoding="iso-8859-1"?><response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="property_get" transaction_id="13"><property name="$test" fullname="$test" type="string" size="4" encoding="base64"><![CDATA[dGVzdA==]]></property></response>
<- evaluateResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 17,
  command: 'evaluate',
  success: true,
  body: { result: '"test"', variablesReference: 0 }
}
-> evaluateRequest
{
  command: 'evaluate',
  arguments: { expression: '$test2', frameId: 1, context: 'hover' },
  type: 'request',
  seq: 18
}
xd(1) <- context_names -i 14 -d 0
xd(1) -> <?xml version="1.0" encoding="iso-8859-1"?><response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="14"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context><context name="User defined constants" id="2"></context></response>
xd(1) <- property_get -i 15 -d 0 -c 0 -n "$test2"
xd(1) -> <?xml version="1.0" encoding="iso-8859-1"?><response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="property_get" transaction_id="15"><property name="$test2" fullname="$test2" type="string" size="5" encoding="base64"><![CDATA[dGVzdDI=]]></property></response>
<- evaluateResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 18,
  command: 'evaluate',
  success: true,
  body: { result: '"test2"', variablesReference: 0 }
}
`

**Comment by zobo** [comment]
There two have positive responses... Do they also take 3 seconds? Do they show up the same time the `evaluateResponse` is logged?

**Comment by GeeZuZz** [comment]
Yes, for both variables, it takes 3 seconds of hover, then the tooltip shows up, and the text appears in the log.
Nothing shows in the log when I start the hover - only when the tooltip shows up after 3 seconds of hovering.

**Comment by zobo** [comment]
Ok, so the delay could come in before hovering is triggered. Maybe in the extension https://code.visualstudio.com/api/references/vscode-api#EvaluatableExpression ...

I'll try to reproduce it here, but I have not yet seen a case. Could be a conflict with some other extension. Do you have any other PHP related extensions installed?

**Comment by GeeZuZz** [comment]
This is a bit strange - I somehow got it working on my main machine (at least, the hover time only takes 1 second now).
But on my other machine, the problem is still there, when breaking in the exact same file. That computer only has xdebug and "PHP Intelephense  v1.8.0" extensions installed.

I won't be able to troubleshoot any more today, but since I got it working again on one computer, this might be some configuration issue, so I guess you should wait for further info before you look more into it. Thanks for all help!

**Comment by zobo** [comment]
Quite old this task, I'll close it and if it had some recent development please make a new one.
