### ISSUE TITLE
[neovim] terminated event not send

### ISSUE THREAD

**Issue by JSteitz** [xdebug/vscode-php-debug#761]
PHP version: `7.4`
Xdebug version: `3.0.4`
VS Code extension version: `1.25.0`

The issue is described here: https://github.com/mfussenegger/nvim-dap/issues/469

In short: neovim dap does not get the `terminated` event from the debug adapter.

**Comment by zobo** [comment]
Hi. I'll research the issue. Thanks.

**Comment by zobo** [comment]
Will try to use Exited Event when the PHP debugee exits and Terminate Event after Disconnect Request.
