### ISSUE TITLE
Running current test case on remote server

### ISSUE THREAD

**Issue by 3rd3** [xdebug/vscode-php-debug#767]
I am wondering whether it is possible to run the currently opened test case on the remote server and then attach to Xdebug without using SSH for remote debugging? Perhaps via an URL that is called in the browser with the script name as argument as a "Listen for Xdebug launcher"?

**Comment by zobo** [comment]
What you can do is, if you have the code both on server and locally, run the script on the server (either from command line or from web server) and instruct Xdebug to connect to your PC. 
VSCode would in fact be showing your local code, but that should be the same as remote.
You would probably need to play with "pathMappings".

There's a bunch of moving parts here...

**Comment by AnrDaemon** [comment]
Just add a "terminal" SSH connection inside your workspace

```
    "terminal.integrated.profiles.windows": {
        "SSH@dev": {
            "args": [
                "-A",
                "-R",
                "9003:localhost:9003",
                "user@remote.host"
            ],
            "overrideName": true,
            "path": "C:\\Programs\\Cygwin\\bin\\ssh.exe",
            "color": "terminal.ansiCyan"
        }
    },
```

Then you will get both an actual terminal and xdebug connector. Then it's a matter of setting up correct tasks to run currently opened test case and connect to debugger.

**Comment by zobo** [comment]
Seems to be answered, closing.
