### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::9003

### ISSUE THREAD

**Issue by fabriciopolito** [xdebug/vscode-php-debug#799]
**PHP version:** 7.4
**Xdebug version:** 3.1.4 
**VS Code extension version:** v1.26.1

**Your launch.json:**

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "pathMappings": {
                "/var/www/html" : "${workspaceFolder}/www"
            }
        }
    ]
}
```

**Xdebug php.ini config:** 

```
zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=VSCODE
```

Xdebug logfile (from setting `xdebug.log` in php.ini):

**VS Code extension logfile (from setting `"log": true` in launch.json):**

```
Error: listen EADDRINUSE: address already in use :::9003
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at /home/fabricio/.vscode/extensions/xdebug.php-debug-1.26.1/out/phpDebug.js:375:24
    at new Promise (<anonymous>)
    at createServer (/home/fabricio/.vscode/extensions/xdebug.php-debug-1.26.1/out/phpDebug.js:234:36)
    at PhpDebugSession.launchRequest (/home/fabricio/.vscode/extensions/xdebug.php-debug-1.26.1/out/phpDebug.js:390:30)
    at PhpDebugSession.dispatchRequest (/home/fabricio/.vscode/extensions/xdebug.php-debug-1.26.1/node_modules/vscode-debugadapter/lib/debugSession.js:378:22)
    at PhpDebugSession.dispatchRequest (/home/fabricio/.vscode/extensions/xdebug.php-debug-1.26.1/out/phpDebug.js:489:15)
    at PhpDebugSession.handleMessage (/home/fabricio/.vscode/extensions/xdebug.php-debug-1.26.1/node_modules/vscode-debugadapter/lib/protocol.js:61:18) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 9003
}
```

There are no services using ports 9003, but the error persists.

![My OS info](https://user-images.githubusercontent.com/4513922/165666379-0c013d2b-c31e-42b8-a6e0-522f83a84598.png)
![scan report nmap](https://user-images.githubusercontent.com/4513922/165666380-45ee4dad-56e9-4c34-9b2a-aa6c86fbb5fd.png)

**Comment by fabriciopolito** [comment]
![vscode](https://user-images.githubusercontent.com/4513922/165668887-5921d37e-9361-4256-b9bc-6036c1749af2.png)

**Comment by zobo** [comment]
Hi. Looks like nmap did see an open port 9003? Try to look at the open ports `ss -apn | grep 9003` or perhaps `lsof | grep 9003`. 
Maybe a docker instance is using the port?

**Comment by fabriciopolito** [comment]
> Hi. Looks like nmap did see an open port 9003? Try to look at the open ports `ss -apn | grep 9003` or perhaps `lsof | grep 9003`. Maybe a docker instance is using the port?

Hello. Yes, that is the ports using by Docker containers and only opened if the container is on. The port 9003 is mapped to container port 9003.

![printscreen-terminal](https://user-images.githubusercontent.com/4513922/165743546-2f33715f-5c4e-46ca-a669-acb5a4538cb6.png)

![docker-compose](https://user-images.githubusercontent.com/4513922/165743856-27cfdcf3-e2ad-4534-af7e-fcf4e11ba18f.png)

**Comment by fabriciopolito** [comment]
> Hi. Looks like nmap did see an open port 9003? Try to look at the open ports `ss -apn | grep 9003` or perhaps `lsof | grep 9003`. Maybe a docker instance is using the port?

I tried to change the port, but the same message up.

![printscreen-terminal-2](https://user-images.githubusercontent.com/4513922/165748935-b2204d78-435d-4e71-897e-b7d4bd0974f0.png)

**Comment by zobo** [comment]
Just remove the whole line (under port in docker-compose). You do not need to forward TCP 9003 to your docker. The php+xdebug process inside your docker connects to your IDE that listens on 9003. Thats what xdebug.client_host tells php.

**Comment by fabriciopolito** [comment]
> Just remove the whole line (under port in docker-compose). You do not need to forward TCP 9003 to your docker. The php+xdebug process inside your docker connects to your IDE that listens on 9003. Thats what xdebug.client_host tells php.

Thanks my friend for your solution. Now it is working fine.

![xdebug-ok](https://user-images.githubusercontent.com/4513922/165753054-2148c418-4312-4d53-929d-6940c48a3c79.png)

**Comment by fabriciopolito** [comment]
I did as Zobo instructed and the problem was solved. Thanks for your support.

**Comment by zobo** [comment]
My pleasure. Thank you!

**Comment by spartanatreyu** [comment]
> Just remove the whole line (under port in docker-compose). You do not need to forward TCP 9003 to your docker. The php+xdebug process inside your docker connects to your IDE that listens on 9003. Thats what xdebug.client_host tells php.

I have no idea how I would have figured this all out without coming across this comment.

Every docker experience has told be that I need to open ports between the docker container and my machine to get anything to work across them.

But no.

For anyone reading this in the future from google, it turns out that you only need to open docker ports when something on your host machine needs to start a conversation with something inside your docker container.

But xdebug doesn't work like that. It's the thing that starts the conversation, so you need to set it up from xdebug's side. When anything inside a docker container tries to reach out to the URL `host.docker.internal` (e.g. xdebug sending a request to host.docker.internal:9003), it's sending a request up to your host machine.

So we want to set up vscode to listen for that port on the host machine, then we want xcode to send stuff up out of the container to the host machine on the host machine's port. Once the connection is made they can communicate back and forth.
