### ISSUE TITLE
Provide plugin on open-vsx.org

### ISSUE THREAD

**Issue by tm1000** [xdebug/vscode-php-debug#807]
See: https://github.com/VSCodium/vscodium/blob/master/DOCS.md?rgh-link-date=2021-01-28T08%3A31%3A00Z#extensions-marketplace

Once you provide the plugin here it can be used on https://github.com/coder/code-server

**Comment by zobo** [comment]
Yes, I plan to setup OpenVSX too, just didn't get around to it yet...

**Comment by filiptronicek** [comment]
Hi @zobo 👋, I'm excited that you're planning to publish to OpenVSX. I work on OpenVSX, so if you have any questions, feel free to ping me!

**Comment by filiptronicek** [comment]
Also, are you planning to publish https://github.com/zobo/vscode-php-intellisense as well? It would be great if you did so that we could have `xdebug.php-pack` on OpenVSX.

**Comment by zobo** [comment]
Hi! Yes, I will publish all 3. I know I need to claim the names first, so hopefully I'll get around. Does the process take a long time?

**Comment by filiptronicek** [comment]
@zobo I am glad you're planning to publish all of them. 

If nobody created the namespaces already, you actually don't need to claim and wait for them first, although it's really good to do it, you can publish the extensions and let the namespace be verified afterwards. The verification process can take just a couple of hours or max a couple of days, from what I have seen.

**Comment by JamesCullum** [comment]
Any update on this?

**Comment by zobo** [comment]
Ha! Just tried it again and it's published now. Will setup automatic publishing when possible.
