### ISSUE TITLE
Consider on-boarding to VS Code Sponsors

### ISSUE THREAD

**Issue by isidorn** [xdebug/vscode-php-debug#811]
Cao Damjane 👋 

Consider on-boarding to VS Code sponsorship. It is as easy as adding:
```json
"sponsor": {
  "url": "https://github.com/sponsors/zobo"
}
```

to your `package.json`

More details here
https://github.com/microsoft/vscode-discussions/discussions/14

**Comment by zobo** [comment]
Jo Izi!

This is great, will add with the next release I'll be doing soon. 

Thanks!

**Comment by isidorn** [comment]
Awesome!
Make sure to use latest vsce 2.9.1 when publishing your extension so this is respected. Thank you!

**Comment by zobo** [comment]
It works!
![image](https://user-images.githubusercontent.com/2456026/172999252-7d46f551-e12f-4ea6-8ae9-fa2e508ee1e3.png)

**Comment by isidorn** [comment]
Yeey - thanks for doing this 👏
