### ISSUE TITLE
Fatal error with any files or classes used. through namespace

### ISSUE THREAD

**Issue by sammerham** [xdebug/vscode-php-debug#838]
PHP version: 8.1.9
Xdebug version: v3.1.5
VS Code extension version: v1.28.0

Your launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 0,
            "runtimeArgs": [
                "-dxdebug.start_with_request=yes"
            ],
            "env": {
                "XDEBUG_MODE": "debug,develop",
                "XDEBUG_CONFIG": "client_port=${port}"
            }
        },
        {
            "name": "Launch Built-in web server",
            "type": "php",
            "request": "launch",
            "runtimeArgs": [
                "-dxdebug.mode=debug",
                "-dxdebug.start_with_request=yes",
                "-S",
                "localhost:0"
            ],
            "program": "",
            "cwd": "${workspaceRoot}",
            "port": 9003,
            "serverReadyAction": {
                "pattern": "Development Server \\(http://localhost:([0-9]+)\\) started",
                "uriFormat": "http://localhost:%s",
                "action": "openExternally"
            }
        }
    ]
}
Xdebug php.ini config:

zend_extension="/opt/homebrew/lib/php/pecl/20210902/xdebug.so"
xdebug.mode = debug, develop
xdebug.start_with_request = yes

Xdebug logfile (from setting `xdebug.log` in php.ini):
VS Code extension logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php

```

**Comment by zobo** [comment]
There is no info about the actual error. Please provide some additional info. Could it be you are trying to run a class file directly?

**Comment by zobo** [comment]
Closing old issue without needed info.
