### ISSUE TITLE
"Disconnect" action missing its icon

### ISSUE THREAD

**Issue by AnrDaemon** [xdebug/vscode-php-debug#841]
VS Code extension version: 1.8.2

The "Disconnect" dropdown action is missing its `codicon-debug-disconnect` icon.

**Comment by AnrDaemon** [comment]
![image](https://user-images.githubusercontent.com/6532485/192517264-14ae565a-1d8e-451d-b322-92bd07f65d51.png)

**Comment by zobo** [comment]
Looks like it this here:
![image](https://user-images.githubusercontent.com/2456026/192519972-ab8b3f9a-70f2-4449-a743-7e231c2e3163.png)
I don't think this has anything to do with the extension.

The arrow does not appear when debugging javascript. It's only availabe when the Capability supportTerminateDebuggee is present.

I honestly don't remember if it was there, but seems this is a issue for microosft/vscode

**Comment by AnrDaemon** [comment]
Oh, ok. I though it is your own code.
The action does not present when debugging JS in browser (FFdebug in my case), because it does not support terminating remote session, only disconnects.
I'll try to raise it in VS Code main.
