### ISSUE TITLE
watch栏目，只能显示一个层级的内容

### ISSUE THREAD

**Issue by wuqiyin** [xdebug/vscode-php-debug#844]
PHP version:7.4
Xdebug version:3.0

Your launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9901,
            "xdebugSettings": {// 不然变量的名称太长的话只能查看部分
                "max_data": -1,
                "max_children": 100000,
            }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 0,
            "runtimeArgs": [
                "-dxdebug.start_with_request=yes"
            ],
            "env": {
                "XDEBUG_MODE": "debug,develop",
                "XDEBUG_CONFIG": "client_port=${port}"
            }
        },
        {
            "name": "Launch Built-in web server",
            "type": "php",
            "request": "launch",
            "runtimeArgs": [
                "-dxdebug.mode=debug",
                "-dxdebug.start_with_request=yes",
                "-S",
                "localhost:0"
            ],
            "program": "",
            "cwd": "${workspaceRoot}",
            "port": 9901,
            "serverReadyAction": {
                "pattern": "Development Server \\(http://localhost:([0-9]+)\\) started",
                "uriFormat": "http://localhost:%s",
                "action": "openExternally"
            }
        }
    ]
}
Xdebug php.ini config:
[xdebug]
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.client_host=127.0.0.1
xdebug.client_port=9901
xdebug.start_with_request = yes

问题：
![image](https://user-images.githubusercontent.com/26370779/194697109-9087d7b6-8716-4f4e-89a1-19056bf03eb5.png)

**Comment by zobo** [comment]
Hi. I hope I understand your problem correctly.

A simple solution is to add `max_depth:10` under `xdebugSettings`, next to `max_data`.

I will improve this with next releases.

Let me know if this solves your problem.

**Comment by wuqiyin** [comment]
With this method, my problem has been solved, thank you!
```json
"xdebugSettings": {// 不然变量的名称太长的话只能查看部分
    "max_depth": 10,// 这个顺序一定要放在第一个，不然wath里看不到内部调试
    "max_data": -1,
    "max_children": 100000,
}
```

**Comment by zobo** [comment]
Great!
A related issue is #808. I plan to implement it so that dynamic child fetch will also be possible in watch pane.
