### ISSUE TITLE
when debug extension installed my snippets not loading.

### ISSUE THREAD

**Issue by myagizmaktav** [xdebug/vscode-php-debug#854]
your snippets I think is too much can you look this issue thanks.
my specs : https://valid.x86.fr/4msd50

I have a hundred extension have btw but when I installed yours extension pack my snippets not loading is stuck loading.

**Comment by AnrDaemon** [comment]
Please explain step by step what are you doing, what you are expecting and what you are actually observing.

**Comment by zobo** [comment]
No feedback, closing. Please reopen if you can still reproduce this.
