### ISSUE TITLE
watch pannel not showing nested data beyond second level

### ISSUE THREAD

**Issue by vulkanosaure** [xdebug/vscode-php-debug#859]
In my left pannel, in the watch list, if i look at an array (nested at multiple levels),
i click on the arrows to unfold the content, but i can only see the root symbol + 1 nested level, but nothing beyond that.

![image](https://user-images.githubusercontent.com/5021020/201002384-b1796ee2-ec00-424c-8c08-d1aaead357cb.png)

on the other hand, if i hover on my symbol in the text editor to have the little modal display the value, it works fine, i can unfold all the nested levels

PHP version: PHP CGI 7.3.33
Xdebug version: v3.1.5
VS Code extension version: v1.29.0

Your launch.json:
```
{
			"preLaunchTask": "refresh chrome",
			"name": "Listen for XDebug2",
			"type": "php",
			"request": "launch",
			"port": 9000
		}
```
Xdebug php.ini config:

Xdebug logfile (from setting `xdebug.log` in php.ini):
VS Code extension logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php
zend_extension = xdebug
xdebug.output_dir ="D:/wamp/tmp"
xdebug.show_local_vars=0
xdebug.log="D:/wamp/logs/xdebug.log"
xdebug.log_level=7
xdebug.client_port=9000
xdebug.mode = debug
xdebug.start_with_request = yes
```

**Comment by zobo** [comment]
Add `max_depth` under `xdebugSettings` in `launch.json`. I'll link some relevant tasks to explain the issue later.

**Comment by vulkanosaure** [comment]
thanks that solved it !

**Comment by zobo** [comment]
For completeness sake. #808 tracks the underlying issue.
