### ISSUE TITLE
This extension has been disabled because it does not support virtual workspaces

### ISSUE THREAD

**Issue by scottlapoint** [xdebug/vscode-php-debug#873]
VS Code version: 1.74.1
VS Code extension version: 1.29.1

This is more of an install issue for the extension.   It seems to have stopped working ( I did not notice as of which version of VS Code it stopped working but I get an error now 
![Screenshot 2022-12-19 at 8 59 51 AM](https://user-images.githubusercontent.com/24252132/208431775-458a504b-d001-49d4-85f1-8bcf4ff95320.jpg)

This extension has been disabled because it does not support virtual workspaces.  

I am connecting to an old server using RemoteFS extension.  After connecting - php debug disables itself as a virtual workspace loads.  This used to work fine.

I couldn't find any information about it, so I am submitting it as a bug.

**Comment by zobo** [comment]
Thaks, I'll investigate. I often use it with VSCode Remote SSH or Containers.

**Comment by zobo** [comment]
I have done some related work. It does not yet solve the issue but I'm going into this direction. #879

**Comment by mufler** [comment]
Hi! 
I am experiencing same issue with v1.32.1. I am using it in conjunction with the extension SSH-FS v1.26.1.

**Comment by zobo** [comment]
This generally works now, but there's a variable substitution issue.
