### ISSUE TITLE
Relative pathMapping not working in 1.31.0

### ISSUE THREAD

**Issue by motionVector** [xdebug/vscode-php-debug#886]
PHP version: 8.1
Xdebug version: 3
VS Code extension version: 1.31.0

Your launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for Xdebug",
      "type": "php",
      "request": "launch",
      "hostname": "0.0.0.0",
      "port": 9003,
      "pathMappings": {
        "/var/www/html": "${workspaceRoot}/../../"
      }
    }
  ]
}
```

I am using a relative path in my pathMapping and since 1.31.0 this doesn't work anymore. I have seen in the changelog that there have been changes to support uri path mappings. I tried 1.30 again and it worked again. I hope can add support for relative paths again, as it is important for pugin development for me and easier not having to open the whole parent directory in VSCode.

**Comment by zobo** [comment]
Hi. Thanks for reporting. I'll add relevant tests and see how to add back support for this.

**Comment by zobo** [comment]
Let me know if it works now.

**Comment by motionVector** [comment]
Thank you, updated and it works again!
Thanks for fixing this so quickly!
