### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Favboi** [xdebug/vscode-php-debug#907]
Type: <b>Bug</b>

Just startup your VS code with the extension enabled

Extension version: 1.32.1
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.57GB (1.97GB free)|
|Process Argv|--crash-reporter-id b1468bb1-8a91-47c1-8667-0e6c375ffe55 --inspect-extensions=47283 --crash-reporter-id b1468bb1-8a91-47c1-8667-0e6c375ffe55 --inspect-extensions=47753 --crash-reporter-id b1468bb1-8a91-47c1-8667-0e6c375ffe55|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000

```

</details>

**Comment by zobo** [comment]
Sorry, I'll need more info on this. Please provide a debug log as described in the Issue template and reopen the issue.
