### ISSUE TITLE
Feature request: improving debug experience

### ISSUE THREAD

**Issue by lubosdz** [xdebug/vscode-php-debug#916]
PHP version: 8.0+
Xdebug version: 3.2+
VS Code extension version: 1.32.1

This is based on Twitter [tweet](https://twitter.com/lubosdz/status/1676920668015808513) and feature request at [VSCode](https://github.com/microsoft/vscode/issues/187363). 

Having experience with couple of PHP IDEs I feel that debugging experience in VSCode might be significantly improved. This applies explicitly to "Run And Debug" window, which currently offers quite limited configurable options. At least following features could be improved:

* highlighting changed values in debug tree since previous debug step
* support for tabular layout with 3 columns (variables-values-object type - see screen bellow) and with sortable option (e.g. sort column with variables ASC/DESC/NOSORT)
* support docking Run And Debug window at the page bottom to allow wide layout
* less cluttered output - partially would be solved with tabular layout
* "Run and Debug" might contain separate tabs for LOCAL VARS - GLOBAL VARS - CALL STACK - IMMEDIATE EVALUATION - BREAKPOINTS
* design options - highlight color, decrease/increase font size, line height

Since I am not familiar what would require implementation at what level - VSCode core, XDebug or extension, I am putting it all here at once. I understand that features mentioned above would require substantial amount of work, thus I do not assume all will be implemented. However, implementing any single feature mentioned will be greatly appreciated. I am also willing to support features above financially, if rough estimate of how much time / costs would require implementing particular feature could be provided. Thank you.

https://i.ibb.co/N3crZdt/screen-php-friendly-debug-output2.png

<img src='https://i.ibb.co/N3crZdt/screen-php-friendly-debug-output2.png'/>

https://i.ibb.co/X4xrnn1/screen-debug-improvement-VSCode-fix.png

<img src='https://i.ibb.co/X4xrnn1/screen-debug-improvement-VSCode-fix.png'/>

**Comment by zobo** [comment]
Some comments:

> * highlighting changed values in debug tree since previous debug step

VSC "flashes" changed variables, but sadly does not keep them highlighted. Can only be implemented in VS Code, not this extension.

> * support for tabular layout with 3 columns (variables-values-object type - see screen bellow) and with sortable option (e.g. sort column with variables ASC/DESC/NOSORT)

Only possible change in VS Code.

> * support docking Run And Debug window at the page bottom to allow wide layout

Only possible change in VS Code.

> * less cluttered output - partially would be solved with tabular layout

Only possible change in VS Code.

> * "Run and Debug" might contain separate tabs for LOCAL VARS - GLOBAL VARS - CALL STACK - IMMEDIATE EVALUATION - BREAKPOINTS

Only possible change in VS Code.

> * design options - highlight color, decrease/increase font size, line height

Only possible change in VS Code.

Sorry for such a negative feedback, but really none of these can be solved in this extension. Maybe some could be solved with a theme (fonts?) - but again, should not be done here.

I hope the main vscode issue gets some community love.

**Comment by lubosdz** [comment]
@zobo Thank you for your feedback. I could not distinguish which feature could be implemented on what level since I am not familiar with VSCode source. Now it's clear.
