### ISSUE TITLE
Debug not work with php 

### ISSUE THREAD

**Issue by kundisun** [xdebug/vscode-php-debug#946]
PHP version:  7.0.19
Xdebug version:  2.6.0-7.0-vc14-x86_64
VS Code extension version: 1.42.14408

Your launch.json: 
{
    "name": "Listen for Xdebug",
    "type": "php",
    "request": "launch",
    "port": 9003
}

Xdebug php.ini config:
[XDebug]
zend_extension = "D:\xampp\php\ext\php_xdebug-2.6.0-7.0-vc14-x86_64.dll"
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_handler = dbgp
xdebug.remote_mode = req
xdebug.remote_host = localhost
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.remote_port = 9003

Debug can't work with php extension. 
![1208](https://github.com/xdebug/vscode-php-debug/assets/57083627/4bd40efe-fd25-4995-a639-138f346d62ff)

**Comment by zobo** [comment]
Hi. First you are running a very old PHP and Xdebug version that are out of support. The "invalid or missing options" is a DBGP error that is returned from Xdebug, but there's no way to know why without the xdebu.log file.
Third, the `Listening to Xdebug on port 0.0.0.0:9003, :::9003` line tells me you have another PHP extension installed that conflicts with this debugger extension and the extension actually doing the debug is not this one.

**Comment by BryanFonseca** [comment]
This issue is coming from the PHP (devsense) extension. It's been fixed in the pre-release so you could upgrade to that one or downgrade to the last version that worked for you.

https://github.com/DEVSENSE/phptools-docs/issues/460
