### ISSUE TITLE
How to remove annoying inline variable content displays

### ISSUE THREAD

**Issue by dlodge77** [xdebug/vscode-php-debug#960]
PHP version: 8.1.2
Xdebug version: 3.1.2
VS Code extension version: 1.34.0

When paused on a breakpoint, Xdebug in VSCode is showing the content of every variable in-line on every line [as shown in this image](https://i.imgur.com/SEtADj2.png)

I find this highly distracting, I have the watch pane if I want to observe certain variables, or I could otherwise hover my mouse over what I want to see.

I don't like that on every line, it's showing the values automatically, it's very cluttering and confusing sometimes.

It seems to be doing this automatically on my Linux PC but not on my Windows one for some reason.

Any idea how to stop this?

**Comment by zobo** [comment]
Hi. This is a combination feature between the debugger and another extension providing PHP language services (vscode-php-intellisense or some other perhaps). This can be controlled by VSCodes setting. Look for `Debug: Inline Values` or the settings json `debug.inlineValues`. You can set this globally, per user, per machine or remote machine, project and (I think) also per language.

**Comment by dlodge77** [comment]
Ah ok yes it was in Settings> Debug: Inline Values

It was set to "Auto", I changed it to "off" and it's gone now

Many thanks 👍
